shadow-maint/shadow

- man/useradd.8.xml
Let's get rid of all the downstream fixes floating around.
Signed-off-by: Christian Brauner <christian.brauner@mailbox.org>
> add long option --no-create-home to -M

- man/newgidmap.1.xml
- man/newuidmap.1.xml
- src/newgidmap.c
- src/newuidmap.c
Fixed small typos in manual pages and code comments.
> Fixed typos in new{g,u}idmap tools.

- man/groupmems.8.xml
- man/gshadow.5.xml
- man/lastlog.8.xml
- man/limits.5.xml
- man/newusers.8.xml
- man/shadow.5.xml
- man/useradd.8.xml
Found using [anorack](https://github.com/jwilk/anorack).
> man: Fix typos

- lib/commonio.c
- lib/groupio.c
- src/useradd.c
- src/usermod.c
Here are four simple patches from the Fedora shadow package that should be mergeable upstream.
> Four simple patches from the Fedora package to merge

- .gitignore
- Makefile.am
- configure.ac
- man/generate_mans.mak
Update the autotools files to match some recent discussions on the mailing list.
> autotools refresh

- src/newgrp.c
Dynamically added users via pam_group are not listed in groups
databases but are still valid.
> support dynamically added users via pam_group

- man/README.md
Closes https://github.com/shadow-maint/shadow/issues/83
> Add note about conditional man pages

- src/newgrp.c
In case a system uses remote identity server (LDAP) the group lookup
can be very slow. We avoid it when we already know the user has the
group membership.
> newgrp: avoid unnecessary group lookups

- man/passwd.1.xml
This note already exists in chage(1).
> Add note to passwd(1) that --maxdays -1 disables the setting.

- po/nb.po
Translate remaining strings to Norwegian bokmål (nb). Also, cure previous translation of excessive anglicism and apply a more consistent use of actual Norwegian syntax.
> Complete translation to Norwegian bokmål

- man/su.1.xml
- src/su.c
Always parse first non-option as username.
> su.c: be more predictable

- man/po/fr.po
- translated by Jean-Philippe MENGUAL
- proofread by the debian-l10n-french mailing list contributors
Signed-off-by: Alban VIDAL <alban.vidal@zordhak.fr>
> French man translation update

- src/pwck.c
Only check home directory if the UID is not within the SYS user range and there is a home directory set. Fixes #126.
> pwck.c: only check home dirs if set and not a system user

- po/zh_TW.po
> l10n(zh_TW): update translations

- src/vipw.c
Closes #185
If vipw is suspended (e.g. via control-Z) and then resumed, it often gets
immediately suspended. This is easier to reproduce on a multi-core system.
root@buster:~# /usr/sbin/vipw
[1]+  Stopped                 /usr/sbin/vipw
root@buster:~# fg
/usr/sbin/vipw
[1]+  Stopped                 /usr/sbin/vipw
root@buster:~# fg
[vipw resumes on the second fg]
The problem is that vipw forks a child process and calls waitpid() with the
WUNTRACED flag. When the child process (running the editor) is suspended, the
parent sends itself SIGSTOP to suspend the main vipw process. However, because
the main vipw is in the same process group as the editor which received the ^Z,
the kernel already sent the main vipw SIGTSTP.
If the main vipw receives SIGTSTP before the child, it will be suspended …
> Fix vipw not resuming correctly when suspended

- po/nl.po
Hi,
I prepared an updated Dutch translation for shadow version 4.8 (2019-12-01 pot file)
I updated the translation in the first place for Debian, 
but on request of the Debian shadow package maintainer,
Bálint Réczey, I create this pull request.
> updated po file for Dutch

- src/useradd.c
Explanation: use set_selinux_file_context() and reset_selinux_file_context() for create_mail() just as is done for create_home()
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1690527
> useradd: doesn't generate /var/spool/mail/$USER with the proper SELinux user identity

- po/nl.po
Updated po/nl.po (using .pot templates from 2020-01-23)
[nl.po.gz](https://github.com/shadow-maint/shadow/files/4302504/nl.po.gz)
> updated Dutch translation

- src/passwd.c
fix [#223](https://github.com/shadow-maint/shadow/issues/223)
> fix #223comment at #endif does not match condition of #if

- README
- src/faillog.c
Drop out in faillog if time is unreadable.
Adding myself to contributors
Closes #130
> Fix segfault on strftime

- tests/cktools/grpck/37_grpck_invalid_option/grpck.test
per @robin-cruk https://github.com/shadow-maint/shadow/commit/a063580dbb03dfc3b31f7cbbc895fd1840800451#commitcomment-37881077
> spelling: with-an

- lib/prototypes.h
- libmisc/find_new_sub_gids.c
- libmisc/find_new_sub_uids.c
- src/newusers.c
- src/useradd.c
Signed-off-by: Serge Hallyn <shallyn@cisco.com>
> remove unused and misleading 'owner' argument from find_new_sub*

- src/useradd.c
check_uid_range : warnings go to stderr in useradd.c
> check_uid_range : warnings go to stderr

- .travis.yml
Signed-off-by: Christian Brauner <christian@brauner.io>
> travis: add more architectures + enable Coverity

- src/useradd.c
- src/usermod.c
usermod and useradd: check only local groups with -G option
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1727236
> Check only local groups when adding new supplementary groups to a user

- src/lastlog.c
As mentioned in #255 here is a padding, which suits IPv6 Addresses and Link-Local Addresses aswell. I tried to keep it as small as possible, without loosing information.
As the complete width exceeds a typical `80` oldschool terminal, this might be non practical to include. I have more on this topic in #255 and guess this PR gets denied in favor of a more dynamic one.
> Add maximum padding to fit IPv6-Addresses

- lib/Makefile.am
- lib/run_part.c
- lib/run_part.h
- man/useradd.8.xml
- man/userdel.8.xml
- src/useradd.c
- src/userdel.c
This should enable additional user tidy-up when running userdel.
Happy to repeat elsewhere if this is acceptable.
Closes #79.
> Adding run-parts for userdel

- src/grpck.c
> Removing trailing n typo

- src/su.c
> loop until waitpid returns pid_child or error

- man/newgidmap.1.xml
- man/newuidmap.1.xml
> Fix the inaccurate description about ID range in man new{u,g}idmap

- src/gpasswd.c
Signed-off-by: whzhe <wanghongzhe@huawei.com>
> gpasswd.c: fix memory leak in sg_adm

- lib/prototypes.h
- libmisc/xmalloc.c
- src/gpasswd.c
Signed-off-by: whzhe <wanghongzhe@huawei.com>
> xfree: move xfree() function to xmalloc.c

- src/useradd.c
src/useradd.c: log exit code when failing
> useradd: log exit code when failing

- src/useradd.c
Signed-off-by: whzhe <wanghongzhe@huawei.com>
> useradd.c:fix memleak in get_groups

- src/useradd.c
Signed-off-by: whzhe51 <wanghongzhe@huawei.com>
> useradd.c:fix memleaks of grp

- libsubid/Makefile.am
> libsubid: move libmisc.a to last LIBADD entry

- src/useradd.c
> useradd: don't try to create 0 subuids

- man/lastlog.8.xml
man/lastlog.8.xml: add another point to the caveats section regarding
the handling of the lastlog file by external tools.
> man: include lastlog file caveat

- man/newgidmap.1.xml
- man/newuidmap.1.xml
> manpages: mention NSS in new[ug]idmap manpages

- libmisc/idmapping.c
When uid 0 maps host uid 0 into the child userns newer kernels require
CAP_SETFCAP be retained as this allows the caller to create fscaps that
are valid in the ancestor userns. This was a security issue (in very
rare circumstances). So whenever host uid 0 is mapped, retain
CAP_SETFCAP if the caller had it.
Userspace won't need to set CAP_SETFCAP on newuidmap as this is really
only a scenario that real root should be doing which always has
CAP_SETFCAP. And if they don't then they are in a locked-down userns.
(LXC sometimes maps host uid 0 during chown operations in a helper
userns but will not rely on newuidmap for that. But we don't want to
risk regressing callers that want to rely on this behavior.)
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
> libmisc: retain CAP_SETFCAP when mapping uid 0

- lib/commonio.c
- lib/commonio.h
- lib/prototypes.h
- lib/selinux.c
- libmisc/copydir.c
- src/useradd.c
- src/userdel.c
- src/usermod.c
- src/vipw.c
> SELinux modernizations

- libsubid/api.c
The rest of the run isn't likely to get much better, is it?
Thanks to Alexey for pointing this out.
Cc: Alexey Tikhonov <atikhono@redhat.com>
> libsubid_init: return false if out of memory

- libsubid/api.c
> libsubid_init: don't print messages on error

- src/useradd.c
Error: RESOURCE_LEAK (CWE-772): [#def28]
shadow-4.8.1/src/useradd.c:1905: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function has been overridden by a user model.]
shadow-4.8.1/src/useradd.c:1905: var_assign: Assigning: "fd" = handle returned from "open("/var/log/faillog", 2)".
shadow-4.8.1/src/useradd.c:1906: noescape: Resource "fd" is not freed or pointed-to in "lseek".
shadow-4.8.1/src/useradd.c:1917: leaked_handle: Handle variable "fd" going out of scope leaks the handle.
1915|   		/* continue */
1916|   	}
1917|-> }
1918|
1919|   static void lastlog_reset (uid_t uid)
Error: RESOURCE_LEAK (CWE-772): [#def29]
shadow-4.8.1/src/useradd.c:1938: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function …
> useradd.c: fix covscan RESOURCE_LEAK

- libmisc/salt.c
* Move all pre-processor defines to the top of the file.
* Unify the gensalt() function to be useable for all supported hash methods.
* Drop the gensalt_{b,yes}crypt() functions in favor of the previous change.
* Clarify the comment about how crypt_make_salt() chooses the used hash method from the settings in the login.defs file.
* Use memset() to fill static buffers with zero before using them.
* Use a fixed amount of 16 random base64-chars for the sha{256,512}crypt hash methods, which is effectively still less than the recommendation from NIST (>= 128 bits), but the maximum those methods can effectively use (approx. 90 bits).
* Rename ROUNDS_{MIN,MAX} to SHA_ROUNDS_{MIN,MAX}.
* Bugfixes in the logic of setting rounds in BCRYPT_salt_rounds().
* Likewise for YESCRYPT_salt_cost().
* Fix …
> Sanitize code in libmisc/salt.c

- src/useradd.c
useradd generates an empty subid range when adding a new user. This is
caused because there are two variables, one local and the other one
global, that have a very similar name and they are used indistinctly in
the code. The local variable loads the SUB_*ID_COUNT configuration from
the login.defs file, while the global variable, which holds a value of
0, is used to generate the subid range. Causing the empty subid range
problem.
I've merged the two variables in the local one and removed the global
variable. I prefer to do it this way to reduce the scope of it but I'm
open to doing it the other way round.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1990653
> useradd: avoid generating an empty subid range

- src/.gitignore
Signed-off-by: Luís Ferreira <contact@lsferreira.net>
> git: ignore generated check_subid_range

- configure.ac
> Fix parentheses in configure.ac

- .github/workflows/main.yml
> initial github actions attempt

- src/su.c
The buggy code was introduced nearly 5 years ago at the
commit 08fd4b69e84364677a10e519ccb25b71710ee686. The
desired behavior is that SIGKILL will be sent to the
child if it does not exit within 2 seconds after it
receives SIGTERM. However, SIGALRM is masked while
waiting for the child so it cannot wake the program
up after 2 seconds to send SIGKILL.
An example shows the buggy behavior, which exists in
Ubuntu 18.04 LTS (with login 1:4.5-1ubuntu2).
```bash
user1@localhost:~$ su user2 -c '
_term() {
echo SIGTERM received
}
trap _term TERM
while true; do
sleep 1
echo still alive
done'
Password:
still alive
Session terminated, terminating shell...Terminated
SIGTERM received
still alive
still alive
still alive
still alive
```
(SIGTERM is sent in another user1's terminal by
executing `killall …
> su: Fix never alarmed SIGKILL when session terminates

- AUTHORS.md
- README.md
- doc/README.skey
* Change to markdown format
* Include an introduction
* Remove the commit mailing list from the contacts
* Add the IRC channel to the contacts
> README: update content and format

- man/getsubids.1.xml
Define -h option behaviour in getsubids man page.
> man: getsubids define -h

- src/su.c
The SIGCHLD handler could have been ignored by parent process.
Make sure that we have default handling activated.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
> Verify default SIGCHLD handling.

- src/usermod.c
> Remove tailing slash on home dir

- src/passwd.c
> passwd -l should not say that it changes expiry

- .builds/alpine-edge.yml
- tests/libsubid/04_nss/test_range
Mainly to get a musl build in there.
> add alpine edge CI build

- etc/shadow-maint/userdel-pre.d/01-kill_user_procs.sh
> script to kill subjects processes

- libmisc/copydir.c
> Adding nofollow to opens

- src/pwck.c
Improving check around pw_dir which may be NULL
Closes #484
> Fix code comment

- libmisc/salt.c
- src/chpasswd.c
Returns null when fopen fails. Then, using fread with a null pointer will cause a segfault.
> fix segmentation fault when changing password with chpasswd

- configure.ac
- man/po/LINGUAS
- man/po/uk.po
- man/uk/Makefile.am
Synced with the current XML pages, tested to compile as expected. Will be completed asap (~87% now).
Many thanks in advance for merging.
> Add Ukrainian translation for man pages

- libmisc/salt.c
On systems with Linux kernel < 3.17, getentropy() and getrandom() may
exist but return ENOSYS.  Use /dev/urandom as a fallback to avoid a hard
requirement on Linux kernel version.
Fixes #512.
> libmisc: use /dev/urandom as a generic fallback for read_random_bytes()

- po/LINGUAS
- po/ka.po
> po: Georgian translation

- libmisc/copydir.c
The setuid, setgid, and sticky bits are not copied during copy_tree.
Also start with very restrictive permissions before setting ownerships.
This prevents situations in which users in a group with less permissions
than others could win a race in opening the file before permissions are
removed again.
Proof of concept:
```
$ echo $HOME
/home/uwu
$ install -o uwu -g fandom -m 604 /dev/null /home/uwu/owo
$ ls -l /home/uwu/owo
-rw----r-- 1 uwu fandom 0 Sep  4 00:00 /home/uwu/owo
```
If /tmp is on another filesystem, then "usermod -md /tmp/uwu uwu" leads
to this temporary situation:
```
$ ls -l /tmp/uwu/owo
-rw----r-- 1 root root  0 Sep  4 00:00 /tmp/uwu/owo
```
This means that between openat and chownat_if_needed a user of group
fandom could open /tmp/uwu/owo and read the content when it is …
> copy_tree: carefully treat permissions

- lib/groupmem.c
- lib/pwmem.c
- lib/sgroupio.c
- lib/shadowmem.c
- src/sulogin.c
Inspired by https://github.com/shadow-maint/shadow/pull/569#issuecomment-1250090643
> Memory cleaning updates

- src/usermod.c
Report error if usermod asked for moving homedir and it does not exist.
> usermod: report error if homedir does not exist

- man/useradd.8.xml
Resolves: https://github.com/shadow-maint/shadow/issues/580
> man: add missing space in useradd.8.xml

- configure.ac
- lib/defines.h
- lib/getdef.c
- src/newgrp.c
- src/su.c
- src/sulogin.c
> Remove dead code

- lib/defines.h
I'll be using this macro for several changes.
> Add NITEMS(arr) to get the number of elements of an array

- .github/workflows/static-code-analysis.yml
> workflow: update checkout acton v2 to v3

- configure.ac
- man/chsh.1.xml
- man/generate_mans.mak
- man/shadow-man.xsl
- src/Makefile.am
- src/chsh.c
This PR solves the issue defined in:
https://github.com/shadow-maint/shadow/issues/587
> Supporting vendor given "shells" configuration file

- lib/bit.h
> leading_zerosul(): Fix bug

- libmisc/agetpass.c
On 2/19/23 18:09, David Mudrich wrote:
> I am working on a RAM based Linux OS from source, and try to use
> latest versions of all software.  I found shadow needs libbsd's
> readpassphrase(3) as superior alternative to getpass(3).  While
> considering if I a) include libbsd, or include libbsd's code of
> readpassphrase(3) into shadow, found, that libbsd's readpassphrase(3)
> never returns \n or \r
> <https://cgit.freedesktop.org/libbsd/tree/src/readpassphrase.c>
> line 122, while agetpass() uses a check for \n in agetpass.c line 108.
> I assume it always fails.
Indeed, it always failed.  I made a mistake when writing agetpass(), assuming that readpassphrase(3) would keep newlines.
>
> I propose a check of len == PASS_MAX - 1, with false positive error for
> exactly PASS_MAX - 1 long …
> libmisc: agetpass(): Fix bug detecting truncation

- po/zh_CN.po
Update translation
Signed-off-by: maqi maqi@uniontech.com
> [po] Update translation

- po/zh_CN.po
Fixes: d80df2c8a: Update translation
> Fix regression in some translation strings

- lib/get_pid.c
write_mapping() will do the following:
openat(proc_dir_fd, map_file, O_WRONLY);
An attacker could create a directory containing a symlink named "uid_map" pointing to any file owned by root, and thus allow him to overwrite any root-owned file.
> Validate fds created by the user

- AUTHORS.md
> Update AUTHORS to add Marek Michałkiewicz

- etc/shadow-maint/groupdel-pre.d/01-kill_group_procs.sh
- src/groupadd.c
- src/groupdel.c
run_parts currently exists in useradd and userdel, this commit mirrors the functionality with groupadd and groupdel
> run_parts for groupadd and groupdel

- man/po/de.po
find the attached German message catalogue proofread by the German language team.
Best regards
Markus
> Update German translations

- src/usermod.c
And one extra optimization using memmove instead of manually moving bytes.
> usermod: Small optimization using memmove for password unlock

- libmisc/xgetXXbyYY.c
- xgetXXbyYY: tfix
- xgetXXbyYY: Centralize error handling
- xgetXXbyYY: Simplify elifs
- xgetXXbyYY: Reorganize code [dropped]
Cc: @ferivoz, @hallyn
> Typo fix, and while at it, simplify code

- libmisc/strtoday.c
Resolves: https://github.com/shadow-maint/shadow/issues/704
> strtoday: remove unnecessary cast

- share/containers/debian.dockerfile
Latest debian version changed the location and format for the repos file.
> CI: update debian repos

- configure.ac
- lib/prototypes.h
- libmisc/Makefile.am
- man/Makefile.am
- man/cs/Makefile.am
- man/de/Makefile.am
- man/fr/Makefile.am
- man/generate_mans.mak
- man/hu/Makefile.am
- man/it/Makefile.am
- man/ja/Makefile.am
- man/pl/Makefile.am
- man/ru/Makefile.am
- man/sv/Makefile.am
- man/uk/Makefile.am
- man/zh_CN/Makefile.am
- share/containers/fedora.dockerfile
- src/Makefile.am
- src/login.c
- src/useradd.c
- src/usermod.c
Partially resolves: https://github.com/shadow-maint/shadow/issues/674
> Conditionally build lastlog funcionality and documentation

- configure.ac
Fixes: 1bdcfa8d3710bf0a3f180b590017df096d346ade ("lastlog: stop building by default")
> configure: fix lastlog check

- man/po/Makefile.in
Add a comment at the top of that file explaining how to regenerate it.
We should add a README, but I don't have time to draft one right now.
> man/po/Makefile: add a comment to shadow-man-pages.pot

- doc/contributions/build_install.md
Fix https://github.com/shadow-maint/shadow/issues/38
> doc: mention ci workflow file to learn about deps

- etc/shadow-maint/userdel-pre.d/01-kill_user_procs.sh
shadow userdel: add the adaptation to the busybox ps in 01-kill_user_procs.sh
> shadow userdel: add the adaptation to the busybox ps in 01-kill_user_procs.sh

- .github/workflows/runner.yml
Add a CI test to check that make dist builds a usable tarball.
> Add a make dist CI test

- libmisc/Makefile.am
See https://github.com/shadow-maint/shadow/issues/763
> Add alloc.h and bit.h to libmisc_la_SOURCES

- autogen.sh
Add "--enable-lastlog" to include lastlog man pages in tarball.
> autogen: enable lastlog build

- man/Makefile.am
Changes:
* man: include its.rules in tarball
* man: include shadow-man.xsl in tarball
This will help generate the man pages from tarball.
Resolves: https://github.com/shadow-maint/shadow/issues/781
> Fix man pages build

- libmisc/readpassphrase.h
Fixes the build with musl libc.
> Replace __{BEGIN,END}_DECLS with #ifdef __cplusplus

- lib/tcbfuncs.c
> lib/tcbfuncs: operate on file descriptor rather than path

- src/faillog.c
> Drop unnecessary cast to same type

- lib/commonio.c
Bail out if the paths generated for the backup and replacement database are truncated.
> commonio: check for path truncations

- lib/Makefile.am
- lib/agetpass.c
- lib/agetpass.h
- lib/prototypes.h
- lib/pwauth.c
- src/gpasswd.c
- src/newgrp.c
- src/passwd.c
- src/sulogin.c
Closes: <https://github.com/shadow-maint/shadow/issues/797>
> get a pass to see agetpass()

- src/faillog.c
Check for arithmetic overflows when computing offsets to avoid file corruptions for huge UIDs.
> faillog: check for overflows

- autogen.sh
- lib/Makefile.am
- lib/commonio.c
- lib/copydir.c
- lib/env.c
- lib/getdef.c
- lib/groupio.c
- lib/mail.c
- lib/nss.c
- lib/prefix_flag.c
- lib/run_part.c
- lib/setupenv.c
- lib/sprintf.c
- lib/sprintf.h
- src/useradd.c
- src/userdel.c
- src/usermod.c
- src/vipw.c
- tests/unit/Makefile.am
- tests/unit/test_xasprintf.c
Another 100 LoC down.  :D
Merge after the Gentoo fix.  (done)
> [x]asprintf(): The axe is still sharp.

- lib/copydir.c
copydir.c:429:4: warning: Value stored to 'err' is never read [deadcode.DeadStores]
> libmisc/copydir: do not forget errors from directory copy

- lib/defines.h
- lib/prefix_flag.c
- lib/subordinateio.c
These where hard coded, make them definable like SHADOW_FILE
> Define SUBUID_FILE/SUBGID_FILE

- README.md
- STABLE.md
Acked-by: Serge Hallyn <serge@hallyn.com>
Acked-by: Iker Pedrosa <ipedrosa@redhat.com>
Cc: Sam James <sam@gentoo.org>
> README.md, STABLE.md: record the stable branch URL(s).

- lib/commonio.c
- lib/get_pid.c
- lib/nss.c
- src/useradd.c
This is just a cosmetic patch in preparation for others.
> lib/, src/: Align variable definitions

- lib/commonio.c
- lib/copydir.c
- lib/failure.c
- lib/idmapping.c
- lib/log.c
- lib/utmp.c
- src/chfn.c
- src/chpasswd.c
- src/groups.c
- src/newusers.c
- src/useradd.c
- src/usermod.c
See individual commits for more details.
Rebased and updated version of #639.
> Assorted static analyzer inspired fixes (no2)

- lib/idmapping.c
Link: <https://github.com/shadow-maint/shadow/commit/673c2a6f9aa6c69588f4c1be08589b8d3475a520#r136830993>
Cc: @hallyn 
Cc: @ebiederm
> lib/idmapping.c: write_mapping(): Fixx off-by-one bug

- lib/gshadow.c
- lib/list.c
- lib/port.c
- lib/sgetgrent.c
- lib/sgetpwent.c
- lib/sgetspent.c
- lib/subordinateio.c
Queued after <https://github.com/shadow-maint/shadow/pull/893>.  Edit: nah, let's do it already.
> Use strsep(3) instead of open-coding it

- src/usermod.c
Hi @ikerexxe ,
This is my implementation with a goto, plus additional refactors to address your concerns about goto, and also simplify some weirdness.
> Fix 2 memory leaks

- STABLE.md
This pull request tries to merge into `4.15.x` branch.
> STABLE.md: 4.15.x is now stable

- src/getsubids.c
A preparatory changes before main patch #1019.
> libsubid: Dealocate memory on exit

- lib/nss.c
- lib/prototypes.h
- lib/subordinateio.c
- lib/subordinateio.h
- libsubid/api.c
- libsubid/subid.h.in
- src/getsubids.c
- tests/libsubid/04_nss/libsubid_zzz.c
> libsubid: Enhance memory management

- tests/common/config.sh
- tests/libsubid/04_nss/Makefile
- tests/libsubid/04_nss/subidnss.test
- tests/libsubid/04_nss/test_range
A few changes which I had to make in 
https://salsa.debian.org/debian/shadow/-/merge_requests/21
I'd like to make them here instead, then, on each release, export a tests.tar.gz tarball which debian can import.
> Prepare tests/ for debian CI

- lib/subordinateio.c
- tests/libsubid/04_nss/Makefile
Fix a missing space after the -I path
> libsubid test makefile: fix a typo

- Makefile.am
Closes: <https://github.com/shadow-maint/shadow/issues/1027>
Reported-by: @zeha
Co-developed-by: @hallyn
Cc: @ikerexxe
> Makefile.am: Fix location of tests in distribution tarball

- lib/chkname.c
- src/groupadd.c
- src/groupmod.c
- src/newusers.c
- src/pwck.c
- src/useradd.c
- src/usermod.c
Closes: <https://github.com/shadow-maint/shadow/issues/1067>
Reported-by: @schuelermine
---
Revisions:
<details>
-  Add explicit return statements.  [@hallyn ]
(The range-diff is weird.  I'm also showing the diff to clarify.)
```
alx@debian:~/src/shadow/shadow/master$ git range-diff shadow/master gh/badname badname 
1:  d7bed689 = 1:  d7bed689 lib/chkname.c: is_valid_{user,group}_name(): Set errno to distinguish the reasons
2:  f2bfbd3d ! 2:  d6e27cac src/: Invert logic to improve readability
@@ src/groupadd.c: static void grp_update (void)
+
+          exit(E_BAD_ARG);
}
--
+ 
-  /*
-   * All invalid group names land here.
-   */
@@ src/groupadd.c: static void grp_update (void)
-           Prog, group_name);
-
-  exit (E_BAD_ARG);
++  return;
}
/*
@@ src/groupmod.c: …
```
> Recommend --badname only if it is useful

- src/useradd.c
The mode of the file should be 644, but mkstemp(2) was transforming it to 600.
To do this, we need a function that accepts a mode parameter.  While we don't need a flags parameter, to avoid confusion with mkostemp(2), let's add both a flags and a mode parameter.
Link: <https://github.com/shadow-maint/shadow/pull/1080>
Reported-by: @kugarocks
Suggested-by: @kugarocks
---
Revisions:
<details>
-  Add missing octal prefix [@kugarocks ]
```
$ git range-diff shadow/master gh/fmkostemp fmkostemp 
1:  fd362dfb ! 1:  b0193b2e src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>
@@ src/useradd.c: set_defaults(void)
* Create a temporary file to copy the new output to.
*/
-  ofp = fmkstemp(new_file);
-+  ofp = fmkomstemp(new_file, 0, 644);
++  ofp = …
```
> src/useradd.c: Add fmkomstemp() to fix mode of </etc/default/useradd>

- man/passwd.1.xml
- man/subgid.5.xml
- man/subuid.5.xml
Trivial typo fix and list correct programs
> man: Fix information in manual pages

- lib/gshadow.c
This is in preparation for other patches.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/inv shadow/master..inv 
1:  c8799756 = 1:  98bc1d51 lib/gshadow.c: endsgent(): Invert logic to reduce indentation
```
</details>
<details>
-  Several rebases
```
$ git range-diff 98bc1d51^..98bc1d51 shadow/master..gh/inv 
1:  98bc1d51 = 1:  5efa45dc lib/gshadow.c: endsgent(): Invert logic to reduce indentation
```
</details>
> lib/gshadow.c: endsgent(): Invert logic to reduce indentation

- configure.ac
This includes a fix for su regression.
> Release 4.17.1

- man/po/LINGUAS
- man/po/pt.po
Bug-Debian: https://bugs.debian.org/968304
> man: Add Portuguese translation

- etc/login.defs
- share/ansible/roles/ci_run/tasks/alpine.yml
- share/ansible/roles/ci_run/tasks/debian.yml
- share/ansible/roles/ci_run/tasks/fedora.yml
- tests/system/etc/login.defs
This reverts commit dcb6b0f4152c1507a137640fea42401a91f22e2c.
> Revert "etc/login.defs: enable CREATE_HOME"

- man/useradd.8.xml
Closes: Debian Bug <https://bugs.debian.org/1005253>
Cc: Chris Hofstaedtler <zeha@debian.org>
> man/useradd.8.xml: wfix

- .github/workflows/runner.yml
- share/ansible/playbook.yml
- share/ansible/roles/ci_run/tasks/opensuse.yml
- share/container-build.sh
Add an ansible task for openSUSE which will use the configure options used by the official openSUSE package.
> Add openSUSE Tumbleweed CI

- man/useradd.8.xml
D'oh!  I forgot to take @Zugschlus 's patch.  Here I'm forwarding it, with an added signature on his behalf, and some tweaks to the commit message.  He sent it to me here: <https://github.com/alejandro-colomar/shadow/pull/2>.
Cc: @zeha , @hallyn
> man/useradd.8.xml: Document new exit code 19 (E_BAD_NAME)

- configure.ac
> configure.ac: stop checking for utmp location

- .github/actions/install-dependencies/action.yml
This accelerates the CI.
Resolves: https://github.com/shadow-maint/shadow/issues/1240
Link: <https://101010.pl/@nabijaczleweli/114149412203886808>
Reported-by: nabijaczleweli <nabijaczleweli@nabijaczleweli.xyz>
> CI: purge man-db

- man/useradd.8.xml
> man/useradd.8.xml: fix the CREATE_HOME description

- lib/sizeof.h
Link: <https://stackoverflow.com/a/79369560/6872717>
> lib/sizeof.h: Make sure STRLEN() only accepts string literals

- configure.ac
The test was about lastlog, not subids
> configure: Fix typo

- configure.ac
Let's do one quick prerelease before we release 4.18 tomorrow.
> Pre-release 4.18.0-rc2

- lib/pam_pass_non_interactive.c
- src/usermod.c
- src/vipw.c
> Fix fprintf(3)-related issues.

- lib/utmp.c
This is an alternative version of PR #1329.
The first commit was cherry-picked from PR #1290 to keep the author as [Alejandro](https://github.com/alejandro-colomar) were the first who created and published this commit.
> Fixed memory leak in UTMP processing

- man/chsh.1.xml
Reference the commit messages.
> man/chsh: remove duplicate paragraph

- po/nl.po
From: @Frans-Spiesschaert 
Closes: <https://github.com/shadow-maint/shadow/issues/1360>
Cc: @zeha 
---
I've added a Signed-off-by @Frans-Spiesschaert tag, as it provided a PGP signature of the file.
> po/nl.po: Update

- lib/sssd.c
- src/grpck.c
- src/pwck.c
- fix a bug introduced in 59e5eef38f899cf00925f0117e3173566b14a5fc
- don't trigger useless cache flush
> A couple of patches around SSSD integration
