src/usermod.c

The current implementation of subuid/subgid support in usermod requires the
user to be a local user present in /etc/passwd.  There doesn't seem to be a
good reason for this; subuids should work equally well for users whose
records are in other NSS databases.
Bug-Ubuntu: https://bugs.launchpad.net/bugs/1475749
Author: Steve Langasek <steve.langasek@ubuntu.com>
Acked-by: Serge Hallyn <serge.hallyn@ubuntu.com>

Don't limit subuid/subgid support to local users

---

lib/commonio.c
lib/groupmem.c
lib/pwmem.c

The functions __gr_dup and __pw_dup do not explicitly zero the
memory which hold the passwords after free. The gr_free and pw_free
functions do this explicitly.
To guarantee same behaviour, it's possible to call these *_free
functions directly from __*_dup, because the memory is initialized
with zeros at the beginning. Calling free(NULL) has no negative
effect and can be considered safe these days.
Also prevent a memory leak in commonio on one of its error paths.

Clear passwords on __gr_dup/__pw_dup errors and fix memory leak

---

src/newgrp.c

Reported at https://alioth.debian.org/tracker/?func=detail&atid=411478&aid=315135&group_id=30580
by Alejandro Joya (afjoyacr-guest)
Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>

Fix a resource leak in syslog_sg

---

etc/login.defs
lib/commonio.c
lib/commonio.h
lib/getdef.c
lib/groupio.c
lib/pwio.c
lib/sgroupio.c
lib/shadowio.c
lib/subordinateio.c
src/chage.c
src/chfn.c
src/chgpasswd.c
src/chpasswd.c
src/chsh.c
src/gpasswd.c
src/groupadd.c
src/groupdel.c
src/groupmems.c
src/groupmod.c
src/grpck.c
src/grpconv.c
src/grpunconv.c
src/newusers.c
src/passwd.c
src/pwck.c
src/pwconv.c
src/pwunconv.c
src/useradd.c
src/userdel.c
src/usermod.c

I'm patching shadow to be more robust when operating in a-typical environments, but these improvements are general enough, that I believe warrant inclusion upstream by default.
Specifically there are deployments that use nss-altfiles / nss-extrausers and thus ship alternative group/passwd/shadow/gshadow files elsewhere on the filesystem (e.g. /var/lib/passwd). In such configurations admin modifiable files /etc/passwd, /etc/group and so on may not exist. Furthermore if one is bootstrapping a new distribution from scratch, it would be nice to point shadow utilities at an empty /etc and start creating default system accounts with useradd/usermod/groupadd/etc utilities without writing initial files by hand. Hence these changes:
* create all databases, with correct (?! used typical permissions …

Make shadow more robust in hostile environments

---

etc/login.defs
libmisc/find_new_sub_gids.c
libmisc/find_new_sub_uids.c
src/useradd.c

- Use an allocation of 65536 uids and gids to allow for POSIX-compliant
user owned namespaces.
- Don't allocate a uid/gid map to system users.
Unfortunately checking for --system isn't quite enough as some
distribution wrappers always call useradd without --system and take care
of choosing a uid and gid themselves, so also check whether the
requested uid/gid is in the user range.
This is taken from a patch I wrote for Ubuntu a couple years ago and
which somehow didn't make it upstream.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

Tweak uid/gid map default configuration

---

man/lastlog.8.xml
src/Makefile.am
src/lastlog.c

This functionality is useful because there is now a feature
of Linux-PAM's pam_lastlog module to block expired users (users
which did not login recently enough) from login. This commit
complements it so the sysadmin is able to unblock such expired user.
Signed-off-by: Tomáš Mráz <tmraz@fedoraproject.org>

Add ability to clear or set lastlog record for user via lastlog command

---

man/chgpasswd.8.xml
man/chpasswd.8.xml
man/limits.5.xml
man/newgidmap.1.xml
man/nologin.8.xml
man/passwd.1.xml
man/pwck.8.xml
man/shadow.5.xml
man/su.1.xml
man/suauth.5.xml
man/useradd.8.xml

While reading the shadow.5 manpage a colleague noticed a typo, so I took it upon me to fix these. Thanks for a useful toolsuite!

man: Fix a number of typos for various commands.

---

man/usermod.8.xml

Should have been: '[...] but only checkS [...]'.
So there was a missing 's'. Architectures isn't the right word either.
I decided to write the whole sentence new.

Fix sentence in usermod manual

---

src/expiry.c
src/gpasswd.c
src/login.c
src/su.c
src/sulogin.c

Some of the supplied tools use functions which are not signal-safe.
Most of the times it's exit() vs. _exit().
In other times it's how the standard output or standard error is
handled. FILE-related functions shall be avoided, therefore I replaced
them with write().
Also there is no need to call closelog(). At worst, it allows to
trigger a deadlock by issuing different signal types at bad timings.
But as these fixes are about race conditions, expect bad timings in
general for these bugs to be triggered. :)

Fixed signal races in shadow tools.

---

src/su.c

- Log INFO instead of ERR on `su missing-user`
- Log NOTICE/WARN instead of ERR on pam_authenticate failure (wrong password for example)
*This PR is part of an ongoing effort to make syslog entries more expressive in Debian. Similar issues in important components like OpenSSH and PAM [were addressed upstream](https://github.com/hemio-ev/expressive-syslog/blob/master/README.md#sshd).*

Reduces syslog priority of common usage events

---

src/su.c

This code was added in dd50014055a36969153e83cf3675d9559fa6a200,
but both calls to snprintf were missing their size arguments, which is
obviously wrong (and fails to compile with GCC 6).
Rebased on top of the fix added later.

Add missing size args to snprintf calls.

---

src/useradd.c

The get_defaults() has to be called before processing the flags.
Signed-off-by: Tomáš Mráz <tmraz@fedoraproject.org>

Fix regression in useradd not loading defaults properly.

---

src/Makefile.am

These assignments were pasted as is into the Makefile and
ended up as part of a rule. (Usually the .PRECIOUS rule
which is why the build system never attempted to execute it
as commands, hiding the problem.)
Signed-off-by: Wolfgang Bumiller <wry.git@bumiller.com>
Reported-by: Rahel A <ra00177@surrey.ac.uk>

buildsys: fix suidubins assignments

---

lib/sgroupio.c
lib/shadowio.c

Otherwise we get build warnings like:
sgroupio.c:255:6: warning: implicit declaration of function 'getdef_bool' [-Wimplicit-function-declaration]
shadowio.c:131:6: warning: implicit declaration of function 'getdef_bool' [-Wimplicit-function-declaration]

include getdef.h for getdef_bool prototype

---

.travis.yml
man/Makefile.am
man/generate_mans.mak
man/generate_translations.mak

kickstart travis integration
currently fails because:
- #50 added invalid `po/pl.po` with fatal errors - it should be reverted (#50) or fixed (#56) (example build with reverted po: https://travis-ci.org/glensc/shadow/builds/181503106)
also removes `false` calls from `$(MAN_mans)` targets because it was not possible to disable man generation, it always invoked those targets regardless of `--disable-man` option
does not enable all features:
```
shadow will be compiled with the following features:
auditing support:		no
CrackLib support:		no
PAM support:			no
SELinux support:		no
ACL support:			no
Extended Attributes support:	no
tcb support (incomplete):	no
shadow group support:		yes
S/Key support:			no
SHA passwords encryption:	yes
nscd support:			yes
subordinate IDs support:	yes
``` …

enable travis integration

---

libmisc/Makefile.am
src/Makefile.am

Catch up with [Automake](http://git.savannah.gnu.org/cgit/automake.git/commit/?id=1415d22f6203206bc393fc4ea233123ba579222d), where the deprecation notice landed in
[v1.6b, cut 2002-07-28](http://git.savannah.gnu.org/cgit/automake.git/tag/?id=Release-1-6b).  Avoids:
```
$ autoreconf -v -f --install
...
libmisc/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
...
src/Makefile.am:10: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
...
```

*/Makefile.am: Replace INCLUDES with AM_CPPFLAGS

---

src/useradd.c

* Print error message if exec fails, for some reason.
* Don't need a static pointer to refer to static string. It doesn't save us anything.
* Remove excess parenthesis.

Print error on exec failure + cosmetic changes

---

lib/commonio.c

If ptr->line == NULL for an entry, the first cycle will exit,
but the second one will happily write past entries buffer.
We actually do not want to exit the first cycle prematurely
on ptr->line == NULL.
Signed-off-by: Tomas Mraz <tmraz@fedoraproject.org>

Fix buffer overflow if NULL line is present in db.

---

lib/prototypes.h
libmisc/Makefile.am
libmisc/gettime.c
src/chpasswd.c
src/newusers.c
src/passwd.c
src/useradd.c
src/usermod.c

The third field in the /etc/shadow file (sp_lstchg) contains the date of
the last password change expressed as the number of days since Jan 1, 1970.
As this is a relative time, creating a user today will result in:
username:17238:0:99999:7:::
whilst creating the same user tomorrow will result in:
username:17239:0:99999:7:::
This has an impact for the Reproducible Builds[0] project where we aim to
be independent of as many elements the build environment as possible,
including the current date.
This patch changes the behaviour to use the SOURCE_DATE_EPOCH[1]
environment variable (instead of Jan 1, 1970) if valid.
[0] https://reproducible-builds.org/
[1] https://reproducible-builds.org/specs/source-date-epoch/
Signed-off-by: Chris Lamb <lamby@debian.org>

Make the sp_lstchg shadow field reproducible.

---

src/su.c

Do not reset the pid_child to 0 if the child process is still
running. This else-condition can be reached with pid being -1,
therefore explicitly test this condition.
This is a regression fix for CVE-2017-2616. If su receives a
signal like SIGTERM, it is not propagated to the child.
Reported-by: Radu Duta <raduduta@gmail.com>
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>

Reset pid_child only if waitpid was successful.

---

ChangeLog

The recently added entries were actually for 2017.

Correct wrong year in ChangeLog dates

---

configure.ac

Print a warning in case xsltproc is missing.

Add warning when turning off man switch

---

src/userdel.c

The userdel checks for users with getpwnam() which might not work
properly in chroot. Check for the user's presence in local files only.
Fixes issue #89

Make userdel to work with -R.

---

src/chage.c

Tiny, tiny change but one I noticed during a training course.
Maximum was misspelled as maximim in two places.

Fixes mispelling of MAX_DAYS help text

---

README
src/newgidmap.c

This is necessary to match the kernel-side policy of "self-mapping in a
user namespace is fine, but you cannot drop groups" -- a policy that was
created in order to stop user namespaces from allowing trivial privilege
escalation by dropping supplementary groups that were "blacklisted" from
certain paths.
This is the simplest fix for the underlying issue, and effectively makes
it so that unless a user has a valid mapping set in /etc/subgid (which
only administrators can modify) -- and they are currently trying to use
that mapping -- then /proc/$pid/setgroups will be set to deny. This
workaround is only partial, because ideally it should be possible to set
an "allow_setgroups" or "deny_setgroups" flag in /etc/subgid to allow
administrators to further restrict newgidmap(1).
Ref: …

newgidmap: enforce setgroups=deny if self-mapping a group

---

src/newusers.c

Edited to code to avoid freeing up of NULL pointer which is causing the Segmentation fault. 
` newusers newusers.txt 
*** Error in `newusers': double free or corruption (!prev): 0x000055aa28dc8030 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f45a98aa7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f45a98b337a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f45a98b753c]
newusers(+0xaa97)[0x55aa271efa97]
newusers(+0x8825)[0x55aa271ed825]
newusers(+0x89de)[0x55aa271ed9de]
newusers(+0x5ea9)[0x55aa271eaea9]
newusers(+0x3eb7)[0x55aa271e8eb7]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f45a9853830]
newusers(+0x4fd9)[0x55aa271e9fd9]
======= Memory map: ========
55aa271e5000-55aa271f5000 r-xp 00000000 08:01 134366 …

Double freeing up pointers , Causing Segmentation fault

---

src/su.c

All arguments are already reordered and parsed by getopt_long since e663c69, so manual '--' slurping is wrong.
Closes #101

su.c: fix '--' slurping

---

src/su.c

When "su -l" is used the behaviour is described as similar to
a direct login. However login.c is doing a setup_env(pw) and then a
pam_getenvlist() in this scenario. But su.c is doing it the other
way around. Which means that the value of PATH from /etc/environment
is overridden. I think this is a bug because the man-page claims that 
"-l": "provides an environment similar to what the user would expect had 
the user logged in directly." and login.c is using the PATH from /etc/environment.
This will fix:
https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/984390

su.c: run pam_getenvlist() after setup_env

---

src/nologin.c

Sometimes getlogin() may fail, e.g., in a chroot() environment or due to NSS misconfiguration. Logging UID allows for investigation and troubleshooting in such situation.

Log UID in nologin

---

configure.ac
lib/prototypes.h
libmisc/utmp.c
src/login.c

This allows shadow-utils to build on systems like Adélie, which have no
<utmp.h> header or `struct utmp`.  We use a <utmpx.h>-based daemon,
[utmps], which uses `struct utmpx` only.
Tested both `login` and `logoutd` with utmps and both work correctly.
[utmps]: http://skarnet.org/software/utmps/
---
NOTE: This has not been tested on a glibc system yet (I don't have any outside of chroots; it is not possible for me to test `login` / `logoutd` functionality in a chroot.)

[WIP] Support systems that only have utmpx

---

libmisc/idmapping.c
libmisc/idmapping.h

Commit 1ecca84 ("new[ug]idmap: not require CAP_SYS_ADMIN in the parent userNS")
does contain a wrong commit message, is lacking an explanation of the
issue, misses some simplifications and hardening features. This commit
tries to rectify this.
In (crazy) environment where all capabilities are dropped from the
capability bounding set apart from CAP_SET{G,U}ID setuid- and
fscaps-based new{g,u}idmap binaries behave differently when writing
complex mappings for an unprivileged user:
1. newuidmap is setuid
unshare -U sleep infinity &
newuidmap $? 0 100000 65536
First file_ns_capable(file, ns, CAP_SYS_ADMIN) is hit. This calls into
cap_capable() and hits the loop
for (;;) {
/* Do we have the necessary capabilities? */
if (ns == cred->user_ns)
return cap_raised(cred->cap_effective, cap) ? 0 : …

new{g,u}idmap: align setuid and fscaps behavior

---

lib/getdef.c
man/Makefile.am
man/lastlog.8.xml
man/login.defs.5.xml
man/login.defs.d/LASTLOG_UID_MAX.xml
man/useradd.8.xml
man/usermod.8.xml
src/lastlog.c
src/login.c
src/useradd.c
src/usermod.c

As the large uids are usually provided by remote user identity and
authentication service, which also provide user login tracking,
there is no need to create a huge sparse file for them on every local
machine.

login.defs: Add LASTLOG_UID_MAX variable to limit lastlog to small uids.

---

man/login.defs.d/SUB_GID_COUNT.xml
man/login.defs.d/SUB_UID_COUNT.xml

Subject says it all. A trivial fix.

Fix the default mentioned in man page for SUB_UID/GID_COUNT variables.

---

lib/commonio.c

The db->fp can be NULL if commonio_unlock() is called when the
shadow file is opened but did not exist before.

Do not crash in commonio_close if database FILE not opened.

---

src/grpck.c
src/pwck.c

Fix #155
signed-off-by: Charlie Vuillemez <cvuillemez@users.noreply.github.com>

Do not flush nscd and sssd cache in read-only mode

---

src/chpasswd.c

When a line that goes over the size of the buffer is read in, an error message is display, but the remaining characters at the end of the line aren't ignored. This can result in the following output:
```
$ (seq 8500 | tr -d '\n' && echo user:password) | sudo src/chpasswd
chpasswd: line 1: line too long
chpasswd: line 2: line too long
chpasswd: line 3: line too long
chpasswd: line 4: line too long
chpasswd: line 5: user '884698470847184728473847484758476847784788479848084818482848384848485848684878488848984908491849284938494849584968497849884998500user' does not exist
chpasswd: error detected, changes ignored
```
This change reads of the remaining output until the next newline, or EOF character.

Fix chpasswd long line handling

---

src/usermod.c

In case the home directory is not a real home directory
(owned by the user) but things like / or /var or similar,
it is unsafe to change ownership of home directory content.
The test checks whether the home directory is owned by the
user him/herself, if not no ownership modification of contents
is performed.

usermod: Guard against unsafe change of ownership of home contents

---

README
configure.ac
lib/defines.h
libmisc/gettime.c
libmisc/pwd2spwd.c
src/pwck.c
src/pwconv.c

From <https://github.com/shadow-maint/shadow/pull/71>:
```
The third field in the /etc/shadow file (sp_lstchg) contains the date of
the last password change expressed as the number of days since Jan 1, 1970.
As this is a relative time, creating a user today will result in:
username:17238:0:99999:7:::
whilst creating the same user tomorrow will result in:
username:17239:0:99999:7:::
This has an impact for the Reproducible Builds[0] project where we aim to
be independent of as many elements the build environment as possible,
including the current date.
This patch changes the behaviour to use the SOURCE_DATE_EPOCH[1]
environment variable (instead of Jan 1, 1970) if valid.
```
This updated PR adds some missing calls to gettime (). This was originally
filed by Johannes Schauer in Debian as …

Make the sp_lstchg shadow field reproducible (re. #71)

---

configure.ac

The documentation uses DocBook 4.5 DOCTYPE but the configure script checked for 4.1.2.

build: Check correct DocBook version

---

lib/commonio.c
lib/commonio.h
lib/groupio.c
lib/pwio.c
lib/sgroupio.c
lib/shadowio.c
lib/subordinateio.c

This PR fixes two issues related to the locking of the databases.

Use lckpwdf() again if prefix is not set and fix a possible DoS in locking

---

lib/spawn.c

lib/spawn.c run_command: don't loop forever if waitpid() is returning ECHILD
If SIGCHILD is being ignored, waitpid() will forever error with ECHILD and
this loop with never end, so don't loop if it erros with ECHILD.

lib/spawn.c run_command: don't loop forever if waitpid() is returning ECHILD

---

configure.ac

A configure error occurs when /bin/sh -> dash:
checking for is_selinux_enabled in -lselinux... yes
checking for semanage_connect in -lsemanage... yes
configure: 16322: test: yesyes: unexpected operator
Use "=" instead of "==" since dash doesn't support this operator.
Signed-off-by: Yi Zhao <yi.zhao@windriver.com>

configure.ac: fix configure error with dash

---

etc/login.defs
src/usermod.c

46331648 introduced LASTLOG_UID_MAX and (probably by a mistake) LASTLOG_MAX_UID. The latter one is apparent typo unsupported by the parser.
46331648 also says LASTLOG_UID_MAX that LASTLOG_UID_MAX is going to be added to login.defs. But that change is missing.

Fixes of LASTLOG_UID_MAX and login.defs

---

src/Makefile.am

Some distros don't care about the split between /bin, /sbin, /usr/bin,
and /usr/sbin, so let them easily stuff binaries wherever they want.
This also fixes a problem during installation where-in a loop of 'chmod
4755' calls will mostly fail (regardless of configuration). However, because
the last two succeed (newuidmap/newgidmap), make considers the command to be a
success. Somewhat not-amusingly, configuring shadow with --with-fcaps will
cause installation to fail because the final chmod call is now a failing one.

Honor --sbindir and --bindir for binary installation

---

man/chage.1.xml
src/chage.c

New option to print dates in ISO format.
EDIT: For clarity, iso8601 date format to match date input formats (YYYY-MM-DD). The intention here is to provide consistency between date display and input.

chage.c: add support for YYYY-MM-DD date printing

---

src/useradd.c

src/useradd.c: including directory name in dir existence error. Prefixing output lines with program name.
Fixes #105 
Fixes #106

useradd.c: including directory name in directory existence error message

---

man/README.md
man/generate_translations.mak

This patch was taken from Fedora Rawhide
https://src.fedoraproject.org/rpms/shadow-utils/raw/b41cff195605b29af23d2ad62a60ddc5a2d89786/f/shadow-4.6-use-itstool.patch
With this patch I was able to successfully build the man pages. Closes https://github.com/shadow-maint/shadow/pull/163. cc @jtojnar @hallyn

man: generate translations using itstool instead of xml2po

---

src/useradd.c

Check whether shell argument given with `-s` is actually present and executable.
Fix https://github.com/shadow-maint/shadow/issues/186

useradd: check for valid shell argument

---

src/useradd.c

Fix typo in 88fa0651bfa4be0c819da0027456f5046a3b4967.
For some reason my git push -f seems not to have worked.

Fix typo in access of shell command

---

man/passwd.5.xml
man/shadow.5.xml

Synchronize how passwd(5) and shadow(5) describe the password field.
Reorder the descriptions more logically.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

man: sync and reorder password field descriptions

---

configure.ac
etc/pam.d/Makefile.am
man/Makefile.am
src/Makefile.am

Enabled by default
This is necessary because coreutils and util-linux can also provide su
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>

build: Make build/installation of su and its support files optional

---

src/Makefile.am

This reverts commit e293aa9cfca0619a63616af75532637dab60d49d.
See https://github.com/shadow-maint/shadow/issues/196
Some distros still care about `/bin` vs `/usr/bin`. This commit makes
it so all binaries are always installed to `/bin`/`/sbin`. The only way to
restore the previous behaviour of installing some binaries to
`/usr/bin`/`/usr/sbin` is to revert the patch.

Revert "Honor --sbindir and --bindir for binary installation"

---

lib/selinux.c

We use fprintf(), stderr etc, so we should include stdio.h.

selinux: include stdio

---

man/usermod.8.xml

Changelog:
1) modified:   man/usermod.8.xml
Removed duplicate "badnames" options entry.

Deduplicate usermod manual (fixes #202)

---

configure.ac

Here's a sad story:
* 70971457 is merged into shadow, allowing newgidmap/newuidmap to be
installed with file caps rather than setuid.
* https://bugs.archlinux.org/task/63248 is filed to take advantage of
this.
* The arch maintainer of the 'shadow' package notices that this doesn't
work, and submits a pull request to fix this in shadow.
* edf7547ad5 is merged, fixing the post install hooks.
The problem here is that distros have been building shadow with PAM for
O(years), but the install hooks have silently failed due to the
combination of the directory mismatch (suidubins vs suidsbins) and later
success with setuid'ing newgidmap/newuidmap.
With the install hooks fixed, those of us (Arch[1] and Gentoo[2] so far)
who never built shadow explicitly with --enable-account-tools-setuid are
now …

Don't auto-enable ACCT_TOOLS_SETUID if PAM is detected

---

src/Makefile.am

`make` runs each line in a shell and bails out on error,
however, the shell is not started with `-e`, so commands in
`for` loops can fail without the error actually causing
`make` to bail out with a failure status.
For instance, the following make snippet will end
successfully, printing 'SUCCESS', despite the first `chmod`
failing:
all:
touch a b
for i in a-missing-file a b; do \
chmod 666 $$i; \
done
@echo SUCCESS
To prevent wrong paths in install scripts from remaining
unnoticed, let's activate `set -e` in the `for` loop
subshells.
Signed-off-by: Wolfgang Bumiller <w.bumiller@proxmox.com>

Makefile: bail out on error in for-loops

---

man/nologin.8.xml
src/nologin.c

If SSH_ORIGINAL_COMMAND is set, it will be added to the syslog entry.
Closes #123.

Adding logging of SSH_ORIGINAL_COMMAND to nologin.

---

etc/login.defs
lib/getdef.c
man/login.defs.5.xml
man/login.defs.d/UMASK.xml
src/newusers.c
src/useradd.c

This option can be used to set a separate mode for useradd(8) and
newusers(8) to create the home directories with.
If this option is not set, the current behavior of using UMASK
or the default umask is preserved.
There are many distributions that set UMASK to 077 by default just
to create home directories not readable by others and use things like
/etc/profile, bashrc or sudo configuration files to set a less restrictive
umask. This has always resulted in bug reports because it is hard
to follow as users tend to change files like bashrc and are not about
setting the umask to counteract the umask set in /etc/login.defs.
A recent change in sudo has also resulted in many bug reports about
this. sudo now tries to respect the umask set by pam modules and on
systems where pam does not set a …

add new UMASK_HOME login.defs option

---

src/useradd.c

This commit adds a from= field to the end of the useradd log entry.
Casting user_name to tallylog_reset to silence a compiler warning.
Closes #198.

Adding tty logging to the useradd command

---

etc/login.defs
lib/getdef.c
man/login.defs.5.xml
man/login.defs.d/HOME_MODE.xml
man/newusers.8.xml
man/useradd.8.xml
src/newusers.c
src/useradd.c

@hallyn sorry, forgot to add the file after rebasing the PR.
I rebased again and added the missing file and added references to the new variable to the man pages of useradd(8) and newusers(8) which I forgot before.
Fixed version of #208

add new HOME_MODE login.defs(5) option

---

src/useradd.c

Although it is a good idea to check for an inadvertent typo
in the shell name it is possible that the shell might not be present
on the system yet when the user is added.

Make the check for non-executable shell only a warning.

---

libmisc/user_busy.c

In case there is a regular user with a process running on a system
with uid falling into a namespaced uid range of another user.
The user with the colliding namespaced uid range will not be
allowed to be deleted without forcing the action with -f.
The user_busy() is adjusted to check whether the suspected process
is really a namespaced process of the user being deleted.

Do not mistake a regular user process for a namespaced one

---

libmisc/prefix_flag.c
libmisc/root_flag.c

Recognise --root=path in addition to --root path (and similarly for
--prefix) to match the syntax accepted by getopt_long.
Fixes #218

libmisc: Accept --root=path and --prefix=path option syntax

---

man/useradd.8.xml

Explanation: clarify the useradd -d parameter as it does create directory HOME_DIR if it doesn't exit.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1677005

useradd: clarify the useradd -d parameter behavior in man page

---

etc/login.defs
man/login.defs.d/ENCRYPT_METHOD.xml
man/login.defs.d/SHA_CRYPT_MIN_ROUNDS.xml

According to crypt(5), MD5 and DES should not be used for new
hashes. Also the default number of SHA rounds chosen by libc is orders
of magnitude too low for modern hardware. Let's warn the users about
weak choices.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

login.defs: warn about weak choices

---

libmisc/idmapping.c

Do not include <sys/prctl.h> we don't have <sys/capability.h>, we don't
need prctl in that case anyway.
Signed-off-by: Samuel Thibault <samuel.thibault@ens-lyon.org>

Fix hurd build

---

.travis.yml

Also remove the openssl section since both lxc and lxcfs don't need it
either.
Signed-off-by: Christian Brauner <christian@brauner.io>

travis: reorder sections and add regenerated coverity token

---

lib/groupmem.c
lib/prototypes.h
man/groupadd.8.xml
man/groupmod.8.xml
src/groupadd.c
src/groupmod.c

Add a -U option which adds new usernames as members.  For groupmod,
also add -a (append), without which existing members are removed.
Closes #265

add -U option to groupadd and groupmod

---

src/useradd.c

covscan was complaining abot calling chmod and ignoring the return value:
Error: CHECKED_RETURN (CWE-252):
shadow-4.6/src/useradd.c:2084: check_return: Calling "chmod(prefix_user_home, mode)" without checking return value. This library function may fail and return an error code.
<pre>
2082|   		mode_t mode = getdef_num ("HOME_MODE",
2083|   		                          0777 & ~getdef_num ("UMASK", GETDEF_DEFAULT_UMASK));
2084|-> 		chmod (prefix_user_home, mode);
2085|   		home_added = true;
2086|   #ifdef WITH_AUDIT
</pre>

useradd: check return value from chmod and log it

---

src/chfn.c

This is a stability fix, not a security fix, because the affected -o
option can only be used by root and it takes a modified passwd file.
If a gecos field for a user has BUFSIZ characters without commas and an
equals sign (i.e. a huge slop/extra field) and chfn is called with -o,
then a buffer overflow occurs.
It is not possible to trigger this with shadow tools. Therefore, the
passwd file must be modified manually.
I have fixed this unlikely case the easiest and cleanest way possible.
Since chfn bails out if more than 80 characters excluding commas are
supposed to be written into gecos field, we can stop processing early on
if -o argument is too long.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>

chfn: Prevent buffer overflow.

---

man/grpck.8.xml
src/grpck.c

'gshadow' man page suggests that "You should use the same list of users
as in /etc/group", but not must.
Closes #261

Option to suppress group/gshadow inconsistencies

---

src/chage.c

This is merely a stability fix, not a security fix.
As the root user, it is possible to set time values which later on
result in signed integer overflows.
For this to work, an sgetspent implementation must be used which
supports long values (glibc on amd64 only parses 32 bit, not 64).
Either use musl or simply call configure with following environment
variable:
$ ac_cv_func_sgetspent=no ./configure
Also it is recommended to compile with -fsanitize=undefined or
-ftrapv to see these issues easily.
Examples to trigger issues when calling "chage -l user":
$ chage -d 9223372036854775807 user
$ chage -d 106751991167300 user
$ chage -M 9999 user
$ chage -d 90000000000000 user
$ chage -I 90000000000000 user
$ chage -M 9999 user
$ chage -E 9223372036854775807 user
While at it, I fixed casting …

chage: Prevent signed integer overflows.

---

lib/sssd.c

Instead of printing warning in stderr print it to file. This way the
user is not spammed with unnecessary messages when updating packages.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1749001

lib/sssd: redirect warning message to file

---

lib/getdef.c

The login.defs is shared between more upstream projects (util-linux,
etc.). We need to improve compatibility between the projects do not
report valid, but foreign items.
Addresses: https://github.com/shadow-maint/shadow/issues/276

getdefs: add foreign (non-shadow-utils) items

---

man/groupdel.8.xml
src/groupdel.c

Existing help output advertises --force as a long opt.
-f, --force                   delete group even if it is the primary group of a user
But errors when the long opt is used.
groupdel: unrecognized option '--force'
Signed-off-by: Jamin W. Collins <jamin.collins@gmail.com>

add parsing support for advertised force long opt

---

src/newgrp.c
src/useradd.c

Error: CLANG_WARNING: [#def31]
src/newgrp.c:448:2: warning: Value stored to 'gid' is never read [deadcode.DeadStores]
```
gid = getgid ();
```
Error: RESOURCE_LEAK (CWE-772): [#def39] [important]
src/useradd.c:728: alloc_fn: Storage is returned from allocation function "get_local_group".
src/useradd.c:728: var_assign: Assigning: "grp" = storage returned from "get_local_group(list)".
src/useradd.c:728: overwrite_var: Overwriting "grp" in "grp = get_local_group(list)" leaks the storage that "grp" points to.
```
726|   		 * GID values, otherwise the string is looked up as is.
727|   		 */
728|-> 		grp = get_local_group (list);
729|
730|   		/*
```

Two covscan issues

---

lib/commonio.c

lib/commonio.c: after writing to the lock file, force a file sync to
the storage system.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1862056

commonio: force lock file sync

---

man/newusers.8.xml

man/newusers.8.xml: clarify that newusers doesn't create parent
directories of the new user's home directory.

newusers: doesn't create parent home directories

---

etc/Makefile.am
etc/useradd
src/useradd.c

Avoids installing inconsistent settings. The correct ones would be
written as soon as an admin uses useradd -D to modify the defaults.

useradd: use built-in settings by default

---

man/po/de.po
man/usermod.8.xml
src/usermod.c

The man page for usermod says:
> -s, --shell SHELL
> The name of the user's new login shell. ...
This is wrong, usermod just set whatever was given as the new shell. So
if you pass `bash` instead of the path of bash a login afterwards might
not work.
The behaviour in chsh was different, it checked if the argument was on
of the known shells and only then set it[0]. To make it easier for
users, the behaviour should be similar in both programms.
To still allow for a user to run without a real shell (e.g. a daemon
user) and not change the old behaviour too much (while still helping
users) check if the new shell looks like a path and then just set it,
w/o further validation
[0] However root was allowed to set any value, no matter if it was a
known shell or not.

usermod: check if shell is know

---

src/userdel.c

src/userdel.c: clarify the examples for "-f" option

userdel: clarify "-f" usage

---

man/chage.1.xml
man/groupadd.8.xml
man/groupmod.8.xml
man/shadow.5.xml
man/useradd.8.xml
man/usermod.8.xml

man/chage.1.xml: Indicate that -d option with a value of 0 forces the
user to change his password. Besides, set an example on how to use -E
option. Finally, add a general note to clarify that chage only takes
charge of local users and another note to indicate that it doesn't check
inconsistencies between shadow and passwd files.
man/groupadd.8.xml: clarify the exit values meaning.
man/shadow.5.xml: indicate the exact time and timezone for the dates.
Moreover, clarify that when the password expires the user won't be able
to login.
man/useradd.8.xml: specify the SELinux requirements for -m option.
man/usermod.8.xml: specify what happens when the current home directory
doesn't exist if using -d and -m options. Moreover, specify what happens
when the group ownership is changed and the uid's …

Man clarifications

---

configure.ac
etc/login.defs
lib/encrypt.c
lib/getdef.c
libmisc/obscure.c
libmisc/salt.c
src/chgpasswd.c
src/chpasswd.c
src/newusers.c
src/passwd.c

This PR should fix #300
Although I have not done intensive testing, I have been able to set yescrypt-hashed passwords using `chpasswd -c YESCRYPT`.

Add yescrypt support

---

etc/login.defs
lib/getdef.c
src/login.c
src/su.c

Otherwise it's treated like the “require no password” clause while it probably
should be treated like a normal su that can't validate anyway.
A similar change should be done for USE_PAM.

login & su: Treat an empty passwd field as invalid

---

libsubid/Makefile.am

Now subid.h gets installed under /usr/include/shadow/subid.h

Install subid.h

---

etc/login.defs
lib/getdef.c
man/Makefile.am
man/login.defs.5.xml
man/login.defs.d/HMAC_CRYPTO_ALGO.xml

Include the new HMAC_CRYPTO_ALGO key that is needed by pam_timestamp to
select the algorithm that is going to be used to calculate the message
authentication code.
pam_timestamp is currently using an embedded algorithm to calculate the
HMAC message, but the idea is to improve this behaviour by relying on
openssl's implementation. On top of that, the ability to change the
algorithm with a simple configuration change allows to simplify the
process of removing unsecure algorithms.
Reference to pam's pull-request: https://github.com/linux-pam/linux-pam/pull/342
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1947294

login.defs: include HMAC_CRYPTO_ALGO key

---

src/useradd.c

Closes #298
Fix useradd when SUB_UID_COUNT=0 in login.defs.

Fix useradd with SUB_UID_COUNT=0

---

configure.ac
lib/prototypes.h
lib/subordinateio.c
lib/subordinateio.h
libsubid/api.c
libsubid/subid.h
src/list_subid_ranges.c
tests/libsubid/04_nss/libsubid_zzz.c

Closes: 339
struct subordinate_range is pretty closely tied to the existing
subid code and /etc/subuid format, so it includes an owner.  Dropping
that or even renaming it is more painful than I'd first thought.
So introduce a 'struct subid_range' which is only the start and
count, leaving 'struct subordinate_range' as the owner, start and
count.

Don't return owner in list_owner_ranges API call.

---

lib/nss.c
lib/prototypes.h
lib/subordinateio.c
lib/subordinateio.h
src/newusers.c

Closes #331
1. drop 'has_any_range' nss method as it is not useful
2. do not try to create a subid range in newusers when using nss for
subids, since that's not possible.
(cherry picked from commit 88a434adbdcf4a8640793fd58bcd2ba77598349d)

fix newusers when nss provides subids

---

man/newgidmap.1.xml
man/newuidmap.1.xml

Clarify that the subid delegation can only come from one source. This work is based on https://github.com/shadow-maint/shadow/issues/331#issuecomment-841905547
Related: https://github.com/shadow-maint/shadow/issues/331

man: clarify subid delegation

---

src/useradd.c

Currently, supplying a relative path via the --prefix flag to the
useradd command triggers a bug in the creation of home directories. The
code seems to unintentionally prepend a leading "/" to all paths,
quietly transforming a relative prefixed home path into an absolute
path. This can be seen in the following strace logs from running
"useradd --create-home --prefix tmp/root squat":
```
access("tmp/root//home/squat", F_OK)    = -1 ENOENT (No such file or directory)
access("/mp", F_OK)                     = 0
access("/mp/root", F_OK)                = 0
access("/mp/root/home", F_OK)           = 0
access("/mp/root/home/squat", F_OK)     = -1 ENOENT (No such file or directory)
mkdir("/mp/root/home/squat", 000)       = 0
chown("/mp/root/home/squat", 0, 0)      = 0
chmod("/mp/root/home/squat", …
```

fix: create relative home path correctly

---

libmisc/prefix_flag.c
src/newusers.c
src/usermod.c

useradd already was enforcing this, but these were not.

usermod, newusers, prefix: enforce absolute paths for homedir

---

src/usermod.c

Error: RESOURCE_LEAK (CWE-772): [#def31]
shadow-4.8.1/src/usermod.c:813: alloc_fn: Storage is returned from allocation function "__gr_dup".
shadow-4.8.1/src/usermod.c:813: var_assign: Assigning: "ngrp" = storage returned from "__gr_dup(grp)".
shadow-4.8.1/src/usermod.c:892: leaked_storage: Variable "ngrp" going out of scope leaks the storage it points to.
890|   		}
891|   	}
892|-> }
893|
894|   #ifdef SHADOWGRP
Error: RESOURCE_LEAK (CWE-772): [#def32]
shadow-4.8.1/src/usermod.c:933: alloc_fn: Storage is returned from allocation function "__sgr_dup".
shadow-4.8.1/src/usermod.c:933: var_assign: Assigning: "nsgrp" = storage returned from "__sgr_dup(sgrp)".
shadow-4.8.1/src/usermod.c:1031: leaked_storage: Variable "nsgrp" going out of scope leaks the storage it points to.
1029|   		}
1030| …

usermod.c: fix covscan RESOURCE_LEAK

---

man/login.defs.d/PASS_MIN_DAYS.xml

man: use the consistent value 0 to disable PASS_MIN_DAYS restriction

---

libmisc/salt.c

This prefix is the recommended one for new bcrypt hashes for a long time.

bcrypt should use $2b$ as prefix for setting.

---

libmisc/salt.c

Simple bugfix.
I've opened this PR, so it does not get overlooked, in case https://github.com/shadow-maint/shadow/pull/357 doesn't get merged.

YESCRYPT_salt_cost() has long as parameter type.

---

libmisc/failure.c
libmisc/log.c
libmisc/utmp.c

Error: BUFFER_SIZE (CWE-170): [#def6]
shadow-4.8.1/libmisc/failure.c:101: buffer_size_warning: Calling "strncpy" with a maximum size argument of 12 bytes on destination array "fl->fail_line" of size 12 bytes might leave the destination string unterminated.
99|   	}
100|
101|-> 	strncpy (fl->fail_line, tty, sizeof fl->fail_line);
102|   	(void) time (&fl->fail_time);
103|
Error: BUFFER_SIZE (CWE-170): [#def9]
shadow-4.8.1/libmisc/log.c:103: buffer_size_warning: Calling "strncpy" with a maximum size argument of 32 bytes on destination array "newlog.ll_line" of size 32 bytes might leave the destination string unterminated.
101|   	(void) time (&ll_time);
102|   	newlog.ll_time = ll_time;
103|-> 	strncpy (newlog.ll_line, line, sizeof newlog.ll_line);
104|   #if HAVE_LL_HOST
105|   	strncpy …

Fix covscan BUFFER_SIZE

---

libmisc/salt.c

Using the random() function to obtain pseudo-random bytes for generating salt strings is considered to be dangerous.  See [CWE-327](https://cwe.mitre.org/data/definitions/327.html).
We really should use a more reliable source for obtaining pseudo-random bytes like `/dev/urandom`.
Fixes #376.
***
Also add some clarifying comments about how the minimum required buffer length is computed inside of the *_salt_rounds_to_buf() functions.

libmisc/salt.c: Obtain random bytes from /dev/urandom.

---

lib/commonio.c
libmisc/addgrps.c
libmisc/chowntty.c
libmisc/copydir.c
libmisc/idmapping.c
libmisc/list.c
libmisc/myname.c
libmisc/user_busy.c
src/newgrp.c
src/passwd.c

I'm not completely sure about the change I made in `libmisc/addgrps.c`, so it would be nice to have a thorough review of it.
Error: RESOURCE_LEAK (CWE-772): [#def1]
shadow-4.8.1/lib/commonio.c:320: alloc_fn: Storage is returned from allocation function "fopen_set_perms".
shadow-4.8.1/lib/commonio.c:320: var_assign: Assigning: "bkfp" = storage returned from "fopen_set_perms(backup, "w", &sb)".
shadow-4.8.1/lib/commonio.c:329: noescape: Resource "bkfp" is not freed or pointed-to in "putc".
shadow-4.8.1/lib/commonio.c:334: noescape: Resource "bkfp" is not freed or pointed-to in "fflush".
shadow-4.8.1/lib/commonio.c:339: noescape: Resource "bkfp" is not freed or pointed-to in "fileno".
shadow-4.8.1/lib/commonio.c:342: leaked_storage: Variable "bkfp" going out of scope leaks the storage it …

Fix covscan RESOURCE_LEAK

---

configure.ac
lib/defines.h
libmisc/salt.c

Most Linux distributions, including Fedora and RHEL 8, are shipping with libxcrypt >= 4.0.
Since that version of libxcrypt the provided family of crypt_gensalt() functions are able to use automatic entropy drawn from secure system ressources, like arc4random(), getentropy() or getrandom().
Anyways, the settings generated by crypt_gensalt() are always guaranteed to works with the crypt() function.
Using crypt_gesalt() is also needed to make proper use of newer hashing methods, like yescrypt, provided by libxcrypt.
***
See https://github.com/shadow-maint/shadow/pull/303#issuecomment-764847950 for reference.

Use crypt_gensalt(), if available in libcrypt.

---

configure.ac
libmisc/salt.c

In a previous commit we introduced `/dev/urandom` as a source to obtain random bytes from.  This may not be available on all systems, or when operating inside of a chroot.
Almost all systems provide functions to obtain random bytes from secure system ressources.  Thus we should prefer to use these, and fall back to `/dev/urandom`, if there is no such function present, as a last resort.
***
See:  https://github.com/shadow-maint/shadow/pull/377#issuecomment-873534049
@AdamWill: This PR will likely fix your issue.

libmisc/salt.c: Use secure system ressources to obtain random bytes.

---

libmisc/salt.c

fread returns element count, not element size.

fread returns element count, not element size

---

libmisc/list.c

In 9eb191edc4a625bb68e827b18638f5b5816cb30c I included a free() that
frees the members variable, which in turn causes the comma_to_list()
function to return an array of empty elements. The array variable holds
a list of pointers that point to offsets of the members variable. When
the function succeeds freeing members variable causes the elements of
the array variable to point to an empty string.
This is causing several regressions in our internal testing environment.
So, I'm reverting the change.
Signed-off-by: Iker Pedrosa <ipedrosa@redhat.com>

libmisc: don't free members variable

---

libsubid/Makefile.am

libsubid.so links to libmisc.a, which contains several routines referring to
PAM functions.
Fixes #384.

libsubid: link to PAM libraries

---

lib/Makefile.am
libmisc/Makefile.am
libsubid/Makefile.am
src/Makefile.am

There's a better way to do this, and I hope to clean that up,
but this fixes out of tree builds for me right now.
Closes #386

Fix out of tree builds with respect to libsubid includes

---

configure.ac
libsubid/Makefile.am

libsubid's Makefile.am was always setting enable-shared in its LDFLAGS.
Do that only if not building static.
Closes #387
Signed-off-by: Serge Hallyn <shallyn@cisco.com>

Respect --enable-static=no in libsubid

---

src/useradd.c

Since bbf4b79, we stopped shipping /etc/default/useradd, and therefore
install of shadow does not auto-create /etc/default.  So when useradd
tries to save a new default, it needs to create the directory.
Closes #390.

useradd: create /etc/default saving defaults.

---

src/usermod.c

The only way of removing a group from the supplementary list is to use
-G option, and list all groups that the user is a member of except for
the one that wants to be removed. The problem lies when there's a user
that contains both local and remote groups, and the group to be removed
is a local one. As we need to include the remote group with -G option
the command will fail.
This reverts commit 140510de9de4771feb3af1d859c09604043a4c9b. This way,
it would be possible to remove the remote groups from the supplementary
list.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1967641
Resolves: https://github.com/shadow-maint/shadow/issues/338
Signed-off-by: Iker Pedrosa <ipedrosa@redhat.com>

usermod: allow all group types with -G option

---

src/useradd.c

subuid_count won't get used by usr_update(), but since we're passing it
as an argument we have to make sure it's always defined.  So just define
it as pre-set to 0.
Closes #402

useradd.c: Fix undeclared subuid_count when not using subids

---

man/po/Makefile.in

xml2po is deprecated.  We've previously replaced xml2po with
itstool in man/generate_translations.mak, but there was still
an instance of it that only is exercised for 'make dist'.
Update that one.  Now 'make dist' succeeds on a ubuntu focal
or newer host where xml2po is not available.

man/po/Makefile.in: switch from xml2po to itstool

---

libmisc/salt.c

If SHA_CRYPT_MIN_ROUNDS and SHA_CRYPT_MAX_ROUNDS are both unspecified,
use SHA_ROUNDS_DEFAULT.
Previously, the code fell through, calling shadow_random(-1, -1). This
ultimately set rounds = (unsigned long) -1, which ends up being a very
large number! This then got capped to SHA_ROUNDS_MAX later in the
function.
The new behavior matches BCRYPT_get_salt_rounds().
Bug: https://bugs.gentoo.org/808195
Fixes: https://github.com/shadow-maint/shadow/issues/393

libmisc: fix default value in SHA_get_salt_rounds()

---

src/gpasswd.c

`sgent` is only initialized in `get_group()` if `is_shadowgrp` is true.
So we should also only attempt to free it if this is actually the case.
Can otherwise lead to:
```
free() double free detected in tcache 2 (gpasswd)
```

Only free sgent if it was initialized

---

src/chfn.c
src/chgpasswd.c
src/expiry.c
src/groupdel.c
src/groupmems.c
src/grpck.c
src/login_nopam.c
src/logoutd.c
src/newgrp.c
src/newuidmap.c
src/newusers.c
src/passwd.c
src/suauth.c
src/sulogin.c

Signed-off-by: Luís Ferreira <contact@lsferreira.net>
---
This patch was generated using `sed -i 's/[ \t]*$//'`. I would suggest encouraging users to set up a pre-commit hook to fix these trivial code style issues.
@hallyn If you want, you can set up a pre-commit CI configuration to help you out on this and other trivial changes. Check https://pre-commit.ci/ for reference.

treewide: remove trailing whitespaces

---

libmisc/hushed.c

If a line in hushlogins file, e.g. /etc/hushlogins, starts with
'\0', then current code performs an out of boundary write.
If the line lacks a newline at the end, then another character is
overridden.
With strcspn both cases are solved.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>

Handle malformed lines in hushlogins file.

---

lib/tcbfuncs.c

During shadowtcb_move() the directory is temporarily changed to be
owned by root:root with permissions 0700.  After the change is done,
the ownership and permissions were supposed to be restored.  The
call for chown() was there, but the chmod() call was missing.  This
resulted in the broken TCB functionality.  The added chmod() fixes
the issue.

Add missing chmod() for shadowtcb_move()

---

src/pwck.c

As `shadow_logfd` variable is not set at the beginning of the program if
something fails and fprintf() is called a segmentation fault happens.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2021339

pwck: fix segfault when calling fprintf()

---

src/useradd.c

Change SELinux labels for files copied from the skeleton directory to
the home directory.
This could cause gnome's graphical user adding to fail without copying
the full skeleton files.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2022658

useradd: change SELinux labels for home files

---

src/newgrp.c

Fix segmentation fault in newgrp when xgetspnam() returns a NULL value
that is immediately freed.
The error was committed in
https://github.com/shadow-maint/shadow/commit/e65cc6aebcb4132fa413f00a905216a5b35b3d57
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2019553

newgrp: fix segmentation fault

---

README
man/Makefile.am
man/getsubids.1.xml
src/.gitignore
src/Makefile.am
src/getsubids.c
tests/libsubid/01_list_ranges/list_ranges.test

Rename list_subid_ranges to getsubids to provide a system binary to
check the sub*ids of a user. The intention is to provide this binary
with any distribution that includes the subid feature, so that system
administrators can check the subid ranges of a given user.
Moreover, include a new configuration option "--with-subids-helpers" to
select whether the tool will be compiled as a non-installable binary or
a system binary.
Finally, add a man page to explain the behaviour of getsubids.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1980780

getsubids: system binary for user's sub*ids

---

libmisc/prefix_flag.c

When using groupdel with a prefix, groupdel will attempt to read a
passwd file to look for any user in the group. When the file does not
exist it cores with segmentation fault.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1986111

groupdel: fix SIGSEGV when passwd does not exist

---

src/vipw.c

Always set SIGCHLD handler to default, even if the caller of vipw has
set SIGCHLD to ignore. If SIGCHLD is ignored no zombie processes would
be created, which in turn could mean that kill is called with an already
recycled pid.
1. Compile nochld:
--
#include <signal.h>
#include <unistd.h>
int main(void) {
char *argv[] = { "vipw", NULL };
signal(SIGCHLD, SIG_IGN);
execvp("vipw", argv);
return 1;
}
--
2. Run nochld
3. Suspend child vi, which suspends vipw too:
`kill -STOP childpid`
4. Kill vi:
`kill -9 childpid`
5. You can see with ps that childpid is no zombie but disappeared
6. Bring vipw back into foreground
`fg`
The kill call sends SIGCONT to "childpid" which in turn could have been
already recycled for another process.
This is definitely not a vulnerability. It would …

Improve child error handling

---

src/useradd.c

In absence of /etc/passwd, eg when bootstrapping a chroot, resolving
uid 0 to a name may not work. Therefore just assume "root".

useradd: assume uid 0 == root as fallback

---

src/useradd.c

The useradd program should be consistent with userdel and usermod and use the
MAIL_SPOOL_DIR variable as the default spool, if it is defined. Otherwise,
don't create a new mailbox, because it won't be cleaned up by userdel when run
with the -r flag.

Removed hard-coded default mail spool in useradd

---

src/login.c
src/su.c

**Caveat: This is for discussion, mostly. Still need to have a policy for bounded capabilities.**
POSIX capabilities have been supported by Linux for quite some time now. Most distributions allow to set inheritable capabilities:
Activate `pam_cap.so` (comes with PAM enabled **libcap**)  in your PAM config...
```
auth		required	pam_env.so
auth		optional	pam_cap.so
auth		requisite	pam_faillock.so preauth
[...]
```
...add capabilities to users in `/etc/security/capability.conf`...
```
[...]
cap_net_raw      joeuser
[...]
```
...and enable that capability on an executable:
```
[βελλεροφων ~]# setcap cap_net_raw=ei /usr/bin/traceroute
[βελλεροφων ~]# getcap /usr/bin/traceroute
/usr/bin/traceroute cap_net_raw=ei
[βελλεροφων ~]#
```
Now **joeuser** can perform traceroutes that require raw …

Add support for ambient capabilities

---

AUTHORS.md
man/usermod.8.xml
src/usermod.c

Adding a new switch -rG, which provides a similar feature set to -aG, allowing a person to list exactly what groups to remove a user from.
As we can see user tester is part of test[1..4]
[a@localhost src]$ tail /etc/group ; sudo tail /etc/gshadow
tester1:x:1003:
test1:x:1004:tester1
test2:x:1005:tester1
test3:x:1006:tester1
test4:x:1007:tester1
tester1:!::
test1:!::tester1
test2:!::tester1
test3:!::tester1
test4:!::tester1
Running with -rG, we can now see that we have removed user tester1 from the named groups, while leaving the unnamed groups untouched
[a@localhost src]$ sudo ./usermod -rG test1,test2 tester1
[a@localhost src]$ tail /etc/group ; sudo tail /etc/gshadow
tester1:x:1003:
test1:x:1004:
test2:x:1005:
test3:x:1006:tester1
test4:x:1007:tester1
tester1:!::
test1:!::
test2:!:: …

Adding new switch -rG to usermod

---

src/usermod.c

That special case is already handled by the called function: strtoday()
so we can simplify the calling code.
Link: <https://github.com/shadow-maint/shadow/issues/454>
Signed-off-by: Alejandro Colomar <alx.manpages@gmail.com>
--
**NOTE**: I didn't test the change, since I couldn't find instructions on how to build it in the README, and there's no `Makefile`.

usermod: Remove special case for ""

---

configure.ac
libsubid/Makefile.am

We were overriding this when --enable-shared was passed. We can actually
just dump the conditional logic as libtool will do the right thing for
us here anyway.
Without this patch, libsubid is installed as .0.
Signed-off-by: Sam James <sam@gentoo.org>

libsubid: fix defining SONAME version

---

lib/commonio.c
lib/nscd.c
lib/selinux.c
lib/shadowlog.c
lib/shadowlog_internal.h
lib/spawn.c
lib/sssd.c
lib/tcbfuncs.c

After #471, the build fails with duplicate symbol errors with `-fno-common`:
```
/gar/bin/ld: ../lib/.libs/libshadow.a(libshadow_la-encrypt.o):/src/sys/shadow/work/6761cf2d7e9defeed7f915c668a87b84bac2c9c3/lib/shadowlog_internal.h:2: multiple definition of `shadow_logfd'; ../lib/.libs/libshadow.a(libshadow_la-commonio.o):/src/sys/shadow/work/6761cf2d7e9defeed7f915c668a87b84bac2c9c3/lib/shadowlog_internal.h:2: first defined here
/gar/bin/ld: ../lib/.libs/libshadow.a(libshadow_la-encrypt.o):/src/sys/shadow/work/6761cf2d7e9defeed7f915c668a87b84bac2c9c3/lib/shadowlog_internal.h:1: multiple definition of `Prog'; ../lib/.libs/libshadow.a(libshadow_la-commonio.o):/src/sys/shadow/work/6761cf2d7e9defeed7f915c668a87b84bac2c9c3/lib/shadowlog_internal.h:1: first defined here
```
(etc.)
`-fcommon` is …

lib: rename Prog to shadow_progname, with only one definition

---

lib/prototypes.h
libmisc/Makefile.am
libmisc/date_to_str.c
po/POTFILES.in
src/chage.c
src/passwd.c
src/usermod.c

PARAMETERS:
According to the C2x charter, I reordered the parameters 'size'
and 'buf' from previously existing date_to_str() definitions.
[C2x charter](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2086.htm):
> 15. Application Programming Interfaces (APIs) should be
> self-documenting when possible.  In particular, the order of
> parameters in function declarations should be arranged such that
> the size of an array appears before the array.  The purpose is to
> allow Variable-Length Array (VLA) notation to be used.  This not
> only makes the code's purpose clearer to human readers, but also
> makes static analysis easier.  Any new APIs added to the Standard
> should take this into consideration.
I used 'long' for the date parameter, as some uses of the function
need to pass a negative …

Have a single definition of date_to_str()

---

lib/shadowlog.c
libsubid/api.c

Set the program name in `subid_init` too, as [suggested](https://github.com/shadow-maint/shadow/pull/472#issuecomment-1001205406) in #472.
The existing code here made me think that there should be a default value in lib if the user doesn't set it, so do that as well.

Default value for progname/logfd, and set progname in subid_init too

---

configure.ac
libmisc/failure.c
src/chage.c
src/faillog.c
src/lastlog.c
src/login.c

strftime(3) has been in standard C since C89.  It is also in
POSIX.1-2001, and in SVr4 (see [`strftime(3)`](https://www.man7.org/linux/man-pages/man3/strftime.3.html) and [`strftime(3p)`](https://www.man7.org/linux/man-pages/man3/strftime.3p.html)).
We can assume that this function is always available.
Signed-off-by: Alejandro Colomar <alx.manpages@gmail.com>

Remove HAVE_STRFTIME ifdefs

---

configure.ac
lib/defines.h
libmisc/getdate.y

memcpy(3) has been in standard C since C89.  It is also in
POSIX.1-2001, in SVr4, and in 4.3BSD (see [`memcpy(3)`](https://man7.org/linux/man-pages/man3/memcpy.3.html) and [`memcpy(3p)`](https://man7.org/linux/man-pages/man3/memcpy.3p.html)).
We can assume that this function is always available.
Signed-off-by: Alejandro Colomar <alx.manpages@gmail.com>

Remove HAVE_MEMCPY and HAVE_MEMSET ifdefs

---

configure.ac
src/groups.c
src/id.c

getgroups(2) has been in POSIX since POSIX.1-2001.  It is also in
in SVr4 and in 4.3BSD (see [`getgroups(2)`](https://man7.org/linux/man-pages/man2/getgroups.2.html) and [`getgroups(3p)`](https://www.man7.org/linux/man-pages/man3/getgroups.3p.html)).
We can assume that this function is always available.
Signed-off-by: Alejandro Colomar <alx.manpages@gmail.com>

Remove HAVE_GETGROUPS ifdefs

---

src/useradd.c

There are two problems:
1. `dirname` is not declared properly, so the compiler assumes it to return `int`.
2. `dirname` does not support called with a static string (see `man 3 dirname`).
Both may cause a segfault, as (1) leads to an undefined behavior and the man page explicitly says (2) can cause a segfault.

fix segfault running useradd -D

---

lib/Makefile.am

Will need to regenerate dist tarball after this (would recommend doing a new release to avoid confusion, e.g. 4.11.1.).
Seems to work for me after running `make dist` then trying to `./configure && make` from that new tarball.
Fixes: #485
Signed-off-by: Sam James <sam@gentoo.org>

build: include lib/shadowlog_internal.h in dist tarballs

---

configure.ac
lib/defines.h

Compilers are allowed to and do optimize memset(3) calls away for
pointers not accessed in the future. Since the memzero wrappers purpose
is exactly to unconditionally override memory (e.g. for stored
passwords) do not implement via regular memset(3), but via either
memset_s(3), explicit_bzero(3) or a hand written implementation using
volatile pointers.
See https://wiki.sei.cmu.edu/confluence/display/c/MSC06-C.+Beware+of+compiler+optimizations

Ensure memory cleaning

---

configure.ac
lib/defines.h
libmisc/getdate.y

Remove STDC_HEADERS, since C89 is nowadays available everywhere (or at least everywhere we can possibly care).
STDC_HEADERS removal allows to simplify other things.  Propagate those changes.

Assume C89 is available

---

lib/nss.c

If /etc/nsswitch.conf doesn't exist podman crashes because shadow_logfd
is NULL. In order to avoid that load the log file descriptor with the
log_get_logfd() helper function.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2038811

nss: get shadow_logfd with log_get_logfd()

---

src/useradd.c

useradd warns that a system user ID less than SYS_UID_MIN is outside the
expected range, even though that ID has been specifically selected with
the "-u" option.
In my opinion all the user ID's below SYS_UID_MAX are for the system,
thus I change the condition to take that into account. Moreover, I also
modify the check for SYS_UID_MAX, so that it's always less than UID_MIN.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2004911

useradd: modify check ID range for system users

---

libsubid/subid.h.in

C++ requires extern "C" linkage specification to call functions from a C
library. Enclose the function definitions in subid.h in an extern "C"
block if compiling in C++ mode to achieve this.
Signed-off-by: Alois Wohlschlager <alois1@gmx-topmail.de>

Make libsubid more easily usable from C++

---

etc/pam.d/login
etc/pam.d/su

If we use **--without-selinux** su say Unknown module. pam_selinux must be optional.

fix noselinux su config bug

---

man/usermod.8.xml

This was introduced in 2f30d235c2b6ba565c50d492d7be33380f73164a; it breaks the build if manpages are enabled.

Fix syntax error in usermod man source

---

src/logoutd.c

ut_line is declared as a nonstring in bits/utmp.h. It might not be NUL
terminated. Limit how much it copies to the size of the array.

Change to strncat

---

AUTHORS.md

The markdown output for the maintainers, authors and contributors list
was wrapped in a single line and it was difficult to read. I've created
an unordered list to get a better output. On top of that I've also added
myself as a maintainer.

AUTHORS: improve markdown output

---

libmisc/xgetXXbyYY.c

The reentrant functions getgrgid_r, getgrnam_r, getpwnam_r, etc. all return an error code instead of setting errno. Adapt the error check accordingly.
See the man page of e.g. getpwnam_r for reference:
> On success, getpwnam_r() and getpwuid_r() return zero, and set *result to pwd.
> If no matching password record was found, these functions return 0 and store NULL in *result.
> **In case of error, an error number is returned**, and NULL is stored in *result.

libmisc/xgetXXbyYY.c: Handle ERANGE error correctly

---

acinclude.m4
configure.ac

Replace
AC_HELP_STRING by AS_HELP_STRING,
AC_GNU_SOURCE by AC_USE_SYSTEM_EXTENSIONS,
AC_TRY_COMPILE by AC_COMPILE_IFELSE and
AM_PROG_LIBTOOL by LT_INIT.
See https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html

configure: replace obsolete autoconf macros

---

tests/chsh/01/run
tests/convtools/01/run
tests/su/10_su_sulog_success/su.test
tests/su/11_su_sulog_failure/su.test

"egrep" is an obsolete alias for grep -E and newer greps will warn on usage
of egrep, so let's just swap it out.
Signed-off-by: Sam James <sam@gentoo.org>

tests: replace egrep -> grep -E

---

.github/actions/install-dependencies/action.yml
.github/workflows/static-code-analysis.yml

Create a Github workflow to install the dependencies to build shadow-utils. Enable the CodeQL analyzer, which first needs to build the project in order to analyze it.

CI: enable CodeQL analyzer

---

.github/workflows/static-code-analysis.yml

CodeQL Action v1 is being deprecated and v2 needs to be used instead.
Reference: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

CI: update actions version

---

man/useradd.8.xml

With -r option, `useradd` doesn't update /etc/sub{u,g}id can be a pitfall.
I'm looking into https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/packaging/root/usr/share/gitlab-runner/post-install#L25 to use podman as a runner of gitlab.
The podman runs a container with a non-admin account called `gitlab-runner`.
However, the running failed because the way to add `gitlab-runner` user done in the `post-install` script was wrong; it was created with `useradd --system`; entries for `gitlab-runner` were not added to /etc/subuid and /etc/subgid.
Adding a note to useradd(8) I proposed here may make the pitfall small a bit.

man (useradd): add a note about -r option and /etc/subuid and subgid

---

lib/subordinateio.c

IDs already populate /etc/subuid and /etc/subgid files so it's necessary
not only to check for the owner name but also for the owner ID of a
given range.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2093311

subordinateio: also compare the owner ID

---

.builds/ubuntu-jammy.yml

Since Ubuntu 21.10 has gone out of support it no longer works for
testing with CI. Instead use 22.04 which is still supported.

Fix CI by testing Ubuntu 22.04 instead of 21.10.

---

man/useradd.8.xml
src/useradd.c
src/usermod.c

Since code gives this error if username or group name is already
used the documentation should reflect that.
Found by accident when testing useradd when the username's corresponding group already existed and got 9 return code.

Fix E_NAME_IN_USE documentation.

---

configure.ac
lib/commonio.c
lib/defines.h
libmisc/chowndir.c
libmisc/copydir.c
libmisc/remove_tree.c

Address CVE-2013-4235 (#317) by pinning the directories operating in and using the *at() version of file related functions.
Requires openat(2), fstatat(2), mkdirat(2), symlinkat(2), linkat(2), mknodat(2), unlinkat(2), fchmodat(2), fchownat(2) and utimensat(2) specified in POSIX.1-2008.
*Should* be supported by glibc 2.6 and Linux 2.6.22.

Address CVE-2013-4235

---

man/useradd.8.xml

As discussed on irc and according to bbf4b79

useradd.8.xml: fix default group id from 100 to 1000

---

libsubid/api.c
libsubid/subid.h.in

As rbalint points out, this was an exported fn.  It also is
the only way for a libsubid user to do what it does, so let's
not drop it.
This reverts commit 477c8e6f42df1e17e45584e74988eb46a11e6caa.

Revert "Drop unused function subid_init()"

---

src/useradd.c

useradd does not create the files if they don't exist, but if they exist
it will try to reset data even if the data did not exist before
resulting in a lot of zeros ending up in tarballs.
An example is basically every chroot containing a Debian (or derivative) system which is packed into a tarball later on e.g. for build servers. The chroot will have an `_apt` system user created in the bootstrap which fills the {last,fail}log files with zeros as they tend to be already created with the right permissions.
Of course, the files aren't large and zeros compress rather well (if you compress your tarballs), but what doesn't exist takes up even less space.
Rational for "ignoring" `LOG_INIT`: The documentation for `--no-log-init` says that it "do[es] not add the user to the lastlog and faillog …

useradd: Do not reset non-existent data in {last,fail}log

---

libmisc/chkname.c
man/groupadd.8.xml
man/useradd.8.xml

The groupadd from shadow does not allow upper case group names, the
same is true for the upstream shadow. But distributions like
Debian/Ubuntu/CentOS has their own way to cope with this problem,
this patch is picked up from CentOS release 7.0 to relax the usernames
restrictions to allow the upper case group names, and the relaxation is
POSIX compliant because POSIX indicate that usernames are composed of
characters from the portable filename character set [A-Za-z0-9._-].
Note from Alexander: Yocto project has been carrying this patch for several years, we're not aware of any reasons why it shouldn't be acceptable, but if such reasons exist, we would like to document or link to them.

shadow: use relaxed usernames

---

lib/semanage.c

useradd: check MLS enablement before setting serange
Resolves: https://github.com/shadow-maint/shadow/issues/552
This fix wraps the calls to set the s0 MLS range in an `if (semanage_mls_enabled(handle)) { }` block to ask the real libsemanage to verify MLS is actually in use.
- now MLS detection is dynamic and optional, not every SELinux user uses MLS

useradd: check MLS enablement before setting serange

---

libmisc/copydir.c

This pull request fixes regressions in copy_tree:
- `./configure --without-acl` leads to a usermod which does not work due to invalid chmod call.
- FIFOs in user home directories prevent `usermod -md /new_home user` from working.
Please see commit messages for more details.

copy_tree: Fix regressions

---

.github/workflows/static-code-analysis.yml

Differential ShellCheck is a GitHub action that performs **differential ShellCheck scans** on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get **reports only about newly added defects**. 
Since this repository has many shell scripts, I think you might find some value in having a shell linter. Differential ShellCheck action is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always …

ci(lint): add shell linter - Differential ShellCheck

---

lib/commonio.c

This tweaks the database locking logic so that failures in the
link-checking paths are more detailed.
The rationale for this is that I've experienced a non-deterministic
bug which seems to be coming from this logic, and I'd like to get
more details about the actual failing condition.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1250

lib/commonio: make lock failures more detailed

---

lib/commonio.c
lib/getdef.c
lib/groupio.c
lib/prototypes.h
lib/sgetgrent.c
lib/tcbfuncs.c
libmisc/copydir.c
libmisc/xmalloc.c
src/gpasswd.c
src/login.c
src/newusers.c

```
free(3) accepts NULL, since the oldest ISO C.  I guess the paranoid code was taking
care of prehistoric implementations of free(3).  I've never known of an implementation
that doesn't conform to this, so let's simplify this.
Remove xfree(3), which was effectively an equivalent of free(3).
```
I found this while merging `xmalloc()`+`str*cpy()` into `xstrdup()`.

Don't test for NULL before calling free(3)

---

lib/defines.h
libmisc/utmp.c

```
glibc, musl, FreeBSD, and OpenBSD define the MAX() and MIN() macros in
<sys/param.h> with the same definition that we use.  Let's not
redefine it here and use the system one, as it's effectively the
same as we define (modulo whitespace).
See:
shadow (previously):
alx@asus5775:~/src/shadow/shadow$ grepc -ktm MAX
./lib/defines.h:318:#define MAX(x,y) (((x) > (y)) ? (x) : (y))
glibc:
alx@asus5775:~/src/gnu/glibc$ grepc -ktm -x 'sys/param.h$' MAX
./misc/sys/param.h:103:#define MAX(a,b) (((a)>(b))?(a):(b))
musl:
alx@asus5775:~/src/musl/musl$ grepc -ktm -x 'sys/param.h$' MAX
./include/sys/param.h:19:#define MAX(a,b) (((a)>(b))?(a):(b))
OpenBSD:
alx@asus5775:~/src/bsd/openbsd/src$ grepc -ktm -x 'sys/param.h$' MAX
./sys/sys/param.h:193:#define	MAX(a,b) (((a)>(b))?(a):(b))
FreeBSD: …
```

Use libc MAX() and MIN()

---

src/chage.c

Introduced by c6c8130db4319613a91dd07bbb845f6c33c5f79f .
After removing snprintf, the format string should get unescaped once.
Fixes #564
Reporter and patch author: DerMouse (github.com/DerMouse)

chage: Fix regression in print_date

---

libmisc/find_new_gid.c
libmisc/find_new_uid.c

The minimum id allocation for system accounts shouldn't be 0 as this is reserved for root.

libmisc: minimum id check for system accounts

---

src/usermod.c

fix `usermod -rG x y` while user `y` is not in group `x` will cause user `y` add into group `x`
I'll explain more in details later in an issue thread. I'm not familiar with the code. I'm not sure if my changes consider all edge cases. But it do fix the issue.

fix `usermod -rG x y` while user `y` is not in group `x` will cause user `y` add into group `x`

---

lib/defines.h
lib/pwio.c
lib/sgetpwent.c
lib/sgetspent.c
lib/shadowio.c

Moreover, include checks to prevent writing entries longer than the length limit.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1422497

Raise limit for passwd and shadow entry length

---

src/useradd.c

Running `useradd --prefix ...` aborts on openSUSE due to their hardening flags with a `buffer overflow detected` message.  It looks like this buffer is one byte short.

useradd: Fix buffer overflow when using a prefix

---

lib/nss.c

Maybe we should have a debug mode where it's still printed, but we don't, so let's be quieter.
Closes #557

Don't warn when failed to open /etc/nsswitch.conf

---

src/useradd.c

According to useradd man page: If /etc/subuid exists, the commands useradd and newusers (**unless the user already have subordinate user IDs**) allocate SUB_UID_COUNT unused user IDs from the range SUB_UID_MIN to SUB_UID_MAX for each new user.
Thus, I've added a condition to check if a user already has a subid/subgid range before assigning one.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2012929

useradd: check if subid range exists for user

---

configure.ac

The missing #include <gshadow.h> causes the configure check to fail spuriously, resulting in HAVE_SHADOWGRP not being defined even on systems that actually have sgetsgent (such as current glibc).

Fix HAVE_SHADOWGRP configure check

---

configure.ac
lib/defines.h
lib/prototypes.h
libmisc/Makefile.am
libmisc/agetpass.c
src/gpasswd.c
src/newgrp.c
src/passwd.c
src/sulogin.c

```
There are several issues with getpass(3).
Many implementations of it share the same issues that the infamous
gets(3).  In glibc it's not so terrible, since it's a wrapper
around getline(3).  But it still has an important bug:
If the password is long enough, getline(3) will realloc(3) memory,
and prefixes of the password will be laying around in some
deallocated memory.
See the getpass(3) manual page for more details, and especially
the commit that marked it as deprecated, which links to a long
discussion in the linux-man@ mailing list.
So, readpassphrase(3bsd) is preferrable, which is provided by
libbsd on GNU systems.  However, using readpassphrase(3) directly
is a bit verbose, so we can write our own wrapper with a simpler
interface similar to that of getpass(3).
One of the benefits …
```

agetpass() to replace getpass(3)

---

configure.ac
lib/defines.h

<https://github.com/shadow-maint/shadow/issues/600>

Raise the bar to ISO C99 (drop support for C89)

---

configure.ac
lib/commonio.c
lib/defines.h
libmisc/limits.c
libmisc/loginprompt.c
libmisc/pwd_init.c
libmisc/rlogin.c
libmisc/salt.c
libmisc/ulimit.c
libmisc/xgetgrgid.c
libmisc/xgetgrnam.c
libmisc/xgetpwnam.c
libmisc/xgetpwuid.c
src/expiry.c
src/gpasswd.c
src/login_nopam.c
src/sulogin.c

Previously, we required ISO C99.  Let's go a bit further, and require POSIX.1-2001, which allows removing a lot of preprocessor and build system code, and even some alternative definitions.

Raise the bar to POSIX.1-2001

---

src/useradd.c

When useradd sends its ADD_USER event, it is filling in the id field. This is not yet written to disk. When auditd sees the event and the log format is enriched, auditd tries to lookup the user name but it does not exist. This causes the event to never be resolvable since ausearch relies on the lookup information attached by auditd.
The fix is to not send the id information for any event until after close_files() is called. Just the acct field is all that is
Patch by Steve Grubb (afaik).
Reported at https://bugzilla.redhat.com/show_bug.cgi?id=1713432

Fix useradd audit event logging of ID field

---

libmisc/copydir.c
src/useradd.c

This patch is used by openSUSE to make useradd look for skeleton files in /usr/etc/skel additionally to /etc/skel in accordance with
https://uapi-group.org/specifications/specs/base_directory_specification/

Add support for skeleton files from /usr/etc/skel

---

src/groupmod.c

This is a preparation patch before some more fixes.  I found some problems in this file, which are not yet addressed by these fixes.  This is only cleaning up so that the more important fixes are more readable.
@hallyn  @ikerexxe  I need to add functions that are usable in the entire project; we've seen that some parts of the project don't use libmisc, right?  In which library should I put them?  Or can we make the entire project depend on libmisc?

Groupmod fixes

---

lib/gshadow.c
lib/lockpw.c
lib/nscd.c
lib/pwauth.c
lib/selinux.c
lib/semanage.c
lib/sgetspent.c
lib/sgroupio.c
lib/shadow.c
lib/sssd.c
lib/subordinateio.c
lib/utent.c
libmisc/addgrps.c
libmisc/audit_help.c
libmisc/find_new_sub_gids.c
libmisc/find_new_sub_uids.c
libmisc/limits.c
libmisc/obscure.c
libmisc/pam_pass.c
libmisc/pam_pass_non_interactive.c
libmisc/pwd2spwd.c
libmisc/pwdcheck.c
libmisc/tz.c
src/login_nopam.c

It is Undefined Behavior to declare errno (see NOTES in its manual page). Instead of using the errno dummy declaration, use one that doesn't need a comment.

Don't redefine errno(3)

---

configure.ac
libmisc/copydir.c

However, don't stop using functions that were once required by POSIX.1-2001 that were good functions, and which have been removed by POSIX.1-2008 without good reasons.  For example, continue using `bzero(3)`.  However, there may be functions that were removed with a good reason.  We should stop using those.

Raise the bar to POSIX.1-2008

---

lib/fields.c
lib/gshadow.c
libmisc/console.c
libmisc/date_to_str.c
libmisc/utmp.c
src/su.c

-  Since strncpy(3) is not designed to write strings, but rather
(null-padded) character sequences (a.k.a. unterminated strings), we
had to manually append a '\0'.  strlcpy(3) creates strings, so they
are always terminated.  This removes dependencies between lines, and
also removes chances of accidents.
-  Repurposing strncpy(3) to create strings requires calculating the
location of the terminating null byte, which involves a '-1'
calculation.  This is a source of off-by-one bugs.  The new code has
no '-1' calculations, so there's almost-zero chance of these bugs.
-  strlcpy(3) doesn't padd with null bytes.  Padding is relevant when
writing fixed-width buffers to binary files, or when sending them
to other processes or through the network.  This is not the case,
so padding is effectively …

Use strlcpy(3) instead of its pattern

---

src/chfn.c

When chfn calls change_field on some fields, if it is not allowed to print some fields, it instead prints them out - except it always prints the fullname.  Fix the field being printed in that case.

chfn: fix the change_field results printed

---

lib/commonio.c
lib/commonio.h
man/groupmems.8.xml

Systems can suffer power interruptions whilst .lock files are in /etc, preventing scripts and other automation tools from updating shadow's files which persist across boots.
This commit replaces that mechanism with file locking to avoid problems of power interruption/crashing.

changing lock mechanism

---

lib/prototypes.h
libmisc/Makefile.am
libmisc/inet_sockaddr2str.c
src/login_nopam.c

gethostbyname(3) was removed in POSIX.1-2008.  It has been obsoleted,
and replaced by getaddrinfo(3), which is superior in several ways:
-  gethostbyname(3) is not reentrant.  There's a GNU extension,
gethostbyname_r(3) which is reentrant, but it's not likely to be
standardized for the following reason.  And we don't care too much
about this point either.
-  gethostbyname(3) only supports IPv4, but getaddrinfo(3) supports both
IPv4 and IPv6 (and may support other address families in the future).
We don't care about reentrancy, so for keeping the code simple (i.e.,
not touch call site to add code to free(3) an allocated buffer), I added
a static buffer for inet_ntop(3).  We could address that in the future,
but I don't think it's worth it.
BTW, we also replace inet_ntoa(3) by inet_ntop(3), …

Use getaddrinfo(3) instead of gethostbyname(3)

---

lib/nss.c

Commit 90424e7c ("Don't warn when failed to open /etc/nsswitch.conf") removed the logging for failing to read /etc/nsswitch.conf to reduce the noise in the case the file does not exists (e.g. musl based systems).
Reintroduce a warning if /etc/nsswitch.conf exists but we failed to read it (e.g. permission denied).
Improves: 90424e7c ("Don't warn when failed to open /etc/nsswitch.conf")
/cc @agherzan

Warn if failed to read existing /etc/nsswitch.conf

---

src/login.c

Login timed out message prints only first few bytes when write is immediately followed by exit. Calling exit from new handler provides enough time to display full message.

shadow: Fix can not print full login timeout message

---

libmisc/salt.c

```
arc4random(3) without kernel support is unsafe, as it can't know when to
drop the buffer.  Since we depend on libbsd since recently, we have
arc4random(3) functions always available, and thus, this code would have
always called arc4random_buf(3bsd), which is unsafe.  Put it after some
better alternatives, at least until in a decade or so all systems have a
recent enough glibc.
glibc implements arc4random(3) safely, since it's just a wrapper around
getrandom(2).
Link: <https://inbox.sourceware.org/libc-alpha/20220722122137.3270666-1-adhemerval.zanella@linaro.org/>
Link: <https://inbox.sourceware.org/libc-alpha/Ytwg8YEJn+76h5g9@zx2c4.com/>
Cc: "Jason A. Donenfeld" <Jason@zx2c4.com>
Cc: Cristian Rodríguez <crrodriguez@opensuse.org>
Cc: Adhemerval Zanella <adhemerval.zanella@linaro.org> …
```

Prefer getrandom(3)/getentropy(3) over arc4random(3bsd)

---

configure.ac
lib/defines.h

* Replace flawed memset_s usage
memset_s() has a different signature than memset(3) or explicit_bzero(), thus the current code would not compile.
Also memset_s() implementations are quite rare.
Use the C23 standardized version memset_explicit(3).
Fixes: https://github.com/shadow-maint/shadow/commit/7a799ebb2c304010c1aad16490e7354c7e7659a2 ("Ensure memory cleaning")
* Modernize manual memzero implementation
Instead of using volatile pointers to prevent the compiler from optimizing the call away, use a memory barrier.
This requires support for embedded assembly, which should be fine after the recent requirement bumps.

memzero updates

---

lib/Makefile.am
lib/pam_defs.h
libmisc/copydir.c
libmisc/env.c
libmisc/gettime.c
libmisc/idmapping.c
src/Makefile.am
src/login.c
src/newgidmap.c
src/newgrp.c
src/newuidmap.c
src/sulogin.c

copydir.c: In function 'copy_dir':
copydir.c:517:32: warning: passing argument 1 of 'copy_tree' from incompatible pointer type [-Wincompatible-pointer-types]
517 |             return (copy_tree (src, dst, false, reset_selinux,
|                                ^~~
|                                |
|                                const struct path_info *
In file included from copydir.c:20:
../lib/prototypes.h:108:35: note: expected 'const char *' but argument is of type 'const struct path_info *'
108 | extern int copy_tree (const char *src_root, const char *dst_root,
|                       ~~~~~~~~~~~~^~~~~~~~
copydir.c:517:37: warning: passing argument 2 of 'copy_tree' from incompatible pointer type [-Wincompatible-pointer-types]
517 |             return (copy_tree (src, dst, false, …

copydir: fix impl usage

---

lib/bit.h
libmisc/Makefile.am
libmisc/bit.c
libmisc/csrand.c

```
__int128, which is needed for optimizing that part of the range, is not
always available.  We need the unoptimized version for portability
reasons.
```
Closes: <https://github.com/shadow-maint/shadow/issues/634>
Fixes: https://github.com/alejandro-colomar/shadow/commit/1a0e13f94edc08d4c773a00d710d56fac966e818 ("Optimize csrand_uniform()")
Reported-by: Adam Sampson <ats@offog.org>
Cc: Iker Pedrosa <ipedrosa@redhat.com>

Unoptimize the higher part of the domain of csrand_uniform()

---

lib/port.c
libmisc/console.c
libmisc/tz.c
src/login_nopam.c
src/suauth.c

If the file referenced by ENV_TZ has a zero length string, then an out of boundary write occurs. Also the result can be wrong because it is assumed that the file will always end with a newline.
Only override a newline character with '\0' to avoid these cases.
This cannot be considered to be security relevant because login.defs and its contained references to system files should be trusted to begin with.
1. Compile shadow's su with address sanitizer and --without-libpam
2. Setup your /etc/login.defs to contain ENV_TZ=/etc/tzname
3. Prepare /etc/tzname to contain a '\0' byte at the beginning
`python -c "print('\x00')" > /etc/tzname`
4. Use su
`su -l`
You can see the following output:
`tz.c:45:8: runtime error: index 18446744073709551615 out of bounds for type 'char …

Correctly handle illegal system file in tz

---

libmisc/agetpass.c
libmisc/obscure.c

It originated in OpenBSD, and is available in libbsd.

Use freezero(3) where suitable

---

lib/groupio.c
lib/pwio.c
lib/sgroupio.c
lib/shadowio.c
libmisc/log.c

Every non-const pointer converts automatically to it.

Remove superfluous casts to 'void*'

---

man/login.defs.d/TTYGROUP.xml

Closes #457
The existing prose was confusing, or simply wrong.  Make it clear that only the group ownership of the tty is affected, and how. Also move the paragraph about defaults after the discussion of acceptable TTYGROUPs, as this seems more natural.

Improve TTYGROUP description in login.defs manpage

---

lib/groupmem.c
lib/prototypes.h
src/newusers.c

Fix memory leaks by replacing realloc(3) with reallocf(3)

---

configure.ac
lib/mempcpy.h
lib/stpecpy.h
lib/stpeprintf.h
libmisc/Makefile.am
libmisc/agetpass.c
libmisc/idmapping.c
libmisc/mempcpy.c
libmisc/stpecpy.c
libmisc/stpeprintf.c
src/groupmod.c

I've seen far too many cases of Undefined Behavior in calls to snprintf(3) that catenate a string just in the last few months.  It's not designed for catenating strings, and should _never_ be used for that.  Let's replace it by a safer API.
The simplification of code at call site talks by itself.
You'll notice that some calls to strncat(3) didn't allow me to write the most beautiful code in  the last calls to stpeprintf(); don't worry; I also plan to replace those strncat(3) calls by some other API.  But not in this patch set, which is restricted to stpeprintf() for simplicity.
---
Edit:
strncat has also been replaced by stpecpy(), which has the same improvements compared to other string copying functions that stpeprintf() has over snprintf(3).

Add stpeprintf()

---

libmisc/find_new_gid.c
libmisc/find_new_uid.c

Due to compatibility reasons neither UID nor GID should overflow to -1, be it on systems with 16-bit or 32-bit uid_t/gid_t since -1 is special.  It has different meaning for example as a chown(2) parameter, could become 65535 in programs compiled when uid_t was 16bit and possibly more issues.

find_new_[ug]id: Skip over IDs that could overflow to -1

---

lib/get_pid.c
lib/prototypes.h
man/newgidmap.1.xml
man/newuidmap.1.xml
src/newgidmap.c
src/newuidmap.c

newuidmap and newgidmap currently take an integner pid as the first argument, determining the process id on which to act.  Accept also "fd:N", where N must be an open file descriptor to the /proc/pid directory for the process to act upon.  This way, if you
exec 10</proc/99
newuidmap fd:10 100000 0 65536
and pid 99 dies and a new process happens to take pid 99 before newuidmap happens to do its work, then since newuidmap will use openat() using fd 10, it won't change the mapping for the new process.
Closes #635

newuidmap and newgidmap: support passing pid as fd

---

lib/bit.h

* Define ULONG_WIDTH if non-existent
* bit_ceil_wrapul(): stop recursion and call bit_ceilul() instead

lib: two fixes in bit.h

---

.github/workflows/runner.yml

Skip updating grub packages that are currently breaking apt-get dist-upgrade.

g-h-a workflow: workaround

---

lib/get_pid.c

Fixes: 6974df39a: newuidmap and newgidmap: support passing pid as fd

get_pidfd_from_fd: return -1 on error, not 0

---

tests/libsubid/04_nss/libsubid_zzz.c

Fixes: efbbcade43: Use safer allocation macros

libsubid: include alloc.h

---

tests/newgidmap/01_newgidmap/newgidmap.test
tests/newuidmap/01_newuidmap/newuidmap.test

The failure message got changed, but the tests looking for it did not.

tests: newuidmap and newgidmap: update expected fail message

---

tests/common/config.sh

git-worktree(1) uses a regular file for <.git>, instead of a directory.
```
alx@debian:~/src/shadow/shadow$ ls -la
total 24
drwxr-xr-x  6 alx alx 4096 Feb 26 15:37 .
drwxr-xr-x  4 alx alx 4096 Feb 19 18:44 ..
drwxr-xr-x  9 alx alx 4096 Feb 26 15:39 .bare.git
drwxr-xr-x 15 alx alx 4096 Feb 26 14:43 docker
drwxr-xr-x 15 alx alx 4096 Feb 26 15:37 git
drwxr-xr-x 15 alx alx 4096 Feb 19 18:47 master
docker  git  master
alx@debian:~/src/shadow/shadow$ cd docker/
alx@debian:~/src/shadow/shadow/docker$ file .git
.git: ASCII text
alx@debian:~/src/shadow/shadow/docker$ cat .git
gitdir: /home/alx/src/shadow/shadow/.bare.git/worktrees/docker
```

tests: Support git-worktree(1)

---

lib/defines.h
lib/fields.c
lib/gshadow.c
libmisc/date_to_str.c
libmisc/utmp.c
src/su.c

This consists of some patches from @eggert, and some patches of mine which have been more or less based on his suggestions.  See the origin of the discussion at Debbugs: <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032393#159>.
I didn't intend to remove strlcpy(3), since the bugs are independent of the use of strlcpy(3).  I opted for fixing the bugs, and keeping strlcpy(3) where it's (IMO) the most appropriate call.
We might want to drop strlcpy(3), but I think that should be addressed separately, and after having fixed the bugs.
There's one patch from Paul that I didn't take or write an alternative, and that's because I didn't yet understand it.  It's `Avoid silent truncation of console file data` (see Debbugs above).

Various fixes related to string copying

---

src/usermod.c

The --gid option accepts a group name or id. When a name is provided, it is resolved to an id by looking up the name in the group database (/etc/group).
The --prefix option overides the location of the passwd and group databases. I suspect the --gid option was overlooked when wiring up the --prefix option.
useradd --gid already respects --prefix; this change makes usermod behave the same way.
Fixes: https://github.com/shadow-maint/shadow/commit/b6b2c756c91806b1c3e150ea0ee4721c6cdaf9d0

usermod: respect --prefix for --gid option

---

lib/fields.c

Added a check to search for control characters and return -1 (in "err") if found.

Control character check

---

.github/workflows/static-code-analysis.yml

Run on pushes and drop unnecessary write access.
Should avoid pull-requests comments like
https://github.com/shadow-maint/shadow/pull/695#issuecomment-1491876950

ci: update Differential ShellCheck

---

lib/semanage.c

Both semanage and libsemanage actually set the user's mls range to the default of the seuser, which makes more sense and removes a bit of code for usermod and useradd.  More fine-grained details must always be set with some other tool
(semanage) anyway.

semanage: Do not set default SELinux range

---

lib/sssd.c

Avoid unnecessary syslog output, like:
Apr 01 13:35:09 dlaptop userdel[45872]: userdel: sss_cache exited with status 1
Apr 01 13:35:09 dlaptop userdel[45872]: userdel: Failed to flush the sssd cache.

sssd: skip flushing if executable does not exist

---

README.md
doc/contributions/build_install.md
doc/contributions/ci.md
doc/contributions/coding_style.md
doc/contributions/introduction.md
doc/contributions/license.md
doc/contributions/releases.md
doc/contributions/tests.md

I have created the following documentation to define how to contribute to this project. I think it's best to centralize all our documentation in one place and make it as simple as possible to reduce the maintenance burden. http://shadow-maint.github.io/shadow-www/ should be doing that, but it isn't updated, so in my opinion we should close it.
As a summary, this project has two type of consumers: developers and sysadmins. The former will expect to have all the meaningful documentation (development guidelines, release notes, etc.) in the development repository. This PR will take care of them. The latter is interested in how to configure and use the commands, which can be checked in the man pages. And in the release notes, which are already up-to-date in the Github page.
Having said that, I …

Contributions documentation

---

share/containers/fedora.dockerfile

libbsd-devel libeconf-devel have already been added to the spec file and they should be installed by the `dnf builddep` command.

ci: remove explicit fedora dependencies

---

.github/workflows/static-code-analysis.yml
.travis.yml
share/containers/alpine.dockerfile
share/containers/debian.dockerfile
share/containers/fedora.dockerfile

If make fails in a multi-process invocation, the log is pretty much unreadable.  To make it readable, build as much as can be built without failing.  If it succeeds, then we're done.  If there was a failure, run a single-process make again, which we know should fail at its first target; that will print the few lines we're really interested in, and they will be at the very end of the log.
This has some side effects:  Now we build as much as we can, instead of failing as early as possible; this may make CI a bit slower.  However, it also has the benefit that you see _all_ the error messages that could be given, instead of needing to fix the first error to see the next and so on.

CI: Make build logs more readable

---

libmisc/yesno.c

Do not stop after 79 characters. Read the complete line to avoid arbitrary limitations.
```
cat > passwd-poc << EOF
root:x:0:0:root:/root:/bin/bash
root:x:0:0:root:/root:/bin/bash
root:x:0:0:root:/root:/bin/bash
EOF
python -c "print(80*'y')" | pwck passwd-poc
```
Two lines should still be within the file because we agreed only once to remove a duplicated line.
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>

Read whole line in yes_or_no

---

src/newgrp.c
src/useradd.c

The tools newgrp and useradd expect waitpid to behave as described in its manual page. But the notes indicate that if SIGCHLD is ignored, waitpid behaves differently.
A user could set SIGCHLD to ignore before starting newgrp through exec. Children of newgrp would not become zombies and their PIDs could be reassigned before newgrp could call kill with the child pid and SIGCONT.
The useradd tool is not installed setuid, but I have added the default there as well (copied from vipw).

newgrp/useradd: always set SIGCHLD to default

---

configure.ac
libmisc/yesno.c

getline(3) is much more readable than manually looping.  It has some
overhead due to the allocation of a buffer, but that shouldn't be a
problem here.  If that was a problem, we could reuse the buffer (thus
making the function non-reentrant), but I don't think that's worth the
extra complexity.
Using getline(3) has the benefit that the function can then use
rpmatch(3) just by changing one line; note to downstream packagers:
distros that use glibc may be interested in patching that line for i18n
purposes.
While we're at it, apply some other minor improvements to this file:
-  Remove comment saying which files use this function.  That's likely
to get outdated.  And anyway, it's just a grep(1) away, so it doesn't
really add any value.
-  Remove unnecessary casts to (void) that were used to …

libmisc/yesno.c: Use getline(3) and rpmatch(3)

---

libmisc/obscure.c
man/passwd.1.xml

I kept the minimum length as 8, since it was what we had for the simplest passwords already.  8 is probably not what you really want from a password, but I believe it should be up to users to chose what they want.  If we raise this too much, we may upset some people, so let's be cautious.
Add the relevant XKCD to the passwd(1) manual page.  It already explains most of the rationale behind this patch.
The strength of a password is an exponential formula, where the base is the size of the character set, and the exponent is the length of the password.  That already shows why long passwords of just lowercase letters are better than short Pa$sw0rdZ3.  But an even more important point is that humans, when forced to use symbols in a password, are more likely to do trivial substitutions on simple …

libmisc, man: Drop old check and advice for complex character sets in passwords

---

libmisc/yesno.c

The getline function does not return a pointer but the amount of read characters. The error return value to check for is -1.
Set buf to NULL to avoid dereference of an uninitialized stack value.
The getline function returns -1 if size argument is NULL. Always use a valid pointer even if size is unimportant.

libmisc/yesno.c: Fix regression

---

lib/prototypes.h
libmisc/loginprompt.c
src/login.c

The `login_prompt` function used in `login` utility allows setting of environment variables when entered next to a user name. These variables still exist in memory even if login attempt failed. A subsequent login from another user takes these environment variables into account.
Also within the privileged code of login running as root a memory leak exists with these environment variables. With default values it would be very hard to trigger an OOM or do other malicious things though.
My suggestion is to remove this undocumented feature.
Also simplified API and fixed a signal unsafe usage while at it.

login_prompt: Fix implementation issues

---

lib/commonio.c

I have removed some obsolete code. Also, since POSIX.1-2008 is a requirement for shadow, O_CLOEXEC can be used which removes the need to call fcntl for a file descriptor.

commonio.c: Simplification

---

lib/commonio.c

Reported in #686, by wyj611 when trying to lock a file that is not present

open with O_CREAT when lock path does not exist

---

man/generate_translations.mak
man/its.rules

its by default does not support xml tags inside translatable units.  Use custom its rules from
https://www.w3.org/TR/xml-i18n-bp/#relating-docbook-plus-its
to enable the tags which are in use by docbook.

Fix broken docbook translations

---

lib/commonio.c

This avoids regressions introduced with do_fcntl_lock.
It is effectively a revert of the following revisions (dropped them in a `git rebase` and copied the resulting file into new branch):
- 0bce9c9808e6932b63a50caf537eaa528d7ed73c
- e899e3d745e9115b3229ed0b68d268fce7891252
- 65470e5c7ddbc2885ad35fbd0218b91a75626c2f
It also addresses the following issues:
- https://github.com/shadow-maint/shadow/issues/718
- https://github.com/shadow-maint/shadow/issues/686

commonio: Use do_lock_file again

---

libmisc/setupenv.c
src/sulogin.c

Some strings are first written into static char arrays before passed to functions which expect a const char pointer anyway.
It is easier to pass these strings directly as arguments.

Remove some static char arrays

---

lib/get_pid.c

Neither a pid_t below 1 nor a negative fd could be valid in this context.
$ newuidmap -1 1 1 1
newuidmap: Could not open proc directory for target 4294967295

get_pid.c: Use tighter validation checks

---

libmisc/prefix_flag.c

Using --prefix in a setuid binary is quite dangerous. An unprivileged user could prepare a custom shadow file in home directory. During a data race the user could exchange directories with links which could lead to exchange of shadow file in system's /etc directory.
This could be used for local privilege escalation.

process_prefix_flag: Drop privileges

---

src/chsh.c

The getusershell implementation of musl returns every line within the /etc/shells file, which even includes comments. Only consider absolute paths for login shells.
Never allow a user to set a shell starting with `*` because that would lead to security issues (login and su would treat the home directory as a subsystem root).

chsh: Verify that login shell path is absolute

---

lib/getdef.c
src/chsh.c

You can see the memory leaks with address sanitizer if shadow is compiled with `--enable-vendordir=/usr/etc`.
How to reproduce:
1. Prepare a custom shell file as root
```
mkdir -p /etc/shells.d
echo /bin/myshell > /etc/shells.d/custom
```
2. Run chsh as regular user
```
chsh
```

Plug econf memory leaks

---

libmisc/root_flag.c
libmisc/sub.c
src/su.c

These commits do not address any real security issues and are merely defensive measurements against faulty configurations:
- login and su could run into infinite loops if subsystems address each other (easiest form: home directory is root)
- check_perms in su is recursive. Nested subsystems could trigger a stack overflow
- chroot/chdir should be called in that order to avoid races

Extend Subsystem Protection

---

lib/subordinateio.c

On failure, these are meant to return 0 with errno set.  But if an nss module is loaded, they were returning -ERRNO instead.

sub_[ug]id_{add,remove}: fix return values

---

libmisc/xgetXXbyYY.c

- Treat another out of memory condition and fail with exit(13) consistently within the file.
- Avoid duplicated code in error handling

xgetXXbyYY: Improve error handling

---

src/newusers.c

Make sure crypto_method set before sha-rounds. Only effects newusers.

Check if crypt_method null before dereferencing

---

src/chgpasswd.c
src/chpasswd.c

The permission also need to be checked before process_root_flag() since that can chroot into non-selinux environment (unavailable selinux mount point for example).

ch(g)passwd: Check selinux permissions upon startup

---

src/chgpasswd.c

Using the --sha-rounds option without first giving a crypt method via the --crypt-method option results in comparisons with a NULL pointer and thus make chgpasswd segfault:
$ chgpasswd -s 1
zsh: segmentation fault  chgpasswd -s 1
Current patch add a sanity check before these comparisons to ensure there is a defined encryption method.

chgpasswd: fix segfault in command-line options

---

src/newusers.c

Fixes build error:
newusers.c: In function 'update_passwd':
newusers.c:433:21: error: 'sflg' undeclared (first use in this function); did you mean 'rflg'?
introduced by
https://github.com/shadow-maint/shadow/commit/5cd04d03f94622c12220d4a6352824af081b8531 which forgot to define sflg for these configure options:
--without-sha-crypt --without-bcrypt --with-yescrypt

Fix yescrypt support

---

man/subuid.5.xml

Resolves: https://github.com/shadow-maint/shadow/issues/752
Fixes typo in `subuid(5)` that referenced "newusers(1)" rather than "newusers(8)".

subuid.5: reference newusers(8) rather than newusers(1)

---

src/lastlog.c

b1282224 (Add maximum padding to fit IPv6-Addresses, 2020-05-24) pads the From field header using `maxIPv6Addrlen - 3`.  This leaves the Latest field header misaligned.  Subtract 4 (the length of "From").
Before:
```
$ lastlog -t 2
Username         Port     From                                       Latest
gdm              tty1                                               Sun Jul 16 17:21:02 -0400 2023
test             tty2                                               Sun Jul 16 02:51:11 -0400 2023
```
After:
```
$ lastlog -t 2
Username         Port     From                                      Latest
gdm              tty1                                               Sun Jul 16 17:21:02 -0400 2023
test             tty2                                               Sun Jul 16 02:51:11 …
```

lastlog: fix alignment of Latest header

---

src/newgrp.c

Since newgrp is setuid-root, any write() system calls it does in order to print error messages will be done as the root user.
Unprivileged users can get newgrp to print essentially arbitrary strings to any open file in this way by passing those strings as argv[0] when calling execve(). For example:
$ setpid() { (exec -a $1$'\n:' newgrp '' 2>/proc/sys/kernel/ns_last_pid & wait) >/dev/null; }
$ setpid 31000
$ readlink /proc/self
31001
This is not a vulnerability in newgrp; it is a bug in the Linux kernel.
However, this type of bug is not new [1] and it makes sense to try to mitigate these types of bugs in userspace where possible.
[1]: https://lwn.net/Articles/476947/

newgrp: fix potential string injection

---

lib/Makefile.am
lib/commonio.c
lib/prototypes.h
lib/write_full.c
libmisc/copydir.c
libmisc/failure.c
libmisc/idmapping.c
libmisc/log.c
libmisc/utmp.c
src/login.c
src/su.c
src/useradd.c
src/usermod.c

write(2) may not write the complete given buffer.  Add a wrapper to avoid short writes.

Add wrapper for write(2)

---

configure.ac
etc/Makefile.am
etc/shadow-maint/Makefile.am

Releases: add etc/shadow-maint to distfiles

---

lib/commonio.c
lib/prototypes.h
lib/write_full.c
libmisc/copydir.c
libmisc/failure.c
libmisc/idmapping.c
libmisc/log.c
libmisc/utmp.c
src/login.c
src/su.c
src/useradd.c
src/usermod.c

Documentation:
-  Correct the comment documenting the function:
write_full() doesn't write "up to" count bytes (which is write(2)'s behavior, and exactly what this function is designed to avoid), but rather exactly count bytes (on success).
-  While fixing the documentation, take the time to add a man-page-like comment as in other APIs.  Especially, since we'll have to document a few other changes from this patch, such as the modified return values.
-  Partial writes are still possible on error.  It's the caller's responsibility to handle that possibility.
API:
-  In write(2), it's useful to know how many bytes were transferred, since it can have short writes.  In this API, since it either writes it all or fails, that value is useless, and callers only want to know if it succeeded or not. …

libmisc/write_full.c: Improve write_full()

---

src/chgpasswd.c
src/groupmems.c
src/su.c
src/useradd.c

Assist static analyzers in understanding final code paths.

Declare usage and failure handler noreturn

---

lib/groupio.c
lib/pwio.c
lib/subordinateio.c

subordinateio.c:360:20: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
360 |         range1 = (*(struct commonio_entry **) p1)->eptr;
|                    ^
subordinateio.c:364:20: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
364 |         range2 = (*(struct commonio_entry **) p2)->eptr;
|                    ^
groupio.c:215:15: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
215 |         if ((*(struct commonio_entry **) p1)->eptr == NULL) {
|               ^
groupio.c:218:15: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
218 |         if ((*(struct commonio_entry **) p2)->eptr == NULL) {
|               ^
groupio.c:222:34: warning: cast discards 'const' …

lib: avoid dropping const qualifier during cast

---

src/login.c

login.c:712:25: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]

login: use strlcpy to always NUL terminate

---

lib/commonio.c

commonio.c:522:15: warning: Although the value stored to 'cp' is used in the enclosing expression, the value is never actually read from 'cp' [deadcode.DeadStores]

lib/commonio: drop dead store

---

libmisc/btrfs.c

btrfs.c:42:13: warning: use of NULL 'cmd' where non-null expected [CWE-476] [-Wanalyzer-null-argument]

lib/btrfs: avoid NULL-dereference

---

lib/subordinateio.c

sprintf(3) does not take the destination buffer into account. Although the destination in these case is large enough, sprintf(3) indicates a code smell.
Use snprintf(3).

Avoid usage of sprintf

---

autogen.sh

```
This allows to do the following:
~/src/shadow/shadow/master$ mkdir .tmp/ && cd .tmp/
~/src/shadow/shadow/master/.tmp$ ../autogen.sh
```
Link: <https://github.com/shadow-maint/shadow/issues/795>
Cc: @thesamesam

autogen.sh: Support out-of-tree builds

---

src/groupadd.c

Both `gr_open` and `sgr_open` are using `commonio_open` function and when there is a failure this function sets `errno` accordingly.

groupadd: Improve error message when opening group file fails.

---

lib/utmp.c

update_utmp() should also return 0 when success.
Fixes: 1f368e1c1838de9d476a36897d7c53394569de08 ("utmp: update `update_utmp()")
Resolves: https://github.com/shadow-maint/shadow/issues/805

utmp: call prepare_utmp() even if utent is NULL

---

.github/workflows/runner.yml
Makefile.am
configure.ac
doc/contributions/tests.md
share/containers/alpine.dockerfile
share/containers/debian.dockerfile
share/containers/fedora.dockerfile
tests/unit/.gitignore
tests/unit/Makefile.am
tests/unit/test_logind.c

Add two simple test cases for the logind functionality, update CI to run the unit tests and briefly explain how to develop tests with this framework.
Resolves: https://github.com/shadow-maint/shadow/issues/790

Add cmocka as unit testing framework

---

src/useradd.c

currently content in this directory will have labels derived from /usr/etc, leading to strange errors for user operations later on

useradd: Set proper SELinux labels for def_usrtemplate

---

man/po/de.po
src/usermod.c

Fix badname option to be singular just like useradd.
Fixes: [45d6746219](https://github.com/shadow-maint/shadow/commit/45d674621918664c8736f94f862e86bddf4c3fd4) ("src: correct "badname" option")

Singular badname

---

lib/getdef.c
lib/getdef.h
src/groupadd.c
src/useradd.c

Closes #746
Only print the 'unknown item' message to syslog if we are actually parsing a login.defs.  Prefix it with "shadow:" to make it clear in syslog where it came from.
Also add the source filename to the console message.  I'm not quite clear on the econf API, so not sure whether in that path we will end up actually having the path, or printing ''.

Improve the login.defs unknown item error message

---

man/chage.1.xml
man/chpasswd.8.xml
man/passwd.1.xml

Support for `--prefix` was added in
https://github.com/shadow-maint/shadow/pull/714 and is available since shadow 4.14.0.
Close https://github.com/shadow-maint/shadow/issues/822

man: document --prefix option in chage, chpasswd and passwd

---

configure.ac
lib/btrfs.c
lib/readpassphrase.h
lib/utmp.c
man/chage.1.xml
man/chpasswd.8.xml
man/passwd.1.xml
src/useradd.c

I've cherry-picked 4 commits.  Here's the tentative text for a release:
```
shadow-4.14.2 (Casín) - shadow utils
Bugfix release.  Changes since shadow-4.14.0:
shadow-4.14.2:
-  libshadow:
-  Fix build with musl libc.
-  Avoid NULL dereference.
-  Update utmp at an initial login
-  useradd(8):
-  Set proper SELinux labels for def_usrtemplate
shadow-4.14.1:
-  Build system:
-  Merge libshadow and libmisc into a single libshadow.  This fixes
problems in the linker, which were reported at least in Gentoo.
```
The considerations I took for which commits to cherry-pick was:
-  Include patches that have been reported as bugs by users.
-  Include the fix for a NULL dereference, even if no bug report was open.  The fix is small, and covers a CWE.
-  Exclude other fixes, such as not ignoring …

4.14.2-a1:  Candidate for a 2nd bugfix release for 4.14

---

lib/utmp.c

```
free(NULL) is valid; there's no need to check for NULL.  Simplify.
Fixes: 5178f8c5afb6 ("utmp: call prepare_utmp() even if utent is NULL")
```

lib/utmp.c: Don't check for NULL before free(3)

---

share/containers/fedora.dockerfile

libbsd is unwanted in Fedora and RHEL, and the recently released Fedora 39 doesn't contain this dependency. Let's build without it to avoid the compilation error.
Resolves: https://github.com/shadow-maint/shadow/issues/839

CI: fix Fedora 39 build

---

src/logoutd.c

ut_line doesn't hold a string.  It is a null-padded fixed-width array. Luckily, I don't think there has ever existed a ut_line ("/dev/tty*") that was 32 bytes long.  That would have resulted in a buffer overrun. Anyway, do the right thing, which is copying into a temporary string.

src/logoutd.c: Fix theoretical buffer overrun

---

lib/chkname.c

The maximum length of 32 wasn't being enforced in the code, and POSIX doesn't specify that maximum length either, so it seems it was an arbitrary limit of the past that doesn't exist any more.  Use a regex that has no length limit.
Closes: <https://github.com/shadow-maint/shadow/issues/836>

lib/chkname.c: Update regex for valid names

---

lib/strtcpy.h
lib/utmp.c
lib/zustr2stp.h

For arrays of char, both NITEMS() and SIZEOF_ARRAY() return the same value.  However, NITEMS() is more appropriate.  Think of wide-character equivalents of the same code; with NITEMS(), they would continue to be valid, while with SIZEOF_ARRAY(), they would be wrong.

lib/: Use NITEMS() instead of SIZEOF_ARRAY() where number of elements is meant

---

src/chsh.c

If an entry in /etc/shells is not an absolute path (comments or partial reads due to fgets), the line should not be considered as a valid login shell.
In general all systems should have getusershells, but let's better be safe than sorry.

chsh: limit acceptable shells to absolute paths

---

lib/defines.h

We require C11 since a few releases ago.  It seems I missed this reminder of ANSI C (C89) back then.

lib/defines.h: Remove condition on __STRICT_ANSI__

---

src/pwunconv.c
src/vipw.c

Upcoming `gcc-14` enabled a few warnings into errors, like `-Wimplicit-function-declaration`. This caused `shadow` build to fail as:
pwunconv.c: In function 'main':
pwunconv.c:132:13: error: implicit declaration of function 'getdef_bool' [-Wimplicit-function-declaration]
132 |         if (getdef_bool("USE_TCB")) {
|             ^~~~~~~~~~~
The change adds missing include headers.

src: add missing declaration of `getdef_bool`

---

lib/shell.c
lib/user_busy.c
src/gpasswd.c

We don't need to terminate them manually after the call.  Remove all that paranoid code, which in some cases was even wrong.  While at it, let's do a few more things:
-  Use sizeof(buf) for the size of the buffer.  I found that a few cases were passing one less byte (probably because the last one was manually zeroed later).  This caused a double NUL.  snprintf(3) wants the size of the entire buffer to properly terminate it.  Passing the exact value hardcoded is brittle, so use sizeof().
-  Align and improve style of variable declarations.  This makes them appear in this diff, which will help review the patch.

lib/, src/: snprintf(3) already terminates strings with NUL

---

src/su.c

su.c:678:26: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘const void *’ [-Wformat=]
su.c:681:44: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘const void *’ [-Wformat=]
su.c:683:46: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘const void *’ [-Wformat=]
Reported-by: Christian Göttsche <cgzones@googlemail.com>

src/su.c: Fix type of variable

---

src/login.c

Group them at the end of the list of variable definitions, and use '#if defined()' instead of '#if[n]def'.  Also indent nested ones.

src/login.c: Group preprocessor conditionals

---

lib/commonio.c
lib/env.c
lib/get_pid.c
lib/hushed.c
lib/nss.c
lib/pwauth.c
lib/shell.c
lib/string/sprintf.c
lib/string/sprintf.h
lib/subordinateio.c
lib/user_busy.c
src/chage.c
src/chfn.c
src/gpasswd.c
src/login.c
src/newgrp.c
src/newusers.c
src/su.c
src/useradd.c
src/vipw.c
tests/unit/Makefile.am
tests/unit/test_sprintf.c

It wraps snprintf(3) so that it performs some steps that one might forget, or might be prone to accidents:
-  It calculates the size of the destination buffer, and makes sure it's an array (otherwise, using sizeof(s) would be very bad).
-  It calculates if there's truncation or an error, returning -1 if so.
BTW, this macro doesn't have any issues of double evaluation, because sizeof() doesn't evaluate its argument (unless it's a VLA, but then the static_assert(3) within NITEMS() makes sure VLAs are not allowed).
This macro is very similar to STRTCPY(), defined in lib/string/strtcpy.h.

lib/string/sprintf.h: Add SNPRINTF() macro

---

man/generate_mans.mak
man/generate_translations.mak

Having a dedicated build directory breaks manual page creation.
Failing command sequence:
```
mkdir build; cd build
../configure --enable-man
make -C man
```

man/: Support compiling in build directory

---

lib/getdef.c
man/login.defs.d/PASS_WARN_AGE.xml

Negative values in login.defs never make sense (except someone wants to forcefully disable a feature with `-1` instead of commenting out a line or start breaking things by using even smaller values, which will be fixed in later PRs).
As a side note, util-linux does not support negative values either. See https://github.com/util-linux/util-linux/blob/master/lib/logindefs.c

lib/getdef.c: Adjust getdef_ boundaries

---

lib/defines.h

Special care has to be taken for 32 bit systems with a 64 bit time_t, since their long data type is still 32 bit.
Reported-by: @stoeckmann

lib/defines.h: Use 'time_t' for DAY

---

man/login.1.xml
man/login.defs.5.xml
man/login.defs.d/CONSOLE_GROUPS.xml
man/login.defs.d/ENV_HZ.xml
man/su.1.xml
man/sulogin.8.xml

CONSOLE_GROUPS and ENV_HZ are not used if PAM is enabled. Remove them (and even whole paragraphs since they would be empty now) if PAM is enabled.

man/: Remove more login.defs items if PAM is in use

---

man/Makefile.am
man/chgpasswd.8.xml
man/chpasswd.8.xml
man/generate_mans.mak
man/gpasswd.1.xml
man/login.defs.5.xml
man/login.defs.d/BCRYPT_MIN_ROUNDS.xml
man/login.defs.d/ENCRYPT_METHOD.xml
man/login.defs.d/SHA_CRYPT_MIN_ROUNDS.xml
man/login.defs.d/YESCRYPT_COST_FACTOR.xml
man/newusers.8.xml
man/passwd.1.xml

The BCRYPT and YESCRYPT relevant items should be described in manual pages.

man/: add BCRYPT and YESCRYPT information

---

lib/age.c
lib/defines.h
lib/isexpired.c
lib/pwd2spwd.c
src/chage.c
src/chpasswd.c
src/newusers.c
src/passwd.c
src/pwck.c
src/pwconv.c
src/useradd.c
src/usermod.c

These are the patches that I reviewed from that PR.
Cc: @stoeckmann

Some patches from #876

---

lib/Makefile.am
lib/adds.c
lib/adds.h
tests/unit/Makefile.am
tests/unit/test_adds.c

These functions add 2 or 3 longs, saturating to LONG_{MIN,MAX} instead of overflowing.
Cc: @stoeckmann

lib/addsl.[ch]: Add addsl() and addsl3()

---

lib/sgetgrent.c

If reallocation fails in function list, then reset the size to 0 again. Without the reset, the next call assumes that `members` points to a memory location with reserved space.
Also use size_t instead of int for size to prevent signed integer overflows. The length of group lines is not limited.
Fixes 45c0003e53ab671c63dcd530fd9f3245d3b29e76 (4.14 release series)
1. Prepare a group file (one long group line and a shorter one, both with a list of users)
```
$ echo -n "root:x:0:" > /tmp/uwu
$ yes , | tr -d '\n' | dd of=/tmp/uwu bs=10 count=3145728 seek=1 conv=notrunc iflag=fullblock
$ echo -e "\nbin:x:1:," >> /tmp/uwu
```
2. Run grpck with tight memory constraints
```
$ ulimit -d 102400
$ grpck /tmp/uwu
Segmentation fault (core dumped)
```

lib/sgetgrent.c: fix null pointer dereference

---

lib/defines.h

ISO C guarantees that #undef is a no-op if there is no such macro.
C11::6.10.3.5p2:
> A preprocessing directive of the form
>
>       # undef identifier new-line
>
> causes the specified identifier no longer to be defined as a macro
> name.  It is ignored if the specified identifier is not currently
> defined as a macro name.
Link: <http://port70.net/~nsz/c/c11/n1570.html#6.10.3.5p2>

lib/defines.h: Don't wrap #undef in #ifdef

---

src/sulogin.c

The sulogin program calls pw_entry in a loop while incorrect root passwords are entered.
Free the previously allocated memory to avoid memory exhaustion.
Proof of Concept (compile with -fsanitize=address):
Run `sulogin` and enter wrong root passwords multiple times. Then press CTRL+D. You can see as many direct leaks as wrong passwords have been entered.

src/sulogin.c: Free previously allocated memory

---

src/su.c

Fixes: ef95bb7ed139 ("src/su.c: Fix type of variable")
Closes: <https://github.com/shadow-maint/shadow/issues/915>
Reported-by: @thesamesam 
Signed-off-by: @alejandro-colomar

src/su.c: do_check_perms(): Fix -Wincompatible-pointer-types bug

---

configure.ac
lib/Makefile.am
share/containers/debian.dockerfile

This fixes build with glibc-2.33 (newer glibc merged libdl and libpthread into libc):
```
libtool: link: x86_64-pc-linux-gnu-gcc -isystem /usr/include/bsd -DLIBBSD_OVERLAY -O2 -pipe -Wl,-O1 -o login login.o login_nopam.o  -Wl,--as-needed ../lib/.libs/libshadow.a -lcrypt -lsystemd -lpam -lpam_misc -lbsd
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: ../lib/.libs/libshadow.a(libshadow_la-nss.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Link correctly with libdl

---

src/passwd.c

That flag has never existed, AFAICS.
Closes: <https://github.com/shadow-maint/shadow/issues/929>
Cc: @thalman

src/passwd.c: Remove comment about a -s flag

---

lib/attr.h
lib/audit_help.c
lib/cleanup_group.c
lib/cleanup_user.c
lib/copydir.c
lib/getdate.y
lib/logind.c
lib/loginprompt.c
lib/obscure.c
lib/pam_pass_non_interactive.c
lib/prototypes.h
lib/pwdcheck.c
lib/semanage.c
src/expiry.c
src/gpasswd.c
src/grpconv.c
src/grpunconv.c
src/login.c
src/su.c
src/sulogin.c

Also fixes #918 by adding the omitted parameter name in active_sessions_count.
Suggested-by: Alejandro Colomar <alx@kernel.org>

lib/, src/: Rename unused macro as MAYBE_UNUSED

---

etc/pam.d/Makefile.am

Install pam configs for chage and newusers when using ./configure --with-libpam --disable-account-tools-setuid.
Fixes https://github.com/shadow-maint/shadow/issues/810.

Install chpasswd,newusers configs when built with pam but without setuid

---

lib/agetpass.c
lib/agetpass.h
man/passwd.1.xml
src/passwd.c

New option --stdin/-s is available for root user. It is useful
for automation/setup and it makes shadow utils passwd more versatile.

Implement reading password from pipe/stdin

---

lib/Makefile.am
lib/atoi/strtoi.c
lib/atoi/strtoi.h
lib/atoi/strtou_noneg.c
lib/atoi/strtou_noneg.h
tests/unit/Makefile.am
tests/unit/test_atoi_strtoi.c

This is in preparation of a rework of `get[u]long()`.

Add strto[iu]_() and strtou_noneg().

---

src/sulogin.c

The `pass` array can be removed. It is possible to directly work with the result of `agetpass`, which in turn removes the need to prepare and clean up the array.
And there was one more external variable which was not in use.

src/sulogin.c: Simpler password handling

---

lib/chkname.c
tests/unit/test_chkname.c

According to sysconf manual page, _SC_LOGIN_NAME_MAX is the maximum name length, **including** the terminating null byte.
Take this into account while validating user names.
Also support systems which might have no upper limit or no _SC_LOGIN_NAME_MAX at all.

lib/chkname.c: Fix off by one validation of _SC_LOGIN_NAME_MAX

---

etc/pam.d/Makefile.am

Fixes: 341d80c2c751 ("Makefile: move chpasswd and newusers to pamd target")
Link: <https://github.com/shadow-maint/shadow/pull/928#discussion_r1487687347>
Link: <https://github.com/shadow-maint/shadow/issues/926#issuecomment-1941324761>
Reported-by: @DimStar77
Reported-by: @jubalh 
Cc: @loqs
Cc: @dvzrv
Cc: @ikerexxe 
To be cherry-picked to 4.14.x.

etc/pam.d/Makefile.am: Fix typo

---

lib/age.c
lib/isexpired.c
src/chage.c

The first commit is about SCALE removal:
- SCALE is always DAY, so drop the definition
- With SCALE being gone, drop unneeded calculations
The other commits clean up calculations based on days per epoch and seconds per epoch. It is much easier to calculate with days (in a long) than with seconds (in a time_t) because the former is already the native encoding in shadow files and LONG_MAX exists, while TIME_T_MAX does not exist everywhere.
- Use proper casts which become relevant for 32 bit systems with 64 bit time_t, e.g. musl-based distributions
- Let `passwd` work with day precision instead of seconds since epoch to allow easier range checking
- Unify integer overflow checks in `chage`
- Add LONG_MAX range checks when working with sp_max etc.
Proof of Concept (for 64 bit systems):
1. …

Day and time cleanups for shadow file entries

---

lib/agetpass.c
lib/defines.h
src/passwd.c

This PR addresses two issues:
* The passwd utility has limit 200 characters. Some admins wants uses longer passwords for technical accounts
* The passwd utility cuts the provided password silently
First commit unifies the password length limit between `agetpass.c` and `passwd.c`.
The second one introduces checking the length of provided password.

Passwd length

---

configure.ac
lib/log.c
lib/sizeof.h
lib/user_busy.c
lib/utmp.c
src/logoutd.c

utmpx is specified by POSIX as an XSI extension.  That's more portable than utmp, which is unavailable for example in musl libc.  The manual page specifies that in Linux (but it probably means in glibc), utmp and utmpx (and the functions that use them) are identical, so this commit shouldn't affect glibc systems.
Assume utmpx is always present.
Also, if utmpx is present, POSIX guarantees that some members exist:
-  ut_user
-  ut_id
-  ut_line
-  ut_pid
-  ut_type
-  ut_tv
So, rely on them unconditionally.
Fixes: 170b76cdd1a9 ("Disable utmpx permanently")
Closes: <https://github.com/shadow-maint/shadow/issues/945>
Reported-by: @firasuke
Reported-by: @awilfox

lib/, src/, configure.ac: Use utmpx instead of utmp

---

lib/utmp.c

Oops.  I forgot to do a change.
Recently, we started using utmpx instead of utmp, and we updated
<./configure.ac> to do the checks for 'struct utmpx' instead of
'struct utmp'.  However, I forgot to update the preprocessor
conditionals accordingly.
Fixes: 64bcb54fa962 ("lib/, src/, configure.ac: Use utmpx instead of utmp")
Link: <https://github.com/shadow-maint/shadow/pull/954>
Cc: @firasuke
Cc: @awilfox
Cc: @ikerexxe

lib/utmp.c: Use the appropriate autotools macros for struct utmpx

---

.github/workflows/runner.yml
share/containers/alpine.dockerfile
share/containers/debian.dockerfile
share/containers/fedora.dockerfile

Otherwise, 'cat testsuite.log' isn't run, since 'set -e' aborts the script earlier.

Use trap(1) to show the testsuite log

---

src/vipw.c

Link: <https://github.com/shadow-maint/shadow/issues/959>
Link: <https://github.com/shadow-maint/shadow/pull/960>
Cc: @skyler-ferrante 
Cc: @hallyn 
Cc: @karelzak 
Cc: @ikerexxe 
Cc: @brauner

Hard-code a remaining case of Prog.

---

lib/Makefile.am
lib/fd.c
lib/prototypes.h
src/chage.c
src/chfn.c
src/chsh.c
src/expiry.c
src/gpasswd.c
src/newgrp.c
src/passwd.c
src/su.c

Adding function check_fds to new file fd.c. The function check_fds should be called in every setuid/setgid program. I also added sanitize_env to every setuid/setgid program.

Adding checks for fd omission

---

lib/idmapping.c

```diff
Previously, we were performing the following two checks:
-       if (ranges != ((argc + 2) / 3)) {
-       if ((ranges * 3) > argc) {
Let's draw a table of the possible input that would pass the first check:
argc:	0 1 2 3 4 5 6 7 8 9
rng:	0 1 1 1 2 2 2 3 3 3
a+2/3*3:0 3 3 3 6 6 6 9 9 9	<-- this is  roundup(argc, 3);
a+2/3:	0 1 1 1 2 2 2 3 3 3	<-- this is  roundup(argc, 3) / 3;
rng*3:	0 3 3 3 6 6 6 9 9 9
From those, let's extract those that would also pass the second check:
argc:	0     3     6     9
rng:	0     1     2     3
rng*3:	0     3     6     9
We can see that there's a simple check for this input:
+       if (ranges * 3 != argc) {
As a sanity check, let's draw a table of the acceptable input with that check:
rng:	0     1     2     3
rng*3:	0     3     6     9
argc:	0     3 …
```

lib/idmapping.c: get_map_ranges(): Merge two input checks into a simpler one

---

.github/workflows/static-code-analysis.yml
share/containers/alpine.dockerfile
share/containers/debian.dockerfile
share/containers/fedora.dockerfile

It was being done so that the second one prints errors without races. However, the same thing can be done by passing -Orecurse to make(1).
And this makes the logs even more readable, since there's no racy output at all.
Fixes: 97f79e3b2715 ("CI: Make build logs more readable")
Link: <https://github.com/shadow-maint/shadow/pull/702>
Link: <https://github.com/nginx/unit/pull/1123>
Acked-by: @ikerexxe 
Cc: @ac000
Cc: @thresheek
Cc: @arbourd

share/containers/, .github/workflows/: Don't make(1) twice

---

src/passwd.c

OPENLOG() already sets the program name as the prefix.
This resulted in entries like:
$ journalctl 2>/dev/null | grep passwd
Mar 03 01:09:47 debian passwd[140744]: passwd: can't view or modify password information for root
Fixes: 8e167d28afd6 ("[svn-upgrade] Integrating new upstream version, shadow (4.0.8)")

src/passwd.c: Don't print the program name twice in a log entry

---

lib/getdate.y
src/id.c
src/sulogin.c

Remove `/*ARGSUSED*/` comments.  Instead, use appropriate declarators for main().  ISO C allows using int main(void) if the parameters are going to be unused.
Also, do some cosmetic changes in the uses of argc and argv, to show where they are used.

lib/, src/: Use int main(void) where appropriate

---

lib/pam_pass_non_interactive.c

The combination of bzero and free could be optimized away.

lib/pam_pass_non_interactive.c: use strzero/free

---

.gitignore
man/.gitignore

before this, the following untracked files showed up in `git status`:
lib/atoi/.dirstamp
lib/string/.dirstamp
lib/time/.dirstamp
man/da/login.defs.d
man/da/messages.mo
man/de/login.defs.d
man/de/messages.mo
man/fr/login.defs.d
man/fr/messages.mo
man/it/login.defs.d
man/it/messages.mo
man/pl/login.defs.d
man/pl/messages.mo
man/ru/login.defs.d
man/ru/messages.mo
man/sv/login.defs.d
man/sv/messages.mo
man/uk/login.defs.d
man/uk/messages.mo
man/zh_CN/login.defs.d
man/zh_CN/messages.mo
test-driver

gitignore: add a few more generated files to be ignored

---

man/po/fr.po

For some reason, "32 characters" were wrongly translated to 16 in french translation file.

Fix wrong french translation

---

lib/copydir.c

There are no guarantees that fstatat() does not clobber the stat buffer on errors.
Use a temporary buffer so that the following code sees correct attributes of the source entry.
Issue #973

lib/copydir:copy_entry(): use temporary stat buffer

---

lib/env.c

If not enough memory is available for more environment variables, treat it exactly like not enough memory for new environment variable content.

lib/env.c: treat out of memory condition as error

---

man/newgidmap.1.xml
man/newuidmap.1.xml

The manpages for newuidmap and newgidmap had a typo "[pid[" instead of "[pid]".  They were also unclear about what the /proc/pid fd should be.  Fix both.
Closes #977
Reported-by: igo95862@yandex.ru

newuidmap and newgidmap manpages: fix fd description

---

share/containers/fedora.dockerfile

Now that fedora 40 is out let's update the flags.

CI: Update build flags for fedora 40

---

lib/get_gid.c
lib/get_pid.c
lib/get_uid.c
lib/getgr_nam_gid.c
lib/getrange.c
lib/gettime.c
lib/limits.c
lib/prefix_flag.c
src/useradd.c

This is part of the changes from <https://github.com/shadow-maint/shadow/pull/892> (at v5).
I've decided to leave the last commits in that PR for later, since I have some ideas to do it differently.  The first commits are refactors that are easier to apply separately.
Here's the range-diff vs that PR at v5:
```
$ git range-diff master gh/getrange gh/gr2
1:  cb16a79a =  1:  cb16a79a lib/getrange.c: getrange(): Small refactor
2:  06a3c8fa =  2:  06a3c8fa lib/getrange.c: getrange(): Small refactor
3:  d25fedb2 =  3:  d25fedb2 lib/getrange.c: getrange(): Remove temporary variable
4:  e40985b1 =  4:  e40985b1 lib/getrange.c: getrange(): Return early to remove an else
5:  e76e4722 =  5:  e76e4722 lib/getrange.c: getrange(): Don't else after return
6:  6fa83922 =  6:  6fa83922 lib/getrange.c: …
```

Some getrange() simplification

---

lib/alloc.h

Instead of GNU builtins and extensions, these macros can be implemented with C11's _Generic(3), and the result is much simpler (and safer, since it's now an error, not just a warning).
I don't remember who showed me that trick; it was some months ago, in the gcc@ or libc-alpha@ mailing lists (maybe it was @uecker).  I reimplemented these macros from scratch for neomutt(1), and did it with _Generic(3), and it was much nicer than all those GNU extensions.  Let's incorporate those improvements here.  :-)
---
Revisions:
<details>
v2 changes:
-  Update copyright
```
$ git range-diff shadow/master gh/alloc alloc 
1:  18ec0d85 ! 1:  84517ec8 lib/alloc.h: Reimplement [X]REALLOC[F]() macros with _Generic(3)
@@ Commit message …
```

lib/alloc.h: Reimplement [X]REALLOC[F]() macros with _Generic(3)

---

lib/atoi/a2i.c
lib/atoi/a2i.h
lib/getrange.c

---
Revisions (to see revisions before v9, see the threads below):
<details>
<summary>v9</summary>
v9 changes:
-  Rebase
```
$ git range-diff gr2..gh/getrange shadow/master..getrange 
1:  fc6bfaa7 = 1:  fca2ece3 lib/atoi/a2i.[ch]: Add const-generic macros
2:  61c128d9 = 2:  46466828 lib/getrange.c: getrange(): Use a2ul() instead of strtoul_noneg()
3:  06ac2307 = 3:  4ed6db3c lib/getrange.c: getrange(): Add const to pointer
4:  4141c586 = 4:  54c16a8a lib/getrange.c: getrange(): Add missing cast
5:  0e6a67cc = 5:  50917d95 lib/getrange.c: getrange(): Report an ERANGE error when min>max
```
</details>
<details>
<summary>v9b</summary>
v9b changes:
-  Reword attribution to @uecker 
```
$ git range-diff shadow/master gh/getrange getrange 
1:  fca2ece3 ! 1:  ed2ec57d lib/atoi/a2i.[ch]: Add …
```

Many getrange() fixes

---

lib/port.c

```
RESOURCE_LEAK (CWE-772)
shadow-4.15.0/src/usermod.c:864:3: alloc_fn: Storage is returned from allocation function "__sgr_dup".
shadow-4.15.0/src/usermod.c:864:3: var_assign: Assigning: "nsgrp" = storage returned from "__sgr_dup(sgrp)".
shadow-4.15.0/src/usermod.c:964:1: leaked_storage: Variable "nsgrp" going out of scope leaks the storage it points to.
962|                   free (nsgrp);
963|           }
964|-> }
965|   #endif                                /* SHADOWGRP */
966|
RESOURCE_LEAK (CWE-772)
shadow-4.15.0/src/usermod.c:734:3: alloc_fn: Storage is returned from allocation function "__gr_dup".
shadow-4.15.0/src/usermod.c:734:3: var_assign: Assigning: "ngrp" = storage returned from "__gr_dup(grp)".
shadow-4.15.0/src/usermod.c:815:1: leaked_storage: Variable "ngrp" going out of …
```

Fix issues detected by static analyzer

---

src/useradd.c

While at it, I found and fixed a file-descriptor leak too, and a free(3) of an invalid pointer.
---
Revisions:
<details>
-  The only fdopen(3) mode that makes sense with mkstemp(3) is `"w"`.
```
$ git range-diff shadow/master gh/goto2 goto2 
1:  f753dbe8 = 1:  f753dbe8 src/useradd.c: set_defaults(): Fix order of clean-ups
2:  29e95616 = 2:  29e95616 src/useradd.c: set_defaults(): Rename goto label
3:  555b8b07 = 3:  555b8b07 src/useradd.c: set_defaults(): Do not free(3) the result of asprintf(3) if it failed
4:  29471eec = 4:  29471eec src/useradd.c: De-duplicate code
5:  4d125f77 ! 5:  59bb454a src/useradd.c: Add fmkstemp() to fix file-descriptor leak
@@ src/useradd.c: static void create_home (void);
static void create_mail (void);
static void check_uid_range(int …
```

More fixes for resource leaks

---

lib/chkname.c
lib/chkname.h
src/login.c

It encapsulates some logic that we may want to reuse elsewhere.
Link: <https://github.com/shadow-maint/shadow/pull/989>
Prompted by @MarcinDigitic's PR.
---
Revisions:
<details>
-  Call this function in a few places to add error handling.
```
$ git range-diff gh/master gh/loginnamemax loginnamemax 
1:  53067b08 = 1:  53067b08 lib/chkname.[ch]: Fix includes
2:  5c0af110 = 2:  5c0af110 lib/chkname.[ch]: login_name_max_size(): Add function
-:  -------- > 3:  2ac009ea src/login.c: main(): Use login_name_max_size()
```
</details>
<details>
-  Add missing include
```
$ git range-diff gh/master gh/loginnamemax loginnamemax 
1:  53067b08 = 1:  53067b08 lib/chkname.[ch]: Fix includes
2:  5c0af110 = 2:  5c0af110 lib/chkname.[ch]: login_name_max_size(): …
```

lib/chkname.[ch]: login_name_max_size(): Add function, and add missing error handling

---

Makefile.am

This is a first step to helping distributions to use our tests in CI.

tests: add the tests/ subdirectory to dist tarball

---

configure.ac

For some reason cmocka library isn't detected in fedora, thus the unit
tests aren't run on this platform. Changing the detection process to be
able to run the unit tests.
I'll be honest, I don't know why the previous way of detecting the library
didn't work. I tried several changes and neither of them seemed to detect
the library on my system even though it was installed.

configure: change cmocka library detection

---

man/lastlog.8.xml

Per https://tdg.docbook.org/tdg/4.5/term, term is a word being defined in a varlistentry.  The 'high uid' description is not a varlistentry, so <term> and </term> show up in the processed manpage.  See debian Bug#1072297.

man/lastlog: remove wrong use of keyword term

---

src/groupmod.c

When ori_group have more than 3 users, try "groupmod -n new_group -U user1,user2 ori_group",core dump occured.
Reading the source code and discovering in grp_update, "grp = *ogrp;" makes grp.gr_mem = *ogrp.gr_mem, so if -U without -a, gr_free_members(&grp) would free *ogrp.gr_mem, which makes original group_db original entry.gr_mem become a wild pointer.
If no -n, gr_update (&grp) would replace *ogrp with grp, nothing would happen; but if with -n, gr_update (&grp) would creat new entry so while write_all write *ogrp.gr_mem ,core dump occurs.
Add !nflg to avoid this situation.

src/groupmod.c: delete gr_free_members(&grp) to avoid double free

---

lib/csrand.c

I accidentally broke this code during an un-optimization.  We need to
start from a random value of the width of the limit, that is, 32 bits.
Thanks to Jason for pointing to his similar code in the kernel, which
made me see my mistake.
Fixes: 2a61122b5e8f ("Unoptimize the higher part of the domain of csrand_uniform()")
Closes: <https://github.com/shadow-maint/shadow/issues/1015>
Reported-by: @michaelbrunnbauer
Link: <https://git.zx2c4.com/linux-rng/tree/drivers/char/random.c#n535>
Cc: @zx2c4
Link: <https://github.com/shadow-maint/shadow/pull/638>
Link: <https://github.com/shadow-maint/shadow/issues/634>
Link: <https://github.com/shadow-maint/shadow/pull/624>

lib/csrand.c: Fix the lower part of the domain of csrand_uniform()

---

tests/run_some

This was causing errors in my local testing in vms.

tests/run_some: make sure unshared root user can descend build dir

---

lib/idmapping.c

The prctl(2) system-call wrapper is implemented as a variadic function. This makes it important to pass arguments to it of the right type (and more importantly of the right width), to avoid undefined behavior.
While at it, check errors with ==-1, not <0, which is more explicit.
See-also: prctl(2), PR_SET_KEEPCAPS(2const)
Link: <https://lore.kernel.org/linux-man/ddbdyaiptesjalgfmztxideej67e3yaob7ucsmbf6qvriwxiif@dohhxrqgwhrf/T/#med306b5b003f9cc7cc2de69fcdd7ee2d056d0954>
Cc: @xry111 
---
See also the manual page for this call, recently split from prctl(2):
Link: <https://www.alejandro-colomar.es/share/dist/man-pages/git/HEAD/man-pages-HEAD.pdf#PR_SET_KEEPCAPS.2const>
Here's an excerpt:
```
SYNOPSIS
#include <sys/prctl.h>
int prctl(PR_SET_KEEPCAPS, long state, 0L, 0L, 0L);
DESCRIPTION
Set …
```

lib/idmapping.c: Use long constants in prctl(2)

---

lib/getdef.c
lib/limits.c
lib/sgetspent.c
lib/shadow.c
src/chage.c
src/check_subid_range.c
src/faillog.c
src/get_subid_owners.c
src/passwd.c
src/useradd.c
src/usermod.c

---
<details>
<summary>v3</summary>
v3 changes:
-  Rebase
```
$ git range-diff gh/strtoll..gh/getuh strtoll..getuh 
1:  806f0ff5 =  1:  81c8665d lib/getdef.c: getdef_num(): Simplify, by calling a2si() instead of str2sl()
2:  f0181f03 =  2:  edff0c98 lib/getdef.c: getdef_unum(): Fix wrong limit check
3:  6d9d10eb =  3:  fd6cfab8 lib/getdef.c: getdef_long(): Simplify, by calling a2sl() instead of str2sl()
4:  f4692dc4 =  4:  435aa712 lib/limits.c: set_prio(): Simplify, by calling str2si() instead of str2sl()
5:  36614d26 =  5:  e4b220b9 lib/limits.c: set_umask(): Simplify, by calling str2i(mode_t, ) instead of str2ul()
6:  b9dcbb2b =  6:  14c14376 lib/limits.c: setup_limits(): Simplify, by calling a2si() instead of str2sl()
7:  9df29b9f =  7:  1e642aef lib/limits.c: setup_limits(): …
```

Uh, get some more numbers

---

lib/port.c

Closes: <https://github.com/shadow-maint/shadow/issues/1036>
---
Revisions:
<details>
-  tfix
```
$ git range-diff string gh/port port 
1:  9c18ae98 = 1:  9c18ae98 lib/port.c: getttyuser(): Remove dead code
2:  eee9766c = 2:  eee9766c lib/port.c: getttyuser(): Use goto to break out of nested loops
3:  7494e4bc = 3:  7494e4bc lib/port.c: getportent(): Rename goto label
4:  4d43f0bf = 4:  4d43f0bf lib/port.c: getportent(): Remove obvious comments
5:  c47a94e5 ! 5:  08bbebb3 lib/port.c: getportent(): Make sure there are at least 2 ':' in the line
@@ lib/port.c: next:
* TTY devices.
*/
-+  if (strchr(cp, ":") == NULL)
++  if (strchr(cp, ':') == NULL)
+          goto next;
+
port.pt_names = ttys;
@@ lib/port.c: next:
* The last entry in the list is a NULL pointer.
*/
-+ …
```

Fix lib/port.c issues

---

lib/find_new_gid.c
lib/find_new_uid.c

Without this, building fails:
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc  -I. -I..    -I..   -lcrypt  -g -O2 -MT libshadow_la-find_new_gid.lo -MD -MP -MF .deps/libshadow_la-find_new_gid.Tpo -c -o libshadow_la-find_new_gid.lo `test -f 'find_new_gid.c' || echo './'`find_new_gid.c
libtool: compile:  gcc -I. -I.. -I.. -lcrypt -g -O2 -MT libshadow_la-find_new_gid.lo -MD -MP -MF .deps/libshadow_la-find_new_gid.Tpo -c find_new_gid.c  -fPIC -DPIC -o .libs/libshadow_la-find_new_gid.o
find_new_gid.c: In function 'check_gid':
find_new_gid.c:117:20: error: 'UINT16_MAX' undeclared (first use in this function)
117 |         if (gid == UINT16_MAX || gid == UINT32_MAX) {
|                    ^~~~~~~~~~
find_new_gid.c:20:1: note: 'UINT16_MAX' is defined in header '<stdint.h>'; did you forget …
```

Include stdint.h for UINT16_MAX/UINT32_MAX

---

lib/chkname.c

If you want a larger object, you'll have to wait at least until the universe expands so much.  (Or maybe not, but luckily, programming is simpler than physics.)
If an implementation doesn't recognize its own limitations, its a bug, not a feature.
Closes: <https://github.com/shadow-maint/shadow/issues/1052>
Cc: @stoeckmann

lib/chkname.c: An object cannot expand further than the universe in which it resides

---

man/groupadd.8.xml
man/groupmod.8.xml

While looking at groupmod I was confused by `--append GID` so I omitted it and groupmod worked just fine.
So looking into the code I figured the man page was wrong - and decided to fix this.
While at it I also fixed some other minor issues, ie #848 
One might argue that this PR is not complete and maybe a large overhaul is required but on the other hand those large PRs are hard to handle so I decided to keep it simple for now and do one step at a time.

man: groupmod: Minor improvements

---

tests/libsubid/04_nss/Makefile

Align on variable name BUILD_BASE_DIR for overriding the toplevel directory. This is the same name as accepted by tests/common/config.sh.
Without this, the test libsubid/04_nss fails in Debian's autopkgtests.

tests/libsubid/04_nss: fix setting basedir

---

Makefile.am

automake complained about duplicate definitions of EXTRA_DIST:
```
autoreconf: running: automake --add-missing --copy --no-force
Makefile.am:19: warning: EXTRA_DIST multiply defined in condition TRUE ...
Makefile.am:3: ... 'EXTRA_DIST' previously defined here
autoreconf: Leaving directory '.'
```

Makefile.am: avoid warning: EXTRA_DIST multiply defined

---

lib/time/day_to_str.h
src/chage.c

That is, use localtime_r(3) instead of gmtime_r(3).
Closes: <https://github.com/shadow-maint/shadow/issues/1057>
Reported-by: @kenion
Cc: @hallyn 
Cc: @eggert

lib/, src/: Use local time for human-readable dates

---

man/userdel.8.xml

The previous wording seemed to say that -f implied -r.  It doesn't; -f only skips safety checks, so reword accordingly.
Closes: <https://github.com/shadow-maint/shadow/issues/1062>
Reported-by: @martinvonwittich
Cc: @hallyn

man/userdel.8.xml: Reword '-f'

---

lib/user_busy.c

Since:
- utmpx APIs are used in non-Linux code blocks
- `<utmpx.h>` is already unconditionally included in Linux parts in other files then 
unconditionally include it in this file as well.

lib/user_busy.c: Include <utmpx.h>

---

src/useradd.c

write_full() returns -1 on error and useradd was checking another value.
Closes: https://github.com/shadow-maint/shadow/issues/1072
Fixes: f45498a6c286 ("libmisc/write_full.c: Improve write_full()")

useradd: fix write_full() return value

---

lib/run_part.c
lib/run_part.h
lib/shadowlog_internal.h

- Use correct data type
- Unify logging (at least the fprintf calls)
- Reduce visibility of locally used function

lib/run_part: Minor cleanups

---

lib/tz.c

The tz function is only called if ENV_TZ starts with a slash.
If the specified file cannot be read, the code implies that ENV_TZ would be returned if it does not start with a slash.
Since we know that it DOES start with a slash, the code can be simplified to state that "TZ=CST6CDT" is returned as a default if the specified file cannot be read.
Benefit of this change is that strcpy's use case here can be easier verified.

lib: Eliminate dead code

---

src/check_subid_range.c

I forgot to remove the setting of errno when I switched from strtoul_noneg() to str2ul().  strtoul(3) needs errno for determining success, but str2ul() does not.
Fixes: f3a1e1cf098d ("src/check_subid_range.c: Call str2ul() instead of strtoul_noneg()")

src/check_subid_range.c: Remove dead code

---

src/useradd.c

I forgot to change the comparison sign that checks the return value of write_full()
Closes: https://github.com/shadow-maint/shadow/issues/1072
Fixes: 8903b94c86c9 ("useradd: fix write_full() return value")
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2313559

useradd: fix comparison sign for write_full() return

---

lib/fields.c
lib/getdate.y
lib/gshadow.c
lib/limits.c
lib/loginprompt.c
lib/nss.c
lib/port.c
lib/setupenv.c
lib/strtoday.c
src/suauth.c

This is a subset of the patches from #1048 for an easier review.
Cc: @hallyn 
Cc: @ikerexxe

Simplify string handling (piecemeal)

---

.github/actions/install-dependencies/action.yml
.github/workflows/runner.yml

CI: update Ubuntu repositories configuration
Recently Ubuntu updated its repositories configuration file from
`/etc/apt/sources.list` to `/etc/apt/sources.list.d/ubuntu.source`.
Thus, we need to update its location to be able to install all the
package dependencies.
In addition, the CI script was trying to uncomment the lines starting
with `deb-src`, but there is none in the new configuration file format.
Replace `Types: deb` by `Types: deb deb-src` at the beginning of the
line instead.
Besides that, let's centralize the installation of dependencies in a single
workflow and install `libltdl-dev`, which is a dependency in the new
Ubuntu version.
Link: https://linuxconfig.org/ubuntus-repository-configuration-ubuntu-sources-have-moved-to-etc-apt-sources-list-d-ubuntu-sources
Closes: …

CI: update Ubuntu repositories configuration

---

doc/contributions/introduction.md

Fixes: 981bb8f9d1ba ("doc: add contributions introduction")
Reported-by: @nabijaczleweli

doc/contributions/introduction.md: Fix typo in link

---

lib/alloc/realloc.h
lib/alloc/reallocf.h

Zero-length allocation calls are non-portable, and may result in nasty
bugs when porting software to other platforms.  Let's just make sure
that we never do that.  Some algorithms need malloc(0) or realloc(p, 0)
to just succeed and give a pointer that has zero elements (but is not
NULL); let's just over-allocate 1 byte, which guarantees success, and
doesn't hurt at all.
BTW, I wonder what's the history about this issue.  If anyone knows what
was the original behavior of malloc(0) and realloc(p, 0), and can
illuminate, it would be very interesting.  Was it ANSI C that goofed it
by allowing NULL to be returned?  Was it before?
---
Revisions:
<details>
-  Do not avoid malloc(0) calls.  The only broken thing is realloc(p,0).  [@nabijaczleweli]
```
$ git range-diff master …
```

Avoid zero-size reallocation calls

---

src/chfn.c
src/chsh.c
src/newgrp.c
src/passwd.c

Fix coverity unbound buffer issues
During coverity scan, there are reported four issues
with unbounded source buffer for each usage of input arg
directly with syslog function.
Sample coverity test report for chsh.c file:
1. string_size_argv: argv contains strings with unknown size.
int main (int argc, char **argv)
[...]
4. var_assign_var: Assigning: user = argv[optind]. Both are now tainted.
user = argv[optind];
[...]
CID 5771784: (#1 of 1): Unbounded source buffer (STRING_SIZE)
15. string_size: Passing string user of unknown size to syslog.
SYSLOG ((LOG_INFO, "changed user '%s' shell to '%s'", user, loginsh));
Similar issue is reported three times more:
File: chfn.c, function: main, variable: user
File: passwd.c, function: main, variable: name
File: newgrp.c, function: main, variable: …

Fix coverity unbounded source buffer issues

---

src/useradd.c

After https://github.com/shadow-maint/shadow/pull/586, there is a memory leak now for `user_groups` (although probably uncritical).
Since the `get_groups` function can be called twice, the first time for default (the `GROUPS` config parameter) and the second time through the `-G` flag. 
In fact, the second call to the `get_groups` function writes groups to `user_groups` from zero, without freeing up occupied memory.
In this change, `uset_groups` is explicitly cleared before filling.
<details><summary>valgrind leak example</summary>
```
// GROUPS from file, flag -G is not set
==59280== 22 bytes in 2 blocks are still reachable in loss record 15 of 36
==59280==    at 0x483E751: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==59280==    by 0x40E320: xmalloc (in …
```

src/useradd.c: get_groups(): Fix memory leak

---

lib/loginprompt.c

This is one of the commits from <https://github.com/shadow-maint/shadow/pull/1048>, to simplify the review.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/strtcpy shadow/master..strtcpy 
1:  3a253dc1 = 1:  61646fda lib/loginprompt.c: login_prompt(): Use strtcpy() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/strtcpy shadow/master..strtcpy 
1:  61646fda = 1:  5d288018 lib/loginprompt.c: login_prompt(): Use strtcpy() instead of its pattern
```
</details>

lib/loginprompt.c: login_prompt(): Use strtcpy() instead of its pattern

---

.github/actions/install-dependencies/action.yml

Closes #1088
We can't be sure whether a github runner will have new- or old- style sources.list, so check whether the new exists, else use the old style.

CI: fix handling of sources.list

---

share/ansible/roles/ci_run/tasks/fedora.yml

The new fedora 41 has been released and some things have changed. Make
sure to install python and python3-dnf and specify the dnf version in
the roles.

CI: fix fedora build problems

---

lib/Makefile.am
lib/copydir.c
lib/fs/readlink/areadlink.c
lib/fs/readlink/areadlink.h
lib/fs/readlink/readlinknul.c
lib/fs/readlink/readlinknul.h
lib/tcbfuncs.c
lib/user_busy.c

readlink(2) doesn't terminate the string.  That's makes using this function unnecessarily complicated and unsafe.  This patch set adds some wrappers that produce a null-terminated string, which significantly simplifies the code at call site.
---
Revisions:
<details>
-  Fix typo
```
$ git range-diff master gh/readlink readlink 
1:  7b577fb5 ! 1:  2a5d0d77 lib/fs/readlink/readlinknul.[ch]: readlinknul(): Add function
@@ lib/fs/readlink/readlinknul.h (new)
+          return -1;
+
+  if (len == size) {
-+          stpcpy(&path[size-1], "");
++          stpcpy(&buf[size-1], "");
+          errno = E2BIG;
+          return -1;
+  }
+
-+  stpcpy(&path[len], "");
++  stpcpy(&buf[len], "");
+  return len;
+}
+
2:  1f297e5e = 2:  46b23e73 lib/fs/readlink/readlinknul.h: …
```

Simplify readlink(2) calls

---

src/gpasswd.c

This fix addresses an issue in is_valid_user_list() where the free operation was attempted on an address not allocated with malloc(). By duplicating the pointer with xstrdup(users) into dup, and using dup as the original pointer, we ensure that only the valid pointer is freed, avoiding an invalid free operation.
Suggested-by: <https://github.com/frostb1ten>
Reported-by: <https://github.com/frostb1ten>
Cc: Serge Hallyn <serge@hallyn.com>

gpasswd: fix invalid free in is_valid_user_list()

---

lib/Makefile.am
lib/list.c
lib/string/strchr/strchrcnt.c
lib/string/strchr/strchrcnt.h
lib/string/strcmp/streq.c
lib/string/strcmp/streq.h

---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/strchrcnt shadow/master..strchrcnt 
1:  e2897fc6 = 1:  75c3a972 lib/string/strchr/strchrcnt.[ch]: strchrcnt(): Add function
2:  4b6ff861 = 2:  9ae5b104 lib/list.c: comma_to_list(): Use strchrcnt() instead of its pattern
```
</details>
<details>
-  Simplify commit message
```
$ git range-diff master gh/strchrcnt strchrcnt 
1:  75c3a972 ! 1:  2d1571a2 lib/string/strchr/strchrcnt.[ch]: strchrcnt(): Add function
@@ Metadata
-    lib/string/strchr/strchrcnt.[ch]: strchrcnt(): Add function
+    lib/string/strchr/: strchrcnt(): Add function
2:  9ae5b104 = 2:  fa711665 lib/list.c: …
```

Abstract counting commas/characters in a string

---

src/login_nopam.c

The reason for that code seems to be some ancient AIX versions that defined a value that was too small (32).  We don't support such systems. In the link below, I found the following comment and code:
```
/*
* Some AIX versions advertise a too small MAXHOSTNAMELEN value (32).
* Result: long hostnames would be truncated, and connections would be
* dropped because of host name verification failures. Adrian van Bloois
* (A.vanBloois@info.nic.surfnet.nl) figured out what was the problem. */
#if (MAXHOSTNAMELEN < 64)
#undef MAXHOSTNAMELEN
#endif
/* In case not defined in <sys/param.h>. */
#ifndef MAXHOSTNAMELEN
#define MAXHOSTNAMELEN  256             /* storage for host name */
#endif
```
Today's systems seem to be much better regarding this macro.  Rely on them.
Link: …

src/login_nopam.c: Rely on the system's MAXHOSTNAMELEN

---

lib/shadow.c

We already have sgetspent(), with identical semantics, defined in <lib/sgetspent.c>.
```diff
$ diff -u <(grepc sgetspent .) <(grepc my_sgetspent .)
--- /dev/fd/63	2024-11-11 11:56:55.444055921 +0100
+++ /dev/fd/62	2024-11-11 11:56:55.444055921 +0100
@@ -1,23 +1,19 @@
-./lib/sgetspent.c:struct spwd *
-sgetspent(const char *string)
+./lib/shadow.c:static struct spwd *my_sgetspent (const char string)
{
-	static char spwbuf[PASSWD_ENTRY_MAX_LENGTH];
-	static struct spwd spwd;
-	char *fields[FIELDS];
-	char *cp;
-	int i;
+	int                 i;
+	char                *fields[FIELDS];
+	char                *cp;
+	static char         spwbuf[BUFSIZ];
+	static char         empty[] = "";
+	static struct spwd  spwd;
/*
* Copy string to local buffer.  It has to be tokenized and we
* have to do that …
```

lib/shadow.c: my_sgetspent(): There can be only one!

---

lib/commonio.c
lib/fputsx.c
lib/port.c
lib/run_part.c
lib/sgetpwent.c
src/grpconv.c
src/login_nopam.c
src/vipw.c

GCC 15 will add -Wzero-as-null-pointer-constant for deprecating it, and I'm working on a paper for deprecating it from ISO C too. Let's remove any uses in our code base.
I've done this change by building GCC from master, adding -Werror=zero-as-null-pointer-constant to ./autogen.sh, and fixing every error that showed up.
Closes: <https://github.com/shadow-maint/shadow/issues/1120>
Link: <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117059>
Link: <https://software.codidact.com/posts/292718/292759#answer-292759>

lib/, src/: Use NULL instead of 0 as a null pointer constant

---

lib/idmapping.c

If get_map_ranges is called on a 32 bit system, where UINT_MAX equals ULONG_MAX, the count check allows illegal values if uid and loweruid are both UINT_MAX due to unsigned integer underflow.
Always use the fix size UINT_MAX as count limitation due to guarantee that sizeof(unsigned int) <= sizeof(unsigned long) in C language.
Fixes: 7c43eb2c4ea6 ("lib/idmapping.c: get_map_ranges(): Move range check to a2ul() call")
Proof of Concept (32 bit system):
```
newuidmap $$ 4294967295 4294967295 10
```
Output:
```
newuidmap: uid range [4294967295-9) -> [4294967295-9) not allowed
```
Expected:
```
newuidmap: subuid overflow detected.
usage: newuidmap [<pid>|fd:<pidfd>] <uid> <loweruid> <count> [ <uid> <loweruid> <count> ] ...
```

lib/idmapping.c: Fix get_map_ranges regression

---

.github/workflows/runner.yml

If a job in a matrix fails we don't want to cancel all jobs, thus we need to set `fail-fast: false` as a strategy property.

CI: avoid cancelling all jobs when one fails

---

share/container-build.sh

The instructions are written so that this script should be run from the root of the repository.  Specify the path from the root of the repo. Before this fix, the command needed to be run from within `<share/>`.

share/container-build.sh: Fix path

---

src/usermod.c

With the PR 352 it is not possible anymore to run `usermod --home "" <USERNAME>`. This PR will fix that regression.
Related to: https://github.com/shadow-maint/shadow/pull/352

Allow setting an empty homedir

---

src/login_nopam.c

That's what the getnameinfo(3) manual page recommends.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/ni_maxhost shadow/master..ni_maxhost 
1:  10cd2649 = 1:  c88c4408 src/login_nopam.c: resolve_hostname(): Use NI_MAXHOST instead of MAXHOSTNAMELEN with getnameinfo(3)
```
</details>
<details>
-  Several rebases
```
$ git range-diff c88c4408^..c88c4408 shadow/master..gh/ni_maxhost 
1:  c88c4408 = 1:  092982c3 src/login_nopam.c: resolve_hostname(): Use NI_MAXHOST instead of MAXHOSTNAMELEN with getnameinfo(3)
```
</details>
<details>
-  Rebase
```
$ git range-diff alx/master..gh/ni_maxhost shadow/master..ni_maxhost 
1:  092982c3 = 1:  b5e0b46b src/login_nopam.c: resolve_hostname(): Use NI_MAXHOST instead …
```

src/login_nopam.c: resolve_hostname(): Use NI_MAXHOST instead of MAXHOSTNAMELEN with getnameinfo(3)

---

lib/csrand.c

---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/csrand shadow/master..csrand 
1:  83995494 = 1:  71610097 lib/csrand.c: csrand(): Use read(2) instead of fread(2)
```
</details>

csrand(): Use POSIX read(2) instead of the heavier stdio

---

lib/gshadow_.h

We require ISO C11 since a long time ago.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff alx/master..gh/stdc shadow/master..stdc 
1:  2fe225b9 = 1:  9dff5322 lib/gshadow_.h: __STDC__ is always 1
```
</details>
<details>
-  Rebase
```
$ git range-diff gh/master..gh/stdc shadow/master..stdc 
1:  9dff5322 = 1:  8d74bdeb lib/gshadow_.h: __STDC__ is always 1
```
</details>

lib/gshadow_.h: __STDC__ is always 1

---

src/groupadd.c
src/groupmod.c

When running groupadd or groupmod with the -U|--user option, also update the group shadow database if it is used.
This closes <https://github.com/shadow-maint/shadow/issues/1124>. See there for more information.
CC @alejandro-colomar

groupadd, groupmod: Update gshadow file with -U

---

lib/addgrps.c
lib/console.c
lib/motd.c
src/groupadd.c
src/groupmod.c
src/login_nopam.c
src/suauth.c

This is a subset of #1048 for easier review.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff gh/strtcpy..gh/strsep strtcpy..strsep 
1:  1ada0038 = 1:  b806041d lib/, src/: Use strsep(3) instead of strtok(3)
```
</details>
<details>
-  Rebase
```
$ git range-diff gh/strtcpy..gh/strsep master..strsep 
1:  b806041d = 1:  b87f79c6 lib/, src/: Use strsep(3) instead of strtok(3)
```
</details>
<details>
-  Expand commit message
```
$ git range-diff master gh/strsep strsep 
1:  b87f79c6 ! 1:  75903c36 lib/, src/: Use strsep(3) instead of strtok(3)
@@ Metadata
lib/, src/: Use strsep(3) instead of strtok(3)
+    strsep(3) is stateless, and so is easier to reason about.
+
+    It also has a slight difference: strtok(3) …
```

Replace most strtok(3) calls by strsep(3)

---

lib/sgetgrent.c

We were possibly using an old value if (i == NFIELDS-1).  A few lines below this check, we use the element in [3] (that is, [NFIELDS-1]), but it might be old, since we didn't necessarily fill it ourselves.
Be stricter, and require that all NFIELDS fields are found.
Closes: <https://github.com/shadow-maint/shadow/issues/1144>
Cc: Serge Hallyn <serge@hallyn.com>
Cc: Iker Pedrosa <ipedrosa@redhat.com>
---
Revisions:
<details>
-  It's not UB; it's just a behavior bug.
```
$ git range-diff master gh/nfields nfields 
1:  aef7dfa9 ! 1:  54ec0af5 lib/sgetgrent.c: sgetgrent(): Fix use of uninitialized value
@@ Metadata
-    lib/sgetgrent.c: sgetgrent(): Fix use of uninitialized value
+    lib/sgetgrent.c: sgetgrent(): Fix use of …
```

lib/sgetgrent.c: sgetgrent(): Fix use-after-free bug

---

lib/fs/readlink/readlinknul.c
lib/fs/readlink/readlinknul.h

---
Revisions:
<details>
-  Rebase
```
$ git range-diff alx/master..gh/readlink shadow/master..readlink 
1:  56975bbd = 1:  1df0343c lib/fs/readlink/readlinknul.h: readlinknul(): Simplify the return value
2:  dacf42bd = 2:  13c7d4c9 lib/fs/readlink/readlinknul.h: readlinknul(): Silence warning
```
</details>
<details>
-  Rebase
```
$ git range-diff gh/master..gh/readlink shadow/master..readlink 
1:  1df0343c = 1:  9c99500d lib/fs/readlink/readlinknul.h: readlinknul(): Simplify the return value
2:  13c7d4c9 = 2:  340b5544 lib/fs/readlink/readlinknul.h: readlinknul(): Silence warning
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/readlink shadow/master..readlink 
1:  9c99500d = 1:  26597716 …
```

readlinknul(): Minor tweaks

---

src/su.c

Launch a login shell again if requested through "su -" or "su -l".
Fixes: d9923431eb38 ("src/: Use xasprintf() instead of its pattern")
Closes: <https://github.com/shadow-maint/shadow/issues/1160>

su: Fix su - regression

---

src/login_nopam.c

The function `user_match` actually modifies the string passed as its first argument, so use `char *` instead of `const char *`.

src/login_nopam.c: Fix compiler warnings

---

lib/chkname.c

```
GNU Hurd recommends having no system limits.  When a program needs a
limit, because it needs to validate user input, it is recommended that
each program defines its own limit macros.  The rationale is that this
avoids hard-coded limits in ABIs, which cannot be modified ever.
However, that doesn't mean that programs should have no limits at all.
We use this limit for validating user input, and so we shouldn't allow
anything just because the system doesn't want to set a limit.
So, when sysconf(2) returns -1, either due to an error or due to a claim
for no limits, we must fall back to the LOGIN_NAME_MAX value.  And if
the system doesn't define that value, we must define it ourselves (we're
more or less free to choose any value, so let's pick the one that glibc
provides nowadays).
``` …

lib/chkname.c: Put limits for LOGIN_NAME_MAX and sysconf(_SC_LOGIN_NAME_MAX)

---

lib/attr.h

These are not available on earlier versions and builds break there.

lib/attr.h: use C23 attributes only with gcc >= 10

---

src/login_nopam.c

A regression in `/etc/login.access` parsing could allow or deny more users than configured. It affects shadow 4.17.x.
The regression takes place in `login` tool if compiled without PAM support. Basically all distributions ship either with PAM support or use util-linux login, so this affects rather few systems, let alone it requires the `EXCEPT` keyword in `/etc/login.access`. Affected right now:
- Linux From Scratch
And these distributions could be affected depending on compile configuration, but have older unaffected versions:
- Gentoo
- NixOS
The `list_match` function handles `EXCEPT` entries in `/etc/login.access` through recursive calls. It calls itself with `NULL`, which was then passed to `strtok` so parsing continued at current position.
Replacing `strtok` with `strsep`, this means …

login: Fix no-pam authorization regression

---

lib/gshadow.c
lib/run_part.c
lib/shadow.c
lib/spawn.c

Before you read any further: No reachable issues exist in current code base (as far as I can tell)
But these defense mechanisms would have made reviewing easier because I could have skipped a few searches:
1. Use `_exit` instead of `exit` after execution errors
After a fork and a failing exec, calling `exit` is not the best choice. Use `_exit` instead because tools like `groupmod` etc. use `add_cleanup` to clean up when `exit` is called. If the child, which inherits these instructions, calls `exit` by itself, these cleanup routines could release passwd/group locks too early. Again: Does not happen, because the code launches sub processes only after these cleanup routines have been already released again. Yet, better be safe than sorry.
2. Set close on exec on critical file descriptors …

Add cheap defense mechanisms

---

man/po/LINGUAS
man/po/ro.po
po/ro.po

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080487

Add Romanian translation

---

man/Makefile.am

Support for `/etc/suauth` only exists if su is installed without PAM support. If su is not installed (--without-su) or if PAM support is enabled (default), do not install suauth.5 manual page.

man/: Install suauth.5 only if feature exists

---

src/chgpasswd.c
src/chpasswd.c
src/login_nopam.c
src/newusers.c
src/suauth.c

First pull request based on current work of refactoring login_nopam.c:
Huge files could trigger signed integer overflows if enough lines are within the file. Use intmax_t which is at least 64 bit to move this event far into the future. I don't see a need to handle THAT case in any more effort.
Also turn a variable from unsigned int to size_t just to make sure that even systems with huge amount of memory cannot trigger an out of boundary access.

src/: Make line number overflows less likely

---

man/passwd.1.xml

If passwd is called with -P, then PAM handling is disabled ([src/passwd.c line 749](https://github.com/shadow-maint/shadow/blob/master/src/passwd.c#L746-L751)). The manual page claims that host files would be used, which is not true.

man/passwd.1.xml: -P disables PAM support

---

src/login_nopam.c

The recursive nature of list_match triggered regression during refactoring. In Linux-PAM, the same code exists which could lead to stack overflow because access.conf could be arbitrarily long.
Use an iterative approach for easier refactoring, to support long lines in the future and to stay in sync with Linux-PAM.
Please see https://github.com/linux-pam/linux-pam/pull/871 for more details since Linux-PAM could at least be affected on a very weird system configuration. Definitely not a security issue, but let's stay in sync and be prepared for a switch from fgets to getline.

src/login_nopam.c: Use iterative list_match

---

lib/encrypt.c
src/gpasswd.c

Most code paths make sure that a plaintext password, if not read from stdin or a file, is properly cleared.
This is not true for all `pw_encrypt` error cases. If the salt itself is considered "unknown", then `exit` is called. Let `pw_encrypt` return an error code so the program logic can clear passwords properly before handling the error.
One such example is musl. If passwd compiled for musl tries to encrypt a password with SHA512 which is longer than 256 characters, it fails. But this can be easily the valid password on the system, because glibc has no such problem. So, just wipe it.
Example output with this patch (passwd linked with musl):
```
$ passwd
Changing password for user
Old password:
crypt method not supported by libcrypt? (SHA512)
passwd: failed to crypt password with previous …
```

Clear plaintext passwords in more error cases

---

lib/commonio.c
src/chgpasswd.c
src/chpasswd.c
src/grpck.c
src/pwck.c
src/useradd.c
src/userdel.c
src/usermod.c

If we are not interested in the amount of errors but only if errors exist, use a flag instead of a counter. This eliminates the chance of signed integer overflows and better reflects the meaning of variable.
Keeping variable name and basically copied from src/faillog.c.

lib/, src/: Turn error counters into flags

---

configure.ac
lib/addgrps.c
lib/age.c
lib/prototypes.h
lib/setugid.c
src/newgrp.c

They're available in every system I checked: glibc,musl,{Free,Net,Open}BSD.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/setgroups shadow/master..setgroups 
1:  878f9ea6 = 1:  5fdcd89b configure.ac, lib/, src/: Assume setgroups(2) exists
2:  0270f587 = 2:  ee242d98 configure.ac, lib/: Assume initgroups(3) exists
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/setgroups shadow/master..setgroups 
1:  5fdcd89b = 1:  c6790b27 configure.ac, lib/, src/: Assume setgroups(2) exists
2:  ee242d98 = 2:  6518b23c configure.ac, lib/: Assume initgroups(3) exists
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/setgroups shadow/master..setgroups 
1:  c6790b27 ! 1:  d4be5ef8 …
```

configure.ac, lib/, src/: Assume setgroups(2) and initgroups(3) exist

---

configure.ac
lib/defines.h
lib/gshadow.c
lib/gshadow_.h
lib/sgroupio.c
src/chgpasswd.c
src/gpasswd.c
src/groupadd.c
src/groupmems.c
src/groupmod.c
src/grpck.c
src/grpconv.c
src/newusers.c
src/useradd.c
src/userdel.c
src/usermod.c

This check was testing a specific bug in a prehistoric libc version. Red Hat 3 is long dead, and it doesn't make sense to test for that specific bug.
---
Revisions:
<details>
-  Keep `lib/shadow.c` for musl, which doesn't have these APIs.
-  Include libc's `<gshadow.h>` if available.
```
$ git range-diff master gh/shadowgrp shadowgrp 
1:  7abca5a1 < -:  -------- configure.ac, lib/, src/: Presume working shadow group support in libc
-:  -------- > 1:  992aedca lib/: Include <gshadow.h> if it's available
-:  -------- > 2:  545bd8de configure.ac, lib/gshadow.c: Presume working shadow group support in libc
```
</details>
<details>
-  Remove obsolete comment
```
$ git range-diff master gh/shadowgrp shadowgrp 
1:  992aedca = 1:  992aedca lib/: …
```

configure.ac, lib/, src/: Presume working shadow group support in libc

---

src/vipw.c

This fixes a problem when the shell is not in monitor mode (job control enabled) which resulted in the terminal pgrp being set to an invalid value once vipw exited.  Fixes #1194.

Restore the original terminal pgrp after editing

---

doc/HOWTO
lib/pwauth.c
lib/pwauth.h
lib/pwdcheck.c
src/login.c
src/su.c

One of the benefits of rewriting a lot of code, is finding dead code that can be removed.  :-)
Cc: @thesamesam
---
Revisions:
<details>
-  Delete another round of dead code.
```
$ git range-diff master gh/deadbeef deadbeef 
1:  28a46878 = 1:  28a46878 lib/, src/, doc/: Remove dead code
2:  5064c6b4 = 2:  5064c6b4 lib/pwauth.*: PW_{ADD,CHANGE,DELETE,FTP,REXEC}: Remove dead code
-:  -------- > 3:  17e7da68 lib/, src/, doc/: Remove pw_auth()'s  as dead code
```
</details>
<details>
-  tfix in commit message
```
$ git range-diff master gh/deadbeef deadbeef 
1:  28a46878 = 1:  28a46878 lib/, src/, doc/: Remove dead code
2:  5064c6b4 = 2:  5064c6b4 lib/pwauth.*: PW_{ADD,CHANGE,DELETE,FTP,REXEC}: Remove dead code
3:  17e7da68 ! 3:  a66b4a9c lib/, …
```

[deadbeef] Remove dead code

---

configure.ac
lib/csrand.c
lib/defines.h
lib/gshadow.c
lib/gshadow_.h
lib/idmapping.c
lib/pam_defs.h

All relevant compilers have had __has_include() since immemorial times (GCC since version 5, according to <https://en.cppreference.com/w/c/compiler_support>).  It's now a C23 standard feature.
This reduces the complexity of the build system.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/has_include shadow/master..has_include 
1:  f716f558 = 1:  1afc7448 configure.ac, lib/: Use __has_include(<crypt.h>) instead of HAVE_CRYPT_H
2:  95ca17af = 2:  6107b7f8 configure.ac, lib/: Use __has_include(<sys/random.h>) instead of HAVE_SYS_RANDOM_H
3:  3d98527a = 3:  0a32d621 lib/: Use __has_include(<security/pam_misc.h>) instead of HAVE_SECURITY_PAM_MISC_H
4:  8052bd28 = 4:  fe3a23d3 lib/: Use __has_include(<security/openpam.h>) instead of …
```

Use cc(1)'s __has_include() instead of build-system checks

---

lib/chkname.c
src/useradd.c

---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/streq shadow/master..streq
1:  224930f8 = 1:  c122513c lib/chkname.c: is_valid_name(): Use streq() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/streq shadow/master..streq
1:  c122513c = 1:  7a8f1e66 lib/chkname.c: is_valid_name(): Use streq() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/streq shadow/master..streq
1:  7a8f1e66 = 1:  d335844d lib/chkname.c: is_valid_name(): Use streq() instead of its pattern
```
</details>
<details>
<summary>v1e</summary>
-  Rebase
```
$ git range-diff master..gh/streq shadow/master..streq 
1:  d335844d ! 1:  4aee5e06 lib/chkname.c: …
```

lib/, src/: Use streq() instead of its pattern

---

src/useradd.c

```
Wrappers like adduser(8) want to do their own stuff if the login name is
bad.  For that, they need to be able to differentiate such an error.
```
Closes: <https://github.com/shadow-maint/shadow/issues/1103>
Suggested-by: @zeha
Cc: @zugschlus
---
Revisions:
<details>
-  Rebase
```
$ git range-diff alx/master..gh/badname master..badname 
1:  4c084b1d = 1:  d288ade5 src/useradd.c: E_BAD_NAME: Use a different error code for bad login names
```
</details>
<details>
-  Rebase
```
$ git range-diff alx/master..gh/badname master..badname 
1:  d288ade5 = 1:  5b17bc41 src/useradd.c: E_BAD_NAME: Use a different error code for bad login names
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/badname …
```

src/useradd.c: E_BAD_NAME: Use a different error code for bad login names

---

lib/Makefile.am
lib/chkname.c
lib/string/ctype/strisascii/strisdigit.c
lib/string/ctype/strisascii/strisdigit.h
lib/strtoday.c
lib/subordinateio.c

---
Revisions:
<details>
-  Add strisdigit() and use it instead of open-coding it.
-  Add note about empty strings in commit message.
```
$ git range-diff master gh/alldigits alldigits 
-:  -------- > 1:  40c9035b lib/string/ctype/: strisdigit(): Add function
1:  a349dfd3 ! 2:  24335081 lib/: Reimplement all_digits() in terms of streq(stpspn()), and open-code it
@@ Metadata
-    lib/: Reimplement all_digits() in terms of streq(stpspn()), and open-code it
+    lib/: Use strisdigit() instead of its pattern
+
+    Note that the old code in
+
+            (1)  lib/strtoday.c:strtoday()
+            (2)  lib/subordinateio.c:append_uids()
+
+    was considering an empty string as if it were a number.
+    strisdigit() does not …
```

Add strisdigit(), and use it instead of its pattern

---

src/chsh.c

chsh(1) documents the -s option with this extra sentence:
> Setting this field to blank causes the system to select the default login shell.
As such warning about a blank string seems wrong.
Closes: <https://bugs.debian.org/876542>
Reported-by: 積丹尼 Dan Jacobson <jidanni@jidanni.org>

chsh: do not warn about blank shell

---

lib/time/day_to_str.h
src/chage.c

This reverts commit 3f5b4b56268269fefed55aa106f382037297d663.
The dates are stored as UTC, and are stored as a number of days since Epoch.  We don't have enough precision to translate it into local time. Using local time has caused endless issues in users.
This patch is not enough for fixing this issue completely, since printing a date without time-zone information means that the date is a local date, but what we're printing is a UTC date.  A future patch should add time-zone information to the date.
For now, let's revert this change that has caused so many issues.
Fixes: 3f5b4b562682 (2024-08-01; "lib/, src/: Use local time for human-readable dates")
Link: <https://github.com/ansible/ansible/blob/devel/test/integration/targets/user/tasks/test_expires.yml#L2-L20>
Link: …

Revert "lib/, src/: Use local time for human-readable dates"

---

lib/getdate.y

There is exactly one caller of this function, and it wants a date, not a time.  It is useless to be able to parse local dates, because we ultimately store a UTC date.  To avoid confusion, unconditionally use UTC.  Since this code had important bugs regarding offset, we can safely assume that no existing users rely on being able to use their local date (this never worked correctly).
Also, the code parsing time zones was quite bad.
Link: <https://github.com/shadow-maint/shadow/issues/1202>
Link: <https://github.com/shadow-maint/shadow/issues/1209>
Reported-by: @zeha 
Reported-by: @timparenti
Reported-by: @leegarrett
Cc: @kenion
Cc: @jubalh 
Cc: @eggert
Cc: @ikerexxe 
Cc: @hallyn 
Cc: @BrianInglis
---
Revisions:
<details>
-  Remove dead code.  difftm() was only used in …

lib/getdate.y: Ignore time-zone information and use UTC

---

configure.ac

Statically set PASSWD_PROGRAM depending on exec_prefix, and not by where the passwd program was at configure time.
Depending on the specific build situation before, this may or may not change the embedded passwd program path. Also configure.ac sets exec_prefix=/ for prefix=/usr, so this might be a bit confusing, but at least deterministic.
Closes: #1224

configure.ac: be deterministic about passwd location

---

src/chfn.c

This partially reverts commit 16cb664865541162c504a6f5ef5ca4b38b5e0c9a.
I'll try to reintroduce this change more carefully after investigation. For now, let's revert to a known-good state.
Fixes: 16cb66486554 (2024-07-01; "lib/, src/: Use strsep(3) instead of its pattern")
Closes: <https://github.com/shadow-maint/shadow/issues/1210>
Reported-by: @zeha 
Suggested-by: @zeha 
---
Revisions:
<details>
-  Reintroduce part of the transformation which is correct.  We can use stpsep().  See <https://github.com/shadow-maint/shadow/pull/1213>.
```
$ git range-diff master gh/strsep strsep
1:  db6885ed = 1:  db6885ed src/chfn.c: Partially revert "lib/, src/: Use strsep(3) instead of its pattern"
-:  -------- > 2:  e2ac691a src/chfn.c: Use stpsep() instead of its pattern
-: …
```

src/chfn.c: Fix bogus transformation

---

lib/audit_help.c
lib/cleanup_group.c
lib/cleanup_user.c
lib/prototypes.h
src/chage.c
src/gpasswd.c
src/groupadd.c
src/groupdel.c
src/groupmod.c
src/newgrp.c
src/useradd.c
src/userdel.c
src/usermod.c

This is a set of changes that Fedora introduced in a downstream patch. The idea is to converge upstream and downstream versions to reduce the maintenance burden. The patch was created a long time ago and we have been adapting it, but it may not be up to date with current upstream code standards, if so, please inform me so I can update the patch.

Audit update

---

lib/commonio.c

Link: <https://github.com/shadow-maint/shadow/pull/1222#discussion_r1966612238>
Link: <https://stackoverflow.com/questions/60802732/are-realpath-portability-concerns-obsolete>
Reported-by: @sthibaul

lib/commonio.c: Rely on the POSIX.1-2008 behavior of realpath(3)

---

doc/contributions/ci.md

Since c8e8557803f3e335eff33009329e0b5b8e464a15 we also run openSUSE in CI.
Minor thing that I forgot in my last PR.

doc: add recently added distribution to list

---

lib/pam_pass.c

The exit code situation is a hot mess. Do a
git grep "define.*E_SUCCESS"
Each src/*.c is defining its own set of error codes, and they are frequently conflicting, e.g. more than one use 10.
We should probably have a common set defined in lib/exitcodes.h. I'm thinking for a first cut, we just move all the definitions from src/*.c to lib/exitcodes.h, and let the conflicts stand. If we later want to change some defines to make them unambiguous across the project, we can do that separately.

Quick fix: define E_PAM_ERR in lib/pam_pass.c

---

src/useradd.c
src/usermod.c

Relevant on fully-usr-merged distributions.
Reported-by: Marc Haber @zugschlus

Accept /usr/sbin/nologin as an alternate to /sbin/nologin

---

lib/getdef.c

util-linux-2.41 introduced new variable: LOGIN_ENV_SAFELIST. Add it to known login.defs variables.

Add LOGIN_ENV_SAFELIST to FOREIGNDEFS

---

share/ansible/roles/ci_run/tasks/fedora.yml

Recently fedora 42 was released and `gawk` was missing as a dependency.

ci: add `gawk` as a fedora dependency

---

lib/getdate.y
lib/strtoday.c
man/chage.1.xml
man/passwd.1.xml
man/shadow.5.xml

-  This is a subset of <https://github.com/shadow-maint/shadow/pull/1217> (revision v2h), to make it easier to review.
This PR removes features of get_date() that we don't really need or want.
It is in preparation of a future replacement of this code by a C implementation.
Cc: @zeha , @timparenti
---
Revisions:
<details>
-  Squash a few commits.  [@timparenti ]
<details>
<summary>Range-diff:</summary>
```
alx@devuan:~/src/shadow/shadow/master$ git range-diff shadow/master gh/gd gd
1:  0b830153 <  -:  -------- lib/getdate.y: Do not parse am/pm time syntax; just 24h
2:  ce35738c !  1:  13de308c lib/getdate.y: Do not parse times; just dates
@@ Metadata
-    lib/getdate.y: Do not parse times; just dates
+    lib/getdate.y: …
```

lib/getdate.y: Restrict the date formats that we support

---

src/newgidmap.c
src/newuidmap.c

The handling for `sub_uid_open` relies on `commonio_open` preserving `errno`, which it appears to make an effort do, but doesn't explicitly document.
Closes: #1253

newuidmap: better error logging on failure

---

tests/system/etc/login.defs
tests/system/framework/hosts/base.py
tests/system/framework/hosts/shadow.py
tests/system/framework/misc/__init__.py
tests/system/framework/utils/tools.py
tests/system/tests/test_groupadd.py
tests/system/tests/test_groupdel.py
tests/system/tests/test_groupmod.py
tests/system/tests/test_useradd.py
tests/system/tests/test_userdel.py
tests/system/tests/test_usermod.py

The test framework PoC only provided basic checks. I've added additional
functionality to the framework by checking shadow and gshadow entries
and I've extended the basic test cases to check those too.
This should give us more coverage over the changes we make to the basic
functionality and ensure that we don't change anything inadvertently.

Extend basic test cases to check shadow and gshadow entries

---

lib/fields.c
lib/setupenv.c
src/useradd.c
src/usermod.c

Checking a boolean (actually, a boolean-like pointer) is more readable
than comparing against a length.
This removes the only uses of strcspn(3) in this project.
strpbrk(3) is a simpler call, even though it has a weird name.  It's
just like strchr(3) but searches for several characters.  I'd have named
it strchrs().
---
@hallyn   Oh well, this is your fault for mentioning that.  :D
---
Revisions:
<details>
-  Since strpbrk(3) is like strchr(3), use it similarly.  That is, treat it as a boolean, with the meaning "the characters were found".  Act as if it was called strchrs().
-  Use spaces instead of tabs.
```
$ git range-diff shadow/master gh/strpbrk strpbrk 
1:  878792c7 ! 1:  72823449 src/: Simplify, using strpbrk(3)
@@ Metadata
src/: Simplify, using strpbrk(3)
- …
```

src/: Simplify, using strpbrk(3)

---

lib/string/strdup/strndupa.h

Cc: @chqrlie
---
Revisions:
<details>
-  Implement STRDUPA() instead of a macro that checks if the argument is a string literal.  This is what we want in the first place.
```
$ git range-diff master gh/sl sl 
1:  76257601 < -:  -------- lib/typetraits.h: is_string_literal(): Add macro
-:  -------- > 1:  dd4fa7bb lib/strdup/: STRDUPA(): Add macro
```
</details>
<details>
-  Fix commit message
```
$ git range-diff master gh/sl sl 
1:  dd4fa7bb ! 1:  6cc16778 lib/strdup/: STRDUPA(): Add macro
@@ Metadata
-    lib/strdup/: STRDUPA(): Add macro
+    lib/string/strdup/: STRDUPA(): Add macro
This is like strdupa(3), but we make sure that the argument is a string
literal, which makes sure that we won't have a …
```

lib/string/strdup/: STRNDUPA(): Reimplement in terms of strndupa(3)

---

lib/Makefile.am
lib/obscure.c
lib/string/ctype/strtoascii/strtolower.c
lib/string/ctype/strtoascii/strtolower.h

---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/stl shadow/master..stl 
1:  851d24b5 = 1:  2740e5ff lib/string/ctype/strtoascii/: strtolower(): Add API
2:  6436ac02 = 2:  a6e78233 lib/: Use strtolower() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git rd
1:  2740e5ff = 1:  7db4fb87 lib/string/ctype/strtoascii/: strtolower(): Add API
2:  a6e78233 = 2:  9c7bc74e lib/: Use strtolower() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git rd 
1:  7db4fb87 = 1:  6fda0b3b lib/string/ctype/strtoascii/: strtolower(): Add API
2:  9c7bc74e ! 2:  b6e7a38f lib/: Use strtolower() instead of its pattern
@@ Commit message
- ## …
```

strtolower(): Add API, and use it instead of its pattern

---

tests/system/framework/roles/shadow.py
tests/system/tests/test_chage.py
tests/system/tests/test_useradd.py
tests/system/tests/test_usermod.py

Testing for https://github.com/shadow-maint/shadow/pull/1217

Test expiration date

---

contrib/adduser.c
lib/Makefile.am
lib/nss.c
lib/string/strcmp/strcaseprefix.c
lib/string/strcmp/strcaseprefix.h
lib/yesno.c

---
Revisions:
<details>
-  Rebase
```
$ git rd
1:  6d2e00ce = 1:  8eaa91b9 lib/string/strcmp/: strcaseprefix(): Add API
2:  9bc969ce = 2:  ab4a23b4 contrib/, lib/: Use strcaseprefix() instead of its pattern
3:  0bd6d7fd = 3:  77ca3e54 lib/nss.c: Use !strcaseprefix() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git rd
1:  8eaa91b9 = 1:  ac554acf lib/string/strcmp/: strcaseprefix(): Add API
2:  ab4a23b4 = 2:  cc1abefc contrib/, lib/: Use strcaseprefix() instead of its pattern
3:  77ca3e54 = 3:  daf5fa96 lib/nss.c: Use !strcaseprefix() instead of its pattern
```
</details>
<details>
-  Rebase
```
$ git rd
1:  ac554acf = 1:  7b7c8496 lib/string/strcmp/: strcaseprefix(): Add API
2:  cc1abefc = 2:  63f34ab8 …
```

[scp] Add strcaseprefix(), and use it instead of its pattern

---

lib/Makefile.am
lib/fields.c
lib/fields.h
lib/groupio.c
lib/prototypes.h
lib/pwio.c
lib/sgroupio.c
lib/shadowio.c
lib/string/ctype/strchrisascii/strchriscntrl.c
lib/string/ctype/strchrisascii/strchriscntrl.h
lib/string/ctype/strisascii/strisprint.c
lib/string/ctype/strisascii/strisprint.h
src/chage.c
src/chfn.c
src/chsh.c

This adds `strisprint()` and `strchriscntrl()`.
---
Revisions:
<details>
-  Rewrite the for loops in strisprint() and strchriscntrl().
-  Add comment desoupifying API names.
```
$ git range-diff shadow/master gh/vf vf 
1:  8561e822 ! 1:  9d2d0f66 lib/string/ctype/strisascii/: strisprint(): Add function
@@ lib/string/ctype/strisascii/strisprint.c (new)
@@
-+// SPDX-FileCopyrightText: 2024, Alejandro Colomar <alx@kernel.org>
++// SPDX-FileCopyrightText: 2024-2025, Alejandro Colomar <alx@kernel.org>
+// SPDX-License-Identifier: BSD-3-Clause
+
+
@@ lib/string/ctype/strisascii/strisprint.h (new)
+  if (streq(s, ""))
+          return false;
+
-+  for (unsigned char c = *s; !streq(s, ""); c = *s++) {
++  for (; !streq(s, ""); s++) {
++          unsigned char  c = *s;
++
+ …
```

valid_field(): Improve readability

---

lib/Makefile.am
lib/fs/mkstemp/fmkomstemp.c
lib/fs/mkstemp/fmkomstemp.h
lib/fs/mkstemp/mkomstemp.c
lib/fs/mkstemp/mkomstemp.h
src/useradd.c

This reduces the complexity of fmkomstemp() by adding a helper API, and moves this into the lib/fs/ library subdir.
---
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/fmkomstemp shadow/master..fmkomstemp 
1:  257e2aaf = 1:  aa3d3676 lib/fs/mkstemp/, src/: fmkomstemp(): Move function to separate file
2:  6b28ca78 = 2:  dae656e6 lib/fs/mkstemp/: mkostemp(): Split API from fmkomstemp()
```
</details>
<details>
-  Rebase
```
$ git range-diff master..gh/fmkomstemp shadow/master..fmkomstemp 
1:  aa3d3676 = 1:  3dfeb6fe lib/fs/mkstemp/, src/: fmkomstemp(): Move function to separate file
2:  dae656e6 = 2:  f6224cb4 lib/fs/mkstemp/: mkostemp(): Split API from fmkomstemp()
```
</details>
<details>
-  Rebase
```
$ …
```

lib/fs/mkstemp/, src/: Move fmkomstemp() to separate files under lib/fs/mkstemp/, and split into mkomstemp()

---

src/newusers.c

This array is only ever used as an array of 7.
```
alx@devuan:/srv/alx/src/shadow/shadow/master$ sed_rm_ccomments() {
perl -p -e 's%/\*.*?\*/%%g' \
|sed -E '\%/\*%, \%\*/% {\%(\*/|/\*)%!d}' \
|sed -E '\%/\*% {s%/\*.*%%; n; s%.*\*/%%;}' \
|sed -E '\%/\*% {s%/\*.*%%; n; s%.*\*/%%;}' \
|sed 's%//.*%%';
}
alx@devuan:/srv/alx/src/shadow/shadow/master$ cat src/newusers.c | grepc main | sed_rm_ccomments | grep -nT 'n\?fields\(\[.*]\)\?'
4:		char *fields[8];
5:		int nfields;
59:			for (cp = buf, nfields = 0; nfields < 7; nfields++) {
60:				fields[nfields] = strsep(&cp, ":");
64:			if (nfields != 6) {
72:			pw = pw_locate (fields[0]);
74:			if (NULL == pw && getpwnam(fields[0]) != NULL) {
77:					 Prog, fields[0]);
81:			if (NULL == pw && get_user_id(fields[2], &uid) != 0) {
91:			    && …
```

src/newusers.c: Fix off-by-one benign bug in array declaration

---

lib/Makefile.am
lib/gshadow.c
lib/list.c
lib/port.c
lib/sgetgrent.c
lib/sgetpwent.c
lib/sgetspent.c
lib/string/strtok/astrsep2ls.c
lib/string/strtok/astrsep2ls.h
lib/string/strtok/strsep2arr.c
lib/string/strtok/strsep2arr.h
lib/string/strtok/strsep2ls.c
lib/string/strtok/strsep2ls.h
lib/string/strtok/xastrsep2ls.c
lib/string/strtok/xastrsep2ls.h
lib/subordinateio.c
src/newusers.c

Suggested-by: @hallyn 
---
Revisions:
<details>
-  Workaround two GCC bugs [@uecker , @pinskia]
<https://gcc.gnu.org/bugzilla/show_bug.cgi?id=118044>
<https://gcc.gnu.org/bugzilla/show_bug.cgi?id=118043>
```
$ git range-diff master gh/astrsep2ls astrsep2ls 
1:  ad66293e !  1:  ccee0abc lib/string/strtok/: strsep2arr(), STRSEP2ARR(): Add APIs
@@ lib/string/strtok/strsep2arr.h (new)
+)
+
+
-+ATTR_ACCESS(read_write, 1) ATTR_ACCESS(write_only, 4)
++ATTR_ACCESS(read_write, 1) ATTR_ACCESS(write_only, 4, 3)
+ATTR_STRING(1) ATTR_STRING(2)
+inline ssize_t strsep2arr(char *s, const char *restrict delim,
+    size_t n, char *a[restrict n]);
2:  5f98de6e !  2:  95f4a921 lib/string/strtok/: strsep2ls(), STRSEP2LS(): Add APIs
@@ lib/string/strtok/strsep2ls.h (new)
+#define …
```

Add some wrappers for usual loops around strsep(3)

---

lib/defines.h
lib/fs/readlink/areadlink.h
lib/get_pid.c
src/login_nopam.c

86451e374b90 ("lib/fs/readlink/areadlink.h: areadlink(): Use PATH_MAX instead of a magic value") introduced using PATH_MAX, but e.g. GNU/Hurd does not define such a limitation.

lib/fs/readlink/areadlink.h: areadlink(): Avoid inconditionally using PATH_MAX

---

man/chage.1.xml
man/passwd.1.xml
man/shadow.5.xml
man/useradd.8.xml
man/usermod.8.xml

Hi! @ikerexxe suggested I could use the opportunity of #1238 to review and update these man pages. I did an initial review so we can start a discussion. 
I'm marking the PR as a draft as it depends on #1238

Update man pages for chage, shadow, passwd

---

tests/unit/Makefile.am
tests/unit/test_xaprintf.c

Fixes: 423fd652b563 (2025-06-03; "lib/string/sprintf/, tests/unit/: Transform x[v]asprintf() into x[v]aprintf()")
Closes: <https://github.com/shadow-maint/shadow/issues/1279>
Reported-by: @tgurr

tests/unit/test_xaprintf.c: Fix test by using streq() instead of strcmp(3)

---

lib/shadow/grp/agetgroups.h

Linux seems to at least write one group always from getgroups(2). However, POSIX doesn't guarantee this, and a system might have 0 groups.
It is implementation‐defined whether getgroups() also returns
the effective group ID in the grouplist array.
Considering such a system, the call getgroups(0,NULL) could indeed return 0, and the second call to getgroups might return a higher value, if the group list has grown in between (race condition).  If this is the case, we'd return an array of 0 elements (or 1, due to the MALLOC() trick to avoid calling it with 0), with no elements filled, but where ngids has been updated to have a positive value.  When the caller of agetgroups() reads the array, they'd overrun the buffer.
Fixes: 05322ed89a1c (2025-01-24; "lib/shadow/grp/: agetgroups(): Add …

lib/shadow/grp/: agetgroups(): Fix possible buffer overrun on non-Linux systems

---

lib/utmp.c

When no "ut_id" is provided by previous utmp file entry, "login" must generate its own "ut_id". Historically tty number  was used for it. However, if current device name is three characters or shorter, then empty "ut_id" is produced or even garbage is copied from uninitialised part of the "line".
This commit fixes it.
This patch uses unportable C extension Elvis operator as it is already used everywhere in the code.
Extracted from #1293

lib/utmp.c: Fixed generated strings for "ut_id"

---

lib/logind.c
lib/prototypes.h
lib/utmp.c
src/login.c

Number of fixes around using PID of forked or parent process.
A subset of commits from #1292, as requested [here](https://github.com/shadow-maint/shadow/pull/1292#discussion_r2215911542).

Fixes related to use of forked PID

---

.gitignore
Makefile.am
configure.ac

A set of random configure (and autotools) fixes and improvements.
As requested [here](https://github.com/shadow-maint/shadow/pull/1283#discussion_r2200800045).

fixes for configure and autotools

---

lib/Makefile.am
lib/chkhash.c
lib/chkhash.h
src/chpasswd.c

Add is_valid_hash to prevent adding a bad hash in /etc/shadow (and so prevent user to be lock) when using chpasswd -e
```sh
echo 'vinz:test123' | chpasswd -e
grep vinz /etc/shadow
vinz:test123:20280:0:99999:7:::
echo 'vinz:test123' |sudo ./chpasswd -e
chpasswd: (line: 1) invalid password hash for user 'vinz'
chpasswd: error detected, changes ignored
```

chpasswd: Check hash before write when using -e

---

lib/utmp.c

This PR fixes wrong utmp entry search, by better following algorithm expected by Linux kernel as described here: https://man7.org/linux/man-pages/man5/utmp.5.html#DESCRIPTION

Correct finding UTMP entry

---

lib/copydir.c
lib/find_new_gid.c
lib/find_new_uid.c
lib/gshadow.c
lib/port.c
lib/prefix_flag.c
lib/subordinateio.c
lib/user_busy.c
lib/utmp.c
src/groupmod.c
src/grpconv.c
src/grpunconv.c
src/logoutd.c
src/newgrp.c
src/pwconv.c
src/pwunconv.c
src/su.c
src/userdel.c
src/usermod.c

---
Revisions:
<details>
-  Rebase
```
$ git rd
1:  49e5b01a ! 1:  682e6ae8 lib/, src/: Reorder while() conditions for safety
@@ Metadata
lib/, src/: Reorder while() conditions for safety
-    In conditions that check for NULL after assignment, it's safer to put
-    the NULL check first, as a mistake would result in a compiler error,
-    as opposed to unwanted implicit conversions.  It's also more readable.
+    In conditions that perform simple assignment (=) before comparison,
+    it's safer to put the comparison first, as a mistake would result in a
+    compiler error, as opposed to assigning something incorrect.
+    It's also more readable, IMO.
```
</details>

While-loop readability improvements.

---

lib/agetpass.c

This is safer, since in general, readpassphrase(3) does not accept a null pointer as input.
This was discovered thanks to @chrisbazley's _Optional qualifier, which I'm testing at the moment.

lib/agetpass.c: Pass "" instead of NULL as an ignored prompt

---

src/chfn.c

I finally understood what this function was doing.  It was over-engineered, for supporting gecos fields that nobody should be writing in the first place.  It was also bogus: if the gecos field was missing some subfield, it left the buffers with garbage.  Even more buggy: if any of the first 4 CSV fields contained any '=' in them, those would be appended to the slop, regardless of oflg, which is inconsistent with the last lines, which parse the remaining slop depending on oflg.  This code was very broken.
---
Revisions:
<details>
-  wfix
-  Fix more bugs, and improve readability.
```
$ git range-diff shadow/master gh/gecos gecos 
1:  91431a96 ! 1:  8cfc1c19 src/chfn.c: Do not allow the 'slop' fields to appear before any non-slop gecos fields
@@ Commit message
2) …
```

Make parsing of gecos field more robust and strict

---

.github/workflows/static-code-analysis.yml
tests/system/framework/hosts/shadow.py
tests/system/framework/roles/shadow.py
tests/system/framework/utils/tools.py
tests/system/pyproject.toml
tests/system/tests/test_chage.py
tests/system/tests/test_groupadd.py
tests/system/tests/test_groupdel.py
tests/system/tests/test_groupmod.py
tests/system/tests/test_useradd.py
tests/system/tests/test_userdel.py
tests/system/tests/test_usermod.py

* Add rules for linters
* Fix existing Python linter issues
* Add Python linters to CI

CI: add Python linter

---

src/su.c

Fixes: 45c6603cc86c (2007-10-07; "[svn-upgrade] Integrating new upstream version, shadow (19990709)")
Closes: <https://github.com/shadow-maint/shadow/issues/1310>

src/su.c: Fix incorrect (non-matching) parentheses

---

lib/env.c
lib/obscure.c
lib/setupenv.c
lib/tcbfuncs.c
src/chfn.c
src/chpasswd.c
src/login_nopam.c
src/su.c

Among other things, remove most uses of strtok(3).  Replace its calls by strsep(3), which is stateless.
This probably silently fixes some bugs, where two separators were being merged as the same one.
Also, that's the reason why I didn't replace all strtok(3) calls.  In some cases (paths), it makes sense to merge adjacent `//`.
----
Revisions:
<details>
-  Rebase
```
$ git range-diff master..gh/string shadow/master..string 
1:  5ba4cfca !  1:  e825c03e lib/, src/: Use stpspn() instead of its pattern
@@ lib/getdate.y: yylex (void)
@@
- #include "atoi/a2i.h"
- #include "atoi/str2i.h"
+ #include "atoi/str2i/str2s.h"
+ #include "atoi/str2i/str2u.h"
#include "memzero.h"
+#include "string/strchr/stpspn.h"
#include "typetraits.h"
@@ lib/strtoday.c
@@
#ident "$Id$"
- …
```

lib/, src/: Use consistent style using strchr(3) in conditionals

---

lib/string/README

Suggested-by: @ikerexxe 
Suggested-by: @hallyn 
Suggested-by: @Karlson2k
Suggested-by: @lslebodn
Here, I've covered also some of the functions I haven't added yet.
<details>
-  Address some issues reported by @ikerexxe .
```
$ git range-diff master gh/strreadme strreadme 
1:  d6d127b6 ! 1:  cc66977f lib/string/README: Add guidelines for using strings
@@ lib/string/README (new)
+   (almost) exclusively.
+
+
-+Forbidden libc functions:
-+=========================
++Don't use some libc functions without Really Good Reasons:
++==========================================================
+
+<stdio.h>
+    asprintf(3)
@@ lib/string/README (new)
+    strcmp(3)
+  Use streq() instead.
+  The return value of strcmp(3) is confusing.
-+  strcmp(3) would be legitimate as a …
```

lib/string/README: Add guidelines for using strings
